public extension FeatureOperation {
    var capabilityOperation: String {
        switch self {
        case .sketch: return "sketch"
        case .primitive: return "primitive"
        case .extrude: return "extrude"
        case .revolve: return "revolve"
        case .sweep: return "sweep"
        case .loft: return "loft"
        case .boolean: return "boolean"
        case .polySpline: return "polySpline"
        case .bSplineSurface: return "bSplineSurface"
        case .patchSurface: return "patchSurface"
        case .faceLoopOffset: return "faceLoopOffset"
        case .edgeOffset: return "edgeOffset"
        case .faceKnife: return "faceKnife"
        case .faceDelete: return "faceDelete"
        case .faceDraft: return "faceDraft"
        case .faceOffset: return "faceOffset"
        case .faceMove: return "faceMove"
        case .edgeMove: return "edgeMove"
        case .vertexMove: return "vertexMove"
        case .linearPattern: return "linearPattern"
        case .radialPattern: return "radialPattern"
        case .gridPattern: return "gridPattern"
        case .curveDrivenPattern: return "curveDrivenPattern"
        case .chamfer: return "chamfer"
        case .fillet: return "fillet"
        case .g2Blend: return "g2Blend"
        case .setbackCorner: return "setbackCorner"
        case .shell: return "shell"
        case .thicken: return "thicken"
        case .bridgeCurve: return "bridgeCurve"
        case .bridgeSurface: return "bridgeSurface"
        case .curveEdit: return "curveEdit"
        case .curveOffset: return "curveOffset"
        case .curveTrim: return "curveTrim"
        case .curveExtend: return "curveExtend"
        case .curveMatch: return "curveMatch"
        case .surfaceOffset: return "surfaceOffset"
        case .surfaceTrim: return "surfaceTrim"
        case .surfaceExtend: return "surfaceExtend"
        case .surfaceMatch: return "surfaceMatch"
        }
    }
}
