public enum FeatureOperationKind: String, Codable, CaseIterable, Hashable, Sendable {
    case sketch
    case primitive
    case extrude
    case revolve
    case sweep
    case loft
    case boolean
    case polySpline
    case bSplineSurface
    case patchSurface
    case faceLoopOffset
    case edgeOffset
    case faceKnife
    case faceDelete
    case faceDraft
    case faceOffset
    case faceMove
    case edgeMove
    case vertexMove
    case linearPattern
    case radialPattern
    case gridPattern
    case curveDrivenPattern
    case chamfer
    case fillet
    case g2Blend
    case setbackCorner
    case shell
    case thicken
    case bridgeCurve
    case bridgeSurface
    case curveEdit
    case curveOffset
    case curveTrim
    case curveExtend
    case curveMatch
    case surfaceOffset
    case surfaceTrim
    case surfaceExtend
    case surfaceMatch
}
