import CADCore

extension KernelCapabilities {
  static let modelingEditCapabilities: [KernelCapability] = [
    feature(
      id: "MODEL-FACELOOPOFFSET-001",
      operation: "faceLoopOffset",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetBody",
        "oneOrMoreStableFacesOfThatBody",
        "positiveDistanceIntoTheFacesOverTheFacesAroundThemOrBoth",
        "symmetricIndividualOrCombinedWithRoundLinearOrNaturalGapFill",
      ],
      outputs: [
        "validatedExactBRep",
        "facesSplitAlongTheirOffsetOutlines",
        "offsetOverTheSurfaceOnPlanesAndCurvedFaces",
        "cornersCutWhereOffsetsCrossAndFilledWhereTheyPart",
        "sameSolidOrSheetTargetInItsPlace",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["EdgeOffsetFeatureTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-EDGEOFFSET-001",
      operation: "edgeOffset",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetBody",
        "oneOrMoreStableEdgesOfASupportFace",
        "positiveDistanceOverTheSupportFace",
        "symmetricAcrossEachEdgeWithRoundLinearOrNaturalGapFill",
      ],
      outputs: [
        "validatedExactBRep",
        "supportFaceSplitAlongTheOffsetChain",
        "openChainEndsCarriedToTheFaceBoundary",
        "offsetOverTheSurfaceOnPlanesAndCurvedFaces",
        "sameSolidOrSheetTargetInItsPlace",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["EdgeOffsetFeatureTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-FACEKNIFE-001",
      operation: "faceKnife",
      topology: .solidBody,
      inputs: [
        "oneValidatedSolidBody",
        "oneStableSelectedLineOnlyPlanarFaceWithOneOuterLoop",
        "oneCoplanarStrictlyInteriorSimpleLineKnifeLoopIncludingConcaveLoops",
      ],
      outputs: [
        "validatedExactSplitBRep",
        "coplanarRingAndCenterFaces",
        "affineFaceLocalPcurves",
        "preservedAnalyticVolume",
        "strictCurrentSchemaNativePersistence",
        "deterministicPreservedSplitAndGeneratedTopologyLineage",
        "typedAmbiguousSourceFaceSelectionAfterSplit",
        "noCarriedTopologyAliases",
      ],
      fixtures: ["FaceKnifeFeatureTests", "FaceKnifeBuilderTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .ambiguousSelection,
        .unsupportedCapability,
        .classificationFailure,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.FaceKnifeFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-FACEDELETE-001",
      operation: "faceDelete",
      topology: .sheetBody,
      inputs: [
        "oneValidatedSolidBody",
        "oneOrMoreUniqueStableSelectedFacesOwnedByTheTargetBody",
        "atLeastOneRemainingFaceInEverySourceShell",
      ],
      outputs: [
        "validatedExactSheetBRep",
        "deterministicEdgeConnectedShellPartition",
        "orphanFreeTopologyAndGeometry",
        "mandatoryFaceLocalPcurves",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "preservedUnrelatedBodiesAndSelections",
        "preservedBodyFaceEdgeAndVertexLineage",
      ],
      fixtures: [
        "FaceDeleteFeatureTests",
        "FaceDeleteSchemaTests",
        "FaceDeleteBuilderTests",
      ],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.FaceDeleteFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-FACEDRAFT-001",
      operation: "faceDraft",
      topology: .solidBody,
      inputs: [
        "oneValidatedSolid",
        "oneOrMoreUniquePlanarFacesOrCylindersAlongThePullDirectionOwnedByTargetBody",
        "eachDraftedFaceOnOneSideOfTheNeutralPlane",
        "onePlanarNeutralFaceOptionallyOffsetAlongItsOutwardSide",
        "finiteNonzeroIsoclineAngleBelowNinetyDegrees",
        "growMovingFixedOrNone",
      ],
      outputs: [
        "validatedExactBRep",
        "planesTurnedAboutTheirNeutralCrossingAndCylindersIntoCones",
        "neighbouringEdgesAndVerticesResolvedFromTheirSurfaces",
        "deterministicGeometryIDs",
        "mandatoryFaceLocalPcurves",
        "analyticVolume",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "preservedUnrelatedBodiesAndSelections",
        "preservedBodyFaceEdgeAndVertexLineage",
      ],
      fixtures: [
        "FaceDraftFeatureTests",
        "FaceDraftSchemaTests",
        "FaceDraftBuilderTests",
        "DraftFaceTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.FaceDraftFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-CHAMFER-001",
      operation: "chamfer",
      topology: .solidBody,
      inputs: [
        "singleStraightEdgeOwnedByTargetBody",
        "singleShellSolid",
        "twoPerpendicularPlanarIncidentFaces",
        "positiveEqualDistance",
      ],
      outputs: [
        "validatedExactBRep",
        "faceLocalPcurves",
        "analyticVolume",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "typedAmbiguousSourceEdgeSelectionAfterSplit",
        "TopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: [
        "ChamferFeatureTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
        .ambiguousSelection,
      ],
      additionalPublicAPIs: ["CADModeling.ChamferFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-FILLET-001",
      operation: "fillet",
      topology: .solidBody,
      inputs: [
        "singleStraightConvexEdgeOwnedByTargetBody",
        "singleShellOrthogonalSolid",
        "twoPerpendicularPlanarIncidentFaces",
        "positiveConstantRadius",
      ],
      outputs: [
        "validatedExactBRep",
        "quarterCylinder",
        "verifiedG1Tangency",
        "faceLocalPcurves",
        "analyticVolume",
        "deterministicEvaluation",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "typedAmbiguousSourceEdgeSelectionAfterSplit",
        "TopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: [
        "FilletFeatureTests",
        "EdgeBlendOwnershipTests",
        "CrossBodyReplacementFeatureTests",
        "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
        .ambiguousSelection,
      ],
      additionalPublicAPIs: ["CADModeling.FilletFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-G2BLEND-001",
      operation: "g2Blend",
      topology: .solidBody,
      inputs: [
        "singleStraightConvexEdgeOwnedByTargetBody",
        "singleShellOrthogonalSolid",
        "twoPerpendicularPlanarIncidentFaces",
        "positiveSymmetricSetbackDistance",
      ],
      outputs: [
        "validatedExactBRep",
        "quinticBSplineSurface",
        "verifiedG2Tangency",
        "faceLocalPcurves",
        "analyticVolume",
        "deterministicEvaluation",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "typedAmbiguousSourceEdgeSelectionAfterSplit",
        "TopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: [
        "G2BlendFeatureTests",
        "EdgeBlendOwnershipTests",
        "CrossBodyReplacementFeatureTests",
        "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
        .ambiguousSelection,
      ],
      additionalPublicAPIs: ["CADModeling.G2BlendFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-SETBACKCORNER-001",
      operation: "setbackCorner",
      topology: .solidBody,
      inputs: [
        "oneTargetBodyOwnedTrihedralConvexVertex",
        "oneOrthogonalHexahedralSolid",
        "threeMutuallyPerpendicularStraightEdges",
        "positiveEqualRollingBallRadius",
      ],
      outputs: [
        "validatedExactBRep",
        "threeQuarterCylinders",
        "sphericalOctant",
        "verifiedG1Tangency",
        "sphericalGreatCirclePcurves",
        "analyticVolume",
        "deterministicEvaluation",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "typedAmbiguousSourceVertexSelectionAfterSplit",
        "TopologyLineage",
        "deterministicRightHandedEdgeOrdering",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: [
        "SetbackCornerFeatureTests",
        "SetbackCornerOwnershipTests",
        "SphericalGreatCirclePcurveTests",
        "CrossBodyReplacementFeatureTests",
        "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
        .ambiguousSelection,
      ],
      additionalPublicAPIs: ["CADModeling.SetbackCornerFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-SHELL-001",
      operation: "shell",
      topology: .solidBody,
      inputs: [
        "oneOrthogonalHexahedralSolid",
        "oneTargetBodyOwnedRemovedPlanarFace",
        "positiveUniformInwardThickness",
      ],
      outputs: [
        "validatedExactBRep",
        "fiveOuterFaces",
        "fiveInnerOffsetFaces",
        "fourOpeningRimFaces",
        "analyticVolume",
        "deterministicEvaluation",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedCavityDepth",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "typedAmbiguousRemovedFaceSelectionAfterSplit",
        "dimensionPreservingTopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: [
        "ShellFeatureTests",
        "ShellOwnershipTests",
        "CrossBodyReplacementFeatureTests",
        "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
        .ambiguousSelection,
      ],
      additionalPublicAPIs: ["CADModeling.ShellFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-EDGEMOVE-001",
      operation: "edgeMove",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneLineOnlyPlanarSolid",
        "oneSolidOrSheetWhoseFacesAroundTheMovedVerticesArePlanarAndStraightEdged",
        "oneTargetBodyOwnedStraightEdge",
        "orOneCircularEdgeBoundingAPlanarCapMovedAlongItsAxisBetweenCoaxialCylindersAndAxisParallelPlanes",
        "finiteDirection",
        "finiteSignedDistancePreservingPlanarityAndVolume",
      ],
      outputs: [
        "validatedExactBRep",
        "faceLocalPcurves",
        "analyticVolume",
        "deterministicEvaluation",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "stableMovedEdgeSelection",
        "dimensionPreservingTopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
        "locallyResolvedPlanarOrBilinearIncidentFaces",
      ],
      fixtures: ["EdgeMoveFeatureTests", "EdgeMoveBuilderTests", "DirectEditSchemaTests", "LocalDirectEditTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.EdgeMoveFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-VERTEXMOVE-001",
      operation: "vertexMove",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneSingleShellLineOnlyPlanarSolid",
        "oneSolidOrSheetWhoseFacesAroundTheMovedVertexArePlanarAndStraightEdged",
        "oneTargetBodyOwnedVertex",
        "finiteDirection",
        "finiteSignedDistancePreservingPositiveVolume",
      ],
      outputs: [
        "validatedExactBRep",
        "nonPlanarIncidentFaceTriangulation",
        "faceLocalPcurves",
        "analyticVolume",
        "deterministicEvaluation",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "stableMovedVertexSelection",
        "splitAndPreservedTopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
        "locallyResolvedPlanarOrBilinearIncidentFaces",
      ],
      fixtures: ["VertexMoveFeatureTests", "VertexMoveBuilderTests", "DirectEditSchemaTests", "LocalDirectEditTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.VertexMoveFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-FACEOFFSET-001",
      operation: "faceOffset",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheet",
        "oneOrMoreTargetBodyOwnedFacesOnPlanesCylindersConesSpheresToriOrOffsettableSurfaces",
        "finiteSignedOutwardDistanceKeepingEveryEdgeAndFaceFromTurningOver",
        "optionalAdjacentAngleTiltingPlanarNeighboursAboutStraightEdges",
        "growMovingFixedOrNone",
      ],
      outputs: [
        "validatedExactBRep",
        "faceLocalPcurves",
        "analyticVolume",
        "deterministicEvaluation",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "stableOffsetFaceSelection",
        "dimensionPreservingTopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
        "neighbouringEdgesAndVerticesResolvedFromTheirSurfaces",
      ],
      fixtures: ["FaceOffsetFeatureTests", "FaceOffsetBuilderTests", "DirectEditSchemaTests", "LocalDirectEditTests", "PushFaceTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.FaceOffsetFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-TOPOLOGYTRANSFORM-001",
      operation: "topologyTransform",
      topology: .sheetOrSolidBody,
      inputs: [
        "facesEdgesAndVerticesOfOneSolidOrSheet",
        "translationRotationOrPositiveFrameScale",
        "planarStraightEdgedFacesAroundTheMovedVertices",
        "curvedEdgesAndWholeFacesMovedByARigidMotion",
      ],
      outputs: [
        "validatedExactBRep",
        "sharedVerticesMovedOnce",
        "locallyResolvedPlanarOrBilinearIncidentFaces",
        "wholeMovedFacesKeepTheirMappedOutwardSide",
        "faceLocalPcurves",
        "analyticVolume",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "dimensionPreservingTopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: ["TopologyTransformTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.TopologyTransformFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-FACEMOVE-001",
      operation: "faceMove",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneSolidOrSheetWhoseFacesAroundTheMovedFaceArePlanarAndStraightEdged",
        "orAPlanarFaceWithCircularOrBSplineEdgesTranslatedAlongTheAxisOfItsNeighbouringCylinders",
        "oneTargetBodyOwnedPlanarFace",
        "finiteDirection",
        "finiteSignedDistanceKeepingEveryFaceFromTurningOver",
      ],
      outputs: [
        "validatedExactBRep",
        "faceLocalPcurves",
        "analyticVolume",
        "deterministicEvaluation",
        "strictRequestDecoding",
        "strictCurrentSchemaNativePersistence",
        "targetBodyScopedIdentityReplacement",
        "targetBodyScopedLineageParents",
        "stableMovedFaceSelection",
        "dimensionPreservingTopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
        "locallyResolvedPlanarOrBilinearIncidentFaces",
      ],
      fixtures: ["FaceMoveFeatureTests", "FaceMoveBuilderTests", "DirectEditSchemaTests", "LocalDirectEditTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.FaceMoveFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-LINEARPATTERN-001",
      operation: "linearPattern",
      topology: .solidBody,
      inputs: [
        "oneLineOnlyPlanarSolid",
        "parameterPreservingRationalBSplineSolid",
        "finiteDirection",
        "positiveSpacing",
        "twoToOneThousandInstancesWithinExactBooleanUnionDomain",
      ],
      outputs: [
        "validatedExactMultiShellBRep",
        "preservedSolidComponentAndVoidShellOwnership",
        "parameterPreservingRationalBSplineIsometry",
        "faceLocalPcurves",
        "analyticVolume",
        "strictRequestDecoding",
        "splitTopologyLineage",
        "typedAmbiguousSourceSelection",
        "preservedUnrelatedBodiesAndSelections",
        "exactUnionOfOverlappingInstances",
      ],
      fixtures: [
        "LinearPatternFeatureTests",
        "LinearPatternFeatureTests.duplicatesSeparatedParameterPreservingBSplineBodyGeometry",
        "ExactPatternTransformTests", "LinearPatternBuilderTests",
        "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .ambiguousSelection,
        .unsupportedCapability,
        .resourceLimitExceeded,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.LinearPatternFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-RADIALPATTERN-001",
      operation: "radialPattern",
      topology: .solidBody,
      inputs: [
        "oneLineOnlyPlanarSolid",
        "parameterPreservingRationalBSplineSolid",
        "finiteAxis",
        "finiteNonzeroAngularSpacing",
        "twoToOneThousandInstancesWithinExactBooleanUnionDomain",
      ],
      outputs: [
        "validatedExactMultiShellBRep",
        "preservedSolidComponentAndVoidShellOwnership",
        "parameterPreservingRationalBSplineIsometry",
        "rigidlyRotatedAnalyticGeometry",
        "faceLocalPcurves",
        "analyticVolume",
        "strictRequestDecoding",
        "splitTopologyLineage",
        "typedAmbiguousSourceSelection",
        "preservedUnrelatedBodiesAndSelections",
        "exactUnionOfOverlappingOrCoincidentInstances",
      ],
      fixtures: [
        "RadialPatternFeatureTests", "ExactPatternTransformTests", "PatternBuilderTests",
        "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .ambiguousSelection,
        .unsupportedCapability,
        .resourceLimitExceeded,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.RadialPatternFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-GRIDPATTERN-001",
      operation: "gridPattern",
      topology: .solidBody,
      inputs: [
        "oneLineOnlyPlanarSolid",
        "parameterPreservingRationalBSplineSolid",
        "twoFiniteNonparallelDirections",
        "twoPositiveSpacings",
        "fourToOneThousandInstancesWithinExactBooleanUnionDomain",
      ],
      outputs: [
        "validatedExactMultiShellBRep",
        "preservedSolidComponentAndVoidShellOwnership",
        "parameterPreservingRationalBSplineIsometry",
        "faceLocalPcurves",
        "analyticVolume",
        "strictRequestDecoding",
        "splitTopologyLineage",
        "typedAmbiguousSourceSelection",
        "preservedUnrelatedBodiesAndSelections",
        "exactUnionOfOverlappingInstances",
      ],
      fixtures: [
        "GridPatternFeatureTests", "ExactPatternTransformTests", "PatternBuilderTests",
        "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .ambiguousSelection,
        .unsupportedCapability,
        .resourceLimitExceeded,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.GridPatternFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-CURVEDRIVENPATTERN-001",
      operation: "curveDrivenPattern",
      topology: .solidBody,
      inputs: [
        "oneLineOnlyPlanarSolid",
        "parameterPreservingRationalBSplineSolid",
        "oneConnectedOpenOrClosedEvaluatedCurveChain",
        "finiteAnchorAndReferenceDirection",
        "twoToOneThousandInstancesWithinExactBooleanUnionDomain",
      ],
      outputs: [
        "validatedExactMultiShellBRep",
        "preservedSolidComponentAndVoidShellOwnership",
        "parameterPreservingRationalBSplineIsometry",
        "equalArcLengthPlacement",
        "closedPathPlacementWithoutDuplicateClosure",
        "minimumRotationTangentAlignment",
        "faceLocalPcurves",
        "analyticVolume",
        "strictRequestDecoding",
        "splitTopologyLineage",
        "typedAmbiguousSourceSelection",
        "preservedUnrelatedBodiesAndSelections",
        "exactUnionOfOverlappingInstances",
      ],
      fixtures: [
        "CurveDrivenPatternFeatureTests",
        "CurveDrivenPatternFeatureTests.distributesInstancesAroundClosedPathWithoutDuplicatingClosure",
        "ExactPatternTransformTests", "CurveDrivenPatternBuilderTests",
        "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .ambiguousSelection,
        .unsupportedCapability,
        .resourceLimitExceeded,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.CurveDrivenPatternFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-MIRROR-001",
      operation: "mirror",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneLineOnlyPlanarSolid",
        "parameterPreservingRationalBSplineSolid",
        "oneSheetProvenClearOfOrOneSidedAgainstTheMirrorPlane",
        "finiteNonzeroMirrorPlaneNormal",
        "twoInstancesWithinExactBooleanUnionDomain",
      ],
      outputs: [
        "validatedExactMultiShellBRep",
        "preservedSolidComponentAndVoidShellOwnership",
        "orientationCorrectParameterPreservingRationalBSplineReflection",
        "faceLocalPcurves",
        "analyticVolume",
        "strictRequestDecoding",
        "splitTopologyLineage",
        "typedAmbiguousSourceSelection",
        "preservedUnrelatedBodiesAndSelections",
        "exactUnionOfOverlappingOrCoincidentInstances",
        "sheetPlacedBesideOrSewnToItsReflection",
      ],
      fixtures: [
        "MirrorFeatureIntegrationTests",
        "SheetMirrorIntegrationTests",
        "LinearPatternFeatureTests.mirrorsParameterPreservingBSplineBodyGeometry",
        "ExactPatternTransformTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .ambiguousSelection,
        .unsupportedCapability,
        .resourceLimitExceeded,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.MirrorFeatureEvaluator"]
    ),
    feature(
      id: "MODEL-JOIN-001",
      operation: "joinBodies",
      topology: .sheetOrSolidBody,
      inputs: [
        "twoOrMoreValidatedSolidBodiesOrTwoOrMoreValidatedSheetBodies",
        "pairwiseDisjointMaterialRegionsAndBoundariesForSolids",
        "sheetsConnectedThroughBoundaryEdgesCoincidentWithinModelingTolerance",
        "optionalRigidPlacementPerTargetIntoTheJoinedFrame",
      ],
      outputs: [
        "validatedExactMultiShellBRep",
        "untouchedSourceShellTopologyAndGeometry",
        "singleJoinedBodyOwningEverySourceShell",
        "explicitSolidComponentAndVoidShellOwnership",
        "fullIntersectionAndContainmentValidationWhenBoundsOverlap",
        "sheetsSewnIntoOneShellWithOneFrontSideAgreeingWithTheFirstSheet",
        "closedSewnSheetsBecomeAnOutwardFacingSolid",
        "mergedBodyTopologyLineage",
        "strictCurrentSchemaNativePersistence",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: ["JoinUnjoinFeatureIntegrationTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .singularGeometry,
        .intersectionFailure,
        .nonDiscreteIntersection,
        .classificationFailure,
        .resourceLimitExceeded,
        .topologyFailure,
        .nonManifoldResult,
      ]
    ),
    feature(
      id: "MODEL-UNJOIN-001",
      operation: "unjoinBody",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetBodyWithOneOrMoreComponents"
      ],
      outputs: [
        "validatedExactBRep",
        "untouchedSourceShellTopologyAndGeometry",
        "oneBodyPerSolidComponentOrSheetShell",
        "preservedOuterAndOwnedVoidShellGrouping",
        "preservedSingleBodyOrSplitMultiBodyTopologyLineage",
        "strictCurrentSchemaNativePersistence",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: ["JoinUnjoinFeatureIntegrationTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: [
        "CADModeling.UnjoinBodyFeatureEvaluator",
        "CADTopology.BRepModel.solidShellComponents",
      ]
    ),
    feature(
      id: "MODEL-UNJOIN-002",
      operation: "unjoinFaces",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetBody",
        "everyFaceOrStableFacesOfThatBody",
      ],
      outputs: [
        "validatedExactBRep",
        "oneSheetBodyInTheSourcesPlace",
        "oneShellPerSeparatedFace",
        "oneShellPerConnectedRemainingPiece",
        "unchangedFaceGeometryTrimAndSide",
        "consumedSourceBodyAndSubshapes",
        "faceLineageToTheSeparatedFaces",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["UnjoinFacesFeatureTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-REVERSE-SHEET-001",
      operation: "reverseSheet",
      topology: .sheetBody,
      inputs: ["oneValidatedSheetBody"],
      outputs: [
        "validatedExactBRep",
        "oneSheetBodyInTheSourcesPlace",
        "everyFaceTurnedToItsOtherSide",
        "unchangedFaceGeometryTrimAndShellGrouping",
        "consumedSourceBodyAndSubshapes",
        "faceLineageToTheReversedFaces",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["ReverseSheetFeatureTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-FACEMATCH-001",
      operation: "faceMatch",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetTargetBody",
        "oneOrMoreUniqueFacesOfTheTarget",
        "oneReferenceFaceOfTheTargetOrOfAnotherBodyWithItsRelativePlacement",
        "frontOrKeptOutwardSide",
        "growMovingFixedOrNone",
      ],
      outputs: [
        "validatedExactBRep",
        "matchedFacesOnTheReferenceSurface",
        "neighbouringEdgesAndVerticesResolvedFromTheirSurfaces",
        "sameSolidOrSheetTargetInItsPlace",
        "untouchedReferenceBody",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["MatchFaceTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-IMPRINT-001",
      operation: "imprintBody",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetTargetBody",
        "oneValidatedSolidOrSheetToolBody",
        "completionNoneOrEdge",
      ],
      outputs: [
        "validatedExactBRep",
        "targetFacesSplitWhereTheToolCrossesThem",
        "bothSidesOfEveryCrossingKept",
        "sameSolidOrSheetTargetInItsPlace",
        "untouchedToolBody",
        "endsInsideAFaceCarriedToAnEdgeWithEdgeCompletion",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["ImprintFeatureTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-ISOPARAM-001",
      operation: "isoparam",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetBody",
        "oneStableFaceOfThatBody",
        "uOrVLinesAtFractionsOfTheFaceExtent",
      ],
      outputs: [
        "validatedExactBRep",
        "faceSplitAlongItsParameterLines",
        "neighbouringEdgesSplitWhereTheLinesMeetThem",
        "optionalControlNetSubdivisionKeepingShape",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["ImprintFeatureTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-UNTRIM-001",
      operation: "untrimFace",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetBody",
        "oneStableFaceOfThatBody",
      ],
      outputs: [
        "validatedExactBRep",
        "oneSheetOfTheFacesUntrimmedSurface",
        "boundedDomainOrFaceExtentInEachDirection",
        "optionalFaceBoundaryImprintedOnTheSheet",
        "untouchedSourceBody",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["ImprintFeatureTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-IMPRINT-002",
      operation: "imprintCurves",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetTargetBody",
        "oneOrMoreBoundedExactCurves",
        "normalOrVectorProjectionWithBidirectionalAndOcclusionOptions",
        "completionNoneEdgeOrBoundary",
      ],
      outputs: [
        "validatedExactBRep",
        "targetFacesSplitAlongTheProjectedCurves",
        "vectorProjectionAsTheCurvesSweepCrossingTheTarget",
        "normalProjectionThroughSharedEdgePoints",
        "sameSolidOrSheetTargetInItsPlace",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["ImprintFeatureTests"],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-EXTRACT-001",
      operation: "extract",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetBody",
        "componentIndexAndExpectedComponentCountOrStableFaceReferences",
      ],
      outputs: [
        "validatedExactBRep",
        "untouchedSourceBody",
        "oneComponentCopiedAsItsOwnBodyOrChosenFacesCopiedAsASheet",
        "wholeShellsOfChosenFacesCopiedAsASolidWithTheirVoidsOrCavityShapes",
        "publicFaceClosureQuery",
        "componentsOrderedBySmallestFaceIdentity",
        "copiedTopologyLineageToSourceSubshapes",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["ExtractFeatureTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-WRAP-001",
      operation: "wrap",
      topology: .sheetOrSolidBody,
      inputs: [
        "oneValidatedSolidOrSheetBody",
        "stableReferenceAndTargetFaces",
        "uvnScaleOffsetMirrorSwapAndNormalFlip",
      ],
      outputs: [
        "validatedExactBRep",
        "sourceTopologyAndTrimsCarriedOntoFittedBSplineSupports",
        "surfaceAndEdgeFitsWithinAQuarterOfTheDistanceTolerance",
        "orientationRestoredWhenTheMapTurnsSpaceInsideOut",
        "sourceReplacedUnlessKept",
        "carriedTopologyLineageToSourceSubshapes",
        "strictCurrentSchemaNativePersistence",
      ],
      fixtures: ["WrapFeatureTests"],
      status: .supported,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .singularGeometry,
        .resourceLimitExceeded,
        .topologyFailure,
      ]
    ),
    feature(
      id: "MODEL-THICKEN-001",
      operation: "thicken",
      topology: .sheetToSolidBody,
      inputs: [
        "oneValidatedSingleShellSheetBody",
        "oneRegularExactTrimmedFaceOrManifoldCanonicalPlanarLineBoundaryFaceNetwork",
        "oneOuterLoopAndZeroOrMoreInnerLoopsPerFace",
        "positiveUniformThickness",
        "positiveNegativeOrSymmetricSide",
      ],
      outputs: [
        "validatedExactBRep",
        "exactOffsetCapSolid",
        "ruledBoundaryWalls",
        "intersectedPolyhedralOffsetSeamsAndMiterVertices",
        "faceLocalPcurves",
        "analyticVolume",
        "strictRequestDecoding",
        "dimensionPreservingTopologyLineage",
        "preservedUnrelatedBodiesAndSelections",
      ],
      fixtures: [
        "ThickenFeatureTests", "ThickenBuilderTests", "CrossBodyReplacementFeatureTests",
        "ModelingFeatureSchemaTests",
      ],
      status: .partial,
      failureCodes: [
        .invalidInput,
        .missingReference,
        .unsupportedCapability,
        .singularGeometry,
        .topologyFailure,
        .nonManifoldResult,
      ],
      additionalPublicAPIs: ["CADModeling.ThickenFeatureEvaluator"]
    ),
  ]
}
