extension CertifiedConeConeIntersectionCurve: NormalizedSurfaceIntersectionCurveEvaluating {}
extension CertifiedConeCylinderIntersectionCurve: NormalizedSurfaceIntersectionCurveEvaluating {}
extension CertifiedParallelTorusTorusIntersectionCurve: NormalizedSurfaceIntersectionCurveEvaluating {}
extension CertifiedSphereConeIntersectionCurve: NormalizedSurfaceIntersectionCurveEvaluating {}
