import CADCore

extension KernelCapabilities {
    static let modelingCurveSurfaceCapabilities: [KernelCapability] = [
        feature(
            id: "MODEL-BRIDGECURVE-001",
            operation: "bridgeCurve",
            topology: .curve,
            inputs: [
                "twoStableFiniteExactCurveEndpointReferences",
                "explicitG0G1OrG2Continuity",
                "optionalPositiveEndpointDerivativeMagnitudes",
            ],
            outputs: [
                "exactPolynomialBezierBSplineCurve",
                "verifiedEndpointContinuity",
                "kernelDerivedDisplaySamples",
                "strictRequestDecoding",
                "upstreamCurveReevaluationPropagation",
            ],
            fixtures: [
                "BridgeCurveFeatureTests",
                "BridgeCurveCommandParityTests",
                "CurveDerivedSamplingSchemaTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularGeometry,
                .resourceLimitExceeded,
            ],
            additionalPublicAPIs: [
                "CADModeling.BridgeCurveFeatureEvaluator",
                "CADModeling.CurveBridgeSolver",
            ]
        ),
        feature(
            id: "MODEL-BRIDGESURFACE-001",
            operation: "bridgeSurface",
            topology: .sheetBody,
            inputs: [
                "twoFinitePositiveWeightRationalBSplineBoundaries",
                "forwardOrReversedEndOrientation",
                "finiteNonDegenerateIndependentParameterDomains",
                "intervalCertifiedRegularAndGloballyEmbeddedRuledSpan",
            ],
            outputs: [
                "validatedExactSheetBRep",
                "rationalRuledBSplineSurface",
                "exactBoundaryInterpolation",
                "normalizedUnionKnotBasis",
                "homogeneousExactDegreeElevation",
                "faceLocalPcurves",
                "strictRequestDecoding",
                "deterministicGeneratedTopologyLineage",
            ],
            fixtures: [
                "BSplineCurveCommonBasisResolverTests",
                "SurfaceFeatureEvaluatorTests",
                "BridgeSurfaceBuilderTests",
                "NativeOperationSchemaTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .singularGeometry,
                .resourceLimitExceeded,
                .topologyFailure,
            ],
            additionalPublicAPIs: [
                "CADGeometry.BSplineCurveCommonBasisResolving",
                "CADGeometry.DefaultBSplineCurveCommonBasisResolver",
                "CADGeometry.RuledBSplineSurfaceBuilding",
                "CADGeometry.ExactRuledBSplineSurfaceBuilder",
                "CADModeling.BridgeSurfaceFeatureEvaluator",
            ]
        ),
        feature(
            id: "MODEL-PATCHSURFACE-001",
            operation: "patchSurface",
            topology: .sheetBody,
            inputs: [
                "fourFinitePositiveWeightRationalBSplineBoundaries",
                "explicitIndependentBoundaryOrientations",
                "cornerCoincidenceWithinTolerance",
                "intervalCertifiedRegularAndGloballyEmbeddedCoonsSpan",
            ],
            outputs: [
                "validatedExactSheetBRep",
                "exactRationalCoonsBSplineSurface",
                "positiveProductDenominator",
                "exactBernsteinProductNumerator",
                "fourExactBoundaryInterpolants",
                "faceLocalPcurves",
                "strictRequestDecoding",
                "deterministicGeneratedTopologyLineage",
            ],
            fixtures: [
                "ExactCoonsBSplineSurfaceBuilderTests",
                "SurfaceFeatureEvaluatorTests",
                "PatchSurfaceBuilderTests",
                "NativeOperationSchemaTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .singularGeometry,
                .resourceLimitExceeded,
                .topologyFailure,
            ],
            additionalPublicAPIs: [
                "CADGeometry.TransfiniteBSplineSurfaceBuilding",
                "CADGeometry.ExactCoonsBSplineSurfaceBuilder",
                "CADModeling.PatchSurfaceFeatureEvaluator",
            ]
        ),
        feature(
            id: "MODEL-CURVEEDIT-001",
            operation: "curveEdit",
            topology: .curve,
            inputs: ["exactBSplineCurveSelection", "controlPointKnotOrWeightEdits"],
            outputs: [
                "validatedExactBSplineCurve",
                "atomicOrderedEditApplication",
                "preservedFiniteTrimDomain",
                "kernelDerivedDisplaySamples",
                "strictRequestDecoding",
            ],
            fixtures: [
                "CurveEditFeatureTests",
                "CurveDerivedSamplingSchemaTests",
                "CurveEditCommandParityTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
            ],
            additionalPublicAPIs: ["CADModeling.CurveEditFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEOFFSET-001",
            operation: "curveOffset",
            topology: .curve,
            inputs: [
                "exactLineCircleOrArc",
                "positiveDistance",
                "coplanarOrientedPlaneNormal",
                "leftOrRightSide",
            ],
            outputs: [
                "exactRepresentationPreservingAnalyticCurve",
                "preservedParameterDomain",
                "physicalRadiusOffset",
                "closedFullTurnMetadata",
                "derivedDisplaySamples",
                "strictRequestDecoding",
            ],
            fixtures: [
                "CurveOffsetTrimFeatureTests",
                "CurveOffsetTrimBuilderTests",
                "CurveOffsetCommandParityTests",
            ],
            status: .partial,
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability],
            additionalPublicAPIs: ["CADModeling.CurveOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-PROJECT-CURVE-001",
            operation: "projectCurve",
            topology: .curve,
            inputs: [
                "finiteRegularExactCurve3D",
                "finiteNonzeroTargetPlaneNormal",
                "optionalNonGrazingProjectionDirection",
            ],
            outputs: [
                "exactRepresentationPreservingProjectedCurve",
                "affineControlPointBSplineProjection",
                "axisAlignedTranslatedCircleProjection",
                "exactRationalQuadraticObliqueConicProjection",
                "parameterPreservingExactAffineImageForGeneralCurves",
                "outwardRoundedWholeIntervalRegularityCertificate",
                "recomputedLineArcLengthDomain",
                "derivedDisplaySamples",
                "strictRequestDecoding",
            ],
            fixtures: [
                "ProjectCurveFeatureIntegrationTests",
                "ProjectCurveAffineImageTests",
                "CurveRegularityValidatorTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularGeometry,
                .intersectionFailure,
                .resourceLimitExceeded,
            ],
            additionalPublicAPIs: ["CADModeling.ProjectCurveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVETRIM-001",
            operation: "curveTrim",
            topology: .curve,
            inputs: ["exactCurve", "containedFiniteParameterDomain"],
            outputs: [
                "unchangedExactCurve",
                "finiteTrimDomain",
                "periodicSpanLimitedToOneTurn",
                "derivedDisplaySamples",
                "strictRequestDecoding",
            ],
            fixtures: [
                "CurveTrimFeatureEvaluatorTests",
                "CurveTrimCommandParityTests",
                "CurveOffsetTrimBuilderTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularGeometry,
                .intersectionFailure,
                .nonDiscreteIntersection,
                .resourceLimitExceeded,
            ],
            additionalPublicAPIs: ["CADModeling.CurveTrimFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEEXTEND-001",
            operation: "curveExtend",
            topology: .curve,
            inputs: ["finiteExactLineOrCircularArc", "startEndOrBoth", "positiveExtensionLength"],
            outputs: [
                "exactExtendedCurve",
                "expandedFiniteParameterDomain",
                "physicalLengthParameterConversion",
                "closedFullTurnMetadata",
                "derivedDisplaySamples",
                "strictRequestDecoding",
            ],
            fixtures: [
                "CurveExtendFeatureTests",
                "CurveExtendBuilderTests",
                "CurveExtendCommandParityTests",
            ],
            status: .partial,
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure],
            additionalPublicAPIs: ["CADModeling.CurveExtendFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEMATCH-001",
            operation: "curveMatch",
            topology: .curve,
            inputs: [
                "oneFiniteRegularExactCurve3DSourceEndpoint",
                "oneFiniteRegularExactCurve3DTargetEndpoint",
                "explicitTargetOrientation",
                "G0G1OrG2Request",
            ],
            outputs: [
                "exactQuinticHermiteBSpline",
                "requestedMatchedEndpointContinuity",
                "preservedOppositeSourceEndpointG2Jet",
                "stableTangentAngleResidual",
                "derivedDisplaySamples",
                "strictRequestDecoding",
            ],
            fixtures: [
                "CurveMatchFeatureTests",
                "CurveMatchBuilderTests",
                "CurveMatchCommandParityTests",
                "CurveDerivedSamplingSchemaTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularSystem,
                .conflictingConstraints,
                .resourceLimitExceeded,
                .topologyFailure,
            ],
            additionalPublicAPIs: ["CADModeling.CurveMatchFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SURFACEOFFSET-001",
            operation: "surfaceOffset",
            topology: .sheetBody,
            inputs: [
                "explicitStableSelectedFaceOwnedByReferencedSheetBody",
                "selectedFaceIsOnlyFaceOfSingleShellSheetBody",
                "oneSingleFaceRegularExactSurfaceSheet",
                "everyValidatedSurface3DRepresentation",
                "oneOuterAndZeroOrMoreInnerExactPcurveLoops",
                "everyValidatedSurfaceParameterCurveRepresentation",
                "finiteParameterBoundsAndCertifiableOffsetRegularity",
                "finiteNonzeroSignedNormalDistance",
            ],
            outputs: [
                "validatedExactSheetBRep",
                "sameParameterExactOffsetSurface",
                "analyticOffsetSimplificationOrCertifiedProceduralOffset",
                "exactSurfaceLiftBoundaryCurves",
                "sameParameterFaceLocalPcurves",
                "preservedOuterAndInnerLoopTopology",
                "freshFeatureScopedSurfaceAndCurveIdentities",
                "preservedTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
                "strictCurrentSchemaNativePersistence",
                "deterministicStableFaceResolutionWithoutImplicitFaceSelection",
            ],
            fixtures: [
                "SurfaceOffsetFeatureTests",
                "SameParameterSurfaceParameterCurveTests",
                "SurfaceOffsetBuilderTests",
                "DirectEditSchemaTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularGeometry,
                .singularSystem,
                .classificationFailure,
                .resourceLimitExceeded,
                .topologyFailure,
            ],
            additionalPublicAPIs: [
                "CADGeometry.SameParameterSurfaceParameterCurve",
                "CADModeling.SurfaceOffsetFeatureEvaluator",
            ]
        ),
        feature(
            id: "MODEL-SURFACETRIM-001",
            operation: "surfaceTrim",
            topology: .sheetBody,
            inputs: [
                "explicitStableSelectedFaceOwnedByReferencedSheetBody",
                "selectedFaceIsOnlyFaceOfSingleShellSheetBody",
                "oneSingleFaceFourEdgeExactRectangularSheet",
                "planeCylinderConeSphereTorusOrRationalBSplineSurface",
                "oneClosedOuterExactPcurveLoop",
                "zeroOrMoreDisjointClosedInnerExactPcurveLoops",
                "affineHarmonicPolylineRationalBSplineGreatCircleOrCertifiedIntersectionPcurves",
                "certifiablySimpleStrictlyContainedFiniteParameterRegion",
            ],
            outputs: [
                "validatedExactTrimmedSheetBRep",
                "unchangedCanonicalExactSurface",
                "exactSurfaceLiftBoundaryCurvesAndOrientedPcurves",
                "deterministicFeatureScopedCurveIdentities",
                "preservedBodyAndFaceLineage",
                "generatedBoundaryEdgeAndVertexLineage",
                "preservedUnrelatedBodiesAndSelections",
                "strictCurrentSchemaNativePersistence",
                "deterministicStableFaceResolutionWithoutImplicitFaceSelection",
            ],
            fixtures: [
                "SurfaceTrimExtendFeatureTests.trimsEveryExactSurfaceRepresentation",
                "SurfaceTrimExtendFeatureTests.trimsAReversedCanonicalBoundaryWithoutChangingLoopOrientation",
                "SurfaceTrimExtendFeatureTests.rejectsTrimThatDoesNotRemoveAParameterRegion",
                "SurfaceTrimExtendFeatureTests.trimsExactHarmonicOuterBoundaryWithAnInnerHole",
                "SurfaceTrimExtendFeatureTests.trimsWithExactRationalBSplineOuterBoundary",
                "SurfaceTrimExtendFeatureTests.rejectsSelfIntersectingExactTrimLoop",
                "SurfaceTrimExtendFeatureTests.rejectsExactTrimBoundaryOutsideTheSourceFace",
                "SurfaceParameterCurveAreaIntegratorTests.certificateBackedPcurvesProduceBoundedCoverageEnclosures",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.bothAnalyticPairRolesProduceCompleteParameterEnclosures",
                "SurfaceTrimExtendBuilderTests.exactSurfaceTrimHasBuilderCommandAndNativePackageParity",
                "DirectEditSchemaTests.surfaceTrimRejectsRemovedRectangularDomainSchema",
                "DirectEditSchemaTests.surfaceOperationTargetRequiresAnExplicitFaceReference",
                "SurfaceOffsetFeatureTests.rejectsSelectedFaceOwnedByAnotherBody",
                "CADCommandTests.surfaceTrimRequestRoundTripsThroughSharedCommand",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularGeometry,
                .intersectionFailure,
                .classificationFailure,
                .resourceLimitExceeded,
                .topologyFailure,
            ],
            additionalPublicAPIs: ["CADModeling.SurfaceTrimFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SURFACEEXTEND-001",
            operation: "surfaceExtend",
            topology: .sheetBody,
            inputs: [
                "explicitStableSelectedFaceOwnedByReferencedSheetBody",
                "selectedFaceIsOnlyFaceOfSingleShellSheetBody",
                "oneSingleFaceExactTrimmedSheet",
                "planeCylinderConeSphereTorusOrRationalBSplineSurface",
                "oneClosedOuterExactPcurveLoop",
                "zeroOrMoreClosedInnerExactPcurveLoops",
                "finiteTargetUVDomainsStrictlyContainingTheSourceOuterTrim",
                "targetDomainsContainedByCanonicalExactSurface",
            ],
            outputs: [
                "validatedExactExtendedSheetBRep",
                "unchangedCanonicalExactSurface",
                "exactSurfaceLiftBoundaryCurvesAndOrientedPcurves",
                "deterministicFeatureScopedCurveIdentities",
                "preservedTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
                "strictCurrentSchemaNativePersistence",
                "deterministicStableFaceResolutionWithoutImplicitFaceSelection",
            ],
            fixtures: [
                "SurfaceTrimExtendFeatureTests.extendsEveryExactSurfaceRepresentationWithinItsCanonicalDomain",
                "SurfaceTrimExtendFeatureTests.extendsANonrectangularExactTrimWhilePreservingItsInnerHole",
                "SurfaceTrimExtendFeatureTests.rejectsOuterDomainNoOpEvenWhenTheSourceHasAnInnerHole",
                "SurfaceTrimExtendFeatureTests.rejectsSurfaceExtendThatShrinksOrPreservesTheCurrentDomain",
                "SurfaceTrimExtendBuilderTests.exactSurfaceExtendHasBuilderCommandAndNativePackageParity",
                "DirectEditSchemaTests.surfaceExtendRejectsRemovedPhysicalDistanceSchema",
                "CADCommandTests.surfaceExtendRequestRoundTripsThroughSharedCommand",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularGeometry,
                .resourceLimitExceeded,
                .topologyFailure,
            ],
            additionalPublicAPIs: ["CADModeling.SurfaceExtendFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SURFACEMATCH-001",
            operation: "surfaceMatch",
            topology: .sheetBody,
            inputs: [
                "explicitStableSelectedFacesOwnedByReferencedSheetBodies",
                "eachSelectedFaceIsOnlyFaceOfItsSingleShellSheetBody",
                "twoSingleFaceFourEdgeExactRectangularSheets",
                "planeCylinderConeSphereTorusOrRationalBSplineSurfaces",
                "axisAlignedExactPcurveBoundaries",
                "twoContainedUVAnchors",
                "alignedOrOpposedNormals",
                "G0G1OrG2Request",
            ],
            outputs: [
                "validatedExactMatchedSheetBRep",
                "exactRationalBSplineMatchedSurface",
                "exactSurfaceLiftBoundaryCurvesAndOrientedPcurves",
                "measuredPositionNormalAndShapeOperatorResiduals",
                "deterministicFeatureScopedCurveIdentities",
                "mergedTargetFaceLineage",
                "preservedUnrelatedBodiesAndSelections",
                "deterministicStableFaceResolutionWithoutImplicitFaceSelection",
            ],
            fixtures: [
                "ExactRectangularBSplineSurfacePatchTests.preservesPositionNormalAndShapeOperator",
                "SurfaceMatchFeatureTests.matchesEveryExactSurfaceRepresentationWithMeasuredG2",
                "SurfaceMatchFeatureTests.rejectsG2WhenOnlyG1CanBeSatisfied",
                "SurfaceMatchBuilderTests.exactRationalSurfaceMatchHasBuilderCommandAndNativePackageParity",
                "CADCommandTests.surfaceMatchRequestRoundTripsThroughSharedCommand",
                "DirectEditSchemaTests.surfaceOperationTargetRequiresAnExplicitFaceReference",
                "SurfaceOffsetFeatureTests.rejectsSelectedFaceOwnedByAnotherBody",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularGeometry,
                .resourceLimitExceeded,
                .conflictingConstraints,
                .topologyFailure,
            ],
            additionalPublicAPIs: [
                "CADGeometry.ExactRectangularBSplineSurfacePatchBuilder",
                "CADIR.SurfaceContinuityEvaluator",
                "CADModeling.SurfaceMatchFeatureEvaluator",
            ]
        ),
    ]
}
