import CADCore

extension KernelCapabilities {
    static let topologyCapabilities: [KernelCapability] = [
        KernelCapability(
            id: "TOPO-LINEAGE-001",
            operation: "topologyLineage",
            status: .supported,
            topology: .subshapeGraph,
            acceptedInputs: [
                "generatedFeatureOutput",
                "evaluatorOwnedCompleteLineage",
                "exactRelationParentCardinality",
                "mixedSplitMergeParentUse",
                "StableSubshapeReference",
                "edgeAndFaceSubobjectQuery",
                "exactBodyFaceEdgeVertexGeometryWitness",
                "parameterChangeFeatureInsertionAndSuppression",
            ],
            exactOutputs: [
                "SubshapeID",
                "SubshapeIndex",
                "TopologyLineage",
                "uniqueLiveDescendantResolution",
                "uniqueGeometrySignatureFallback",
                "typedSplitAmbiguity",
                "typedGeometryAmbiguity",
                "topologyKindCompatibleResolution",
                "multiGenerationLiveDescendantAmbiguity",
                "typedLineageCycleFailure",
                "oneToOneFeatureOutputCoverage",
                "evaluatingFeatureOutputOwnership",
                "noEngineInferredLineage",
                "canonicalUniqueSortedParentSet",
                "exactCurveSurfacePcurveAndTopologyWitness",
                "sameFeatureGeometryFallback",
                "crossFeatureGeometryMatchRejection",
                "stableParameterChangeAndFeatureInsertionResolution",
                "suppressedSelectionMissingReference",
                "splitAmbiguityAndMergedParentResolution",
            ],
            failureCodes: [.invalidInput, .missingReference, .ambiguousSelection, .topologyFailure],
            tolerance: .standard,
            publicAPIs: [
                "CADCore.SubshapeID",
                "CADCore.TopologyLineage",
                "CADIR.StableSubshapeReference",
                "CADIR.SubshapeGeometrySignature",
                "CADIR.CurveSpanGeometrySignature",
                "CADIR.FaceGeometrySignature",
                "CADIR.BodyGeometrySignature",
                "CADIR.SubshapeIndex",
                "CADModeling.StableSubshapeResolving",
                "CADModeling.StableSubshapeResolver",
                "CADKernel.EvaluatedDocument",
                "CADKernel.EdgeQueryEvaluator",
                "CADKernel.SurfaceQueryEvaluator",
            ],
            testFixtures: [
                "TopologyLineageValidationTests",
                "FeatureTopologyLineageValidatorTests",
                "DocumentEvaluatorIncrementalTests",
                "StableSelectionResolverTests",
                "BooleanEvaluationPlanServiceTests",
                "CADCommandTests",
                "FaceLoopOffsetFeatureTests",
                "EdgeOffsetFeatureTests",
                "SubshapeGeometrySignatureTests",
                "NativeStableSelectionPackageTests",
                "FaceKnifeFeatureTests",
                "TopologyLineageMergeResolutionTests",
            ]
        ),
        KernelCapability(
            id: "TOPO-BREP-001",
            operation: "validatedBRep",
            status: .supported,
            topology: .anyBRep,
            acceptedInputs: [
                "vertex",
                "edge",
                "coedge",
                "loop",
                "face",
                "shell",
                "body",
                "everyValidatedSurfaceAndPcurveRepresentationCombination",
                "analyticCoordinatePcurves",
                "sphericalGreatCirclePcurves",
                "positiveWeightRationalBSpline3DEdgesAndPcurvesOnAnalyticSurfaces",
                "exactSurfaceLiftCurveOnBSplineSurface",
                "trimmedAndReversedExactSurfaceLiftCurvesOnSourceSurface",
                "certifiedImplicitPcurvesWithAnyPerCellGraphFreeCoordinate",
                "certifiedAnalyticImplicitPcurvesOnCylinderConeSphereAndTorus",
                "certifiedAnalyticPairPcurvesOnEveryRegisteredAnalyticPairAndEitherSourceRole",
                "rectangularCoordinatePcurveDomainsOnPlaneCylinderConeSphereAndTorusFaces",
                "certifiedGreenIntegralPcurveLoopsOnPlanarFaces",
                "concaveOrthogonalCoordinatePcurveLoopsWithHolesOnAnalyticSurfaces",
                "arbitraryAffineHarmonicPolylineAndPositiveWeightRationalBSplinePcurveLoopsOnAnalyticSurfaces",
                "sphericalGreatCirclePcurveLoopsOnSpheres",
                "certifiedAnalyticImplicitPcurveLoopsOnAnalyticSurfaces",
                "certifiedAnalyticPairPcurveLoopsOnAnalyticSurfaces",
                "orderedSolidComponentsWithForwardOuterAndFollowingReversedVoidShells",
                "boundedTwoSphereBooleanShells",
                "boundedOffsetSphereConeBooleanShellsWithTwoClosedTransverseComponentsAndExternalConeCap",
                "boundedCoaxialSphereConeBooleanShells",
                "boundedCoaxialTorusCylinderBooleanShellsWithStrictInteriorIntersectionCircles",
                "boundedParallelOffsetTorusCylinderBooleanShellsWithTwoClosedTransverseComponentsAndExternalCylinderCaps",
                "boundedCenteredNonParallelTorusCylinderBooleanShellsWithTwoClosedTransverseComponentsAndExternalCylinderCaps",
                "boundedCoaxialSphereTorusBooleanShellsWithStrictInteriorIntersectionCircles",
                "boundedNonCoaxialSphereTorusBooleanShellsWithTwoClosedTransverseComponents",
                "boundedCoaxialTorusTorusBooleanShellsWithStrictInteriorIntersectionCircles",
                "boundedParallelOffsetTorusTorusBooleanShellsWithFourClosedTransverseComponents",
                "boundedNonParallelTorusTorusBooleanShellsWithTwoClosedTransverseComponents",
                "boundedPlanarCutterRingTorusBooleanShellsWithOneRegularQuarticLoop",
                "boundedCoaxialConeTorusBooleanShellsWithStrictInteriorIntersectionCirclesAndExternalConeCap",
                "boundedNonCoaxialConeTorusBooleanShellsWithTwoClosedTransverseComponentsAndExternalConeCap",
                "boundedCoaxialConeConeBooleanShellsWithOneStrictInteriorIntersectionCircle",
                "boundedTransverseConeConeBooleanShellsWithOneClosedTransverseComponentAndExternalCaps",
                "boundedCoaxialSphereCylinderBooleanShellsWithTwoStrictInteriorIntersectionCirclesAndExternalCylinderCaps",
                "boundedCoaxialConeCylinderBooleanShellsWithStrictInteriorSideAndCapIntersectionCircles",
                "boundedTransverseConeCylinderBooleanShellsWithTwoClosedSideComponentsAndExternalOrHyperbolicallyIntersectingCylinderCaps",
                "closedRectangularClampedMultiSpanPositiveWeightRationalBSplineSurfaceShellsWithExactAxisAlignedPcurves",
                "axisAlignedPlanarRationalBSplineFacesWithCertifiedStraightEdges",
                "closedNonClampedMultiSpanPositiveWeightRationalBSplineSurfaceShellsWithTriangularRationalPcurveDomains",
            ],
            exactOutputs: [
                "manifold",
                "watertight",
                "faceLocalPcurves",
                "exactSurfaceLiftPcurveIdentity",
                "normalizedTrimPreservingSurfaceLiftPcurveRecovery",
                "monotoneGeometricPcurveCorrespondenceIndependentOfParameterization",
                "homogeneousBernsteinCurveOnSurfaceDerivativeBounds",
                "krawczykGraphCellImplicitPcurveAreaBounds",
                "certifiedImplicitFreeUIntegrationByPartsBounds",
                "intervalImplicitFunctionPcurveDerivativeBounds",
                "rationalAnalyticNURBSAzimuthAndMeridianAngleAreaBounds",
                "adaptiveIntervalSphericalGreatCirclePcurveAreaBounds",
                "adaptiveThirdOrderCertifiedAnalyticPairPcurveAreaBounds",
                "outwardRoundedClosedFormAnalyticRectangularSurfaceFluxVolumeBounds",
                "outwardRoundedPcurveGreenIntegralPlanarSurfaceFluxVolumeBounds",
                "outwardRoundedOrthogonalPcurveAnalyticSurfaceFluxVolumeBounds",
                "sixthDerivativeGaussExplicitPcurveAnalyticSurfaceFluxVolumeBounds",
                "outwardRoundedBSplineDerivativeToBernsteinPcurveBounds",
                "derivedKrawczykSubcellAnalyticImplicitSurfaceFluxVolumeBounds",
                "adaptiveThirdOrderCertifiedAnalyticPairSurfaceFluxVolumeBounds",
                "outwardRoundedMultiSpanRationalRevolutionProfileMomentBounds",
                "validatedExactTopology",
                "analyticCylinderVolume",
                "analyticRevolvedThroughHoleVolume",
                "closedFormTwoSphereBooleanVolume",
                "closedFormSphereConeBooleanVolume",
                "adaptiveDiskSectionSphereConeBooleanVolume",
                "closedFormSphereTorusBooleanVolume",
                "adaptiveDiskSectionSphereTorusBooleanVolume",
                "closedFormSphereCylinderBooleanVolume",
                "adaptiveDiskSectionSphereCylinderBooleanVolume",
                "adaptiveAnnulusDiskSectionTorusCylinderBooleanVolume",
                "adaptiveAnnulusSectionTorusTorusBooleanVolume",
                "toleranceBoundedCenteredNonParallelTorusCylinderBooleanVolume",
                "outwardRoundedBernsteinPolynomialSurfaceFluxVolumeBounds",
                "adaptiveSixthDerivativeRationalBezierSurfaceFluxVolumeBounds",
                "outwardRoundedHomogeneousKnotInsertionBounds",
                "outwardRoundedAxisAlignedPlanarStraightEdgeSurfaceFluxBounds",
                "certifiedRationalPcurveKnotCrossingSurfaceFluxVolumeBounds",
                "validatedBRepRetainedCertifiedVolume",
                "bodyScopedCertifiedVolume",
                "positiveMaterialVolumePerOrderedSolidComponent",
                "strictCurrentBRepSchema",
                "totalCertifiedSurfaceFluxWithoutUnsupportedFallback",
            ],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .topologyFailure,
                .nonManifoldResult,
                .resourceLimitExceeded,
                .singularSystem,
                .ambiguousSelection,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADTopology.BRepModel",
                "CADTopology.BRepModel.solidShellComponents",
                "CADTopology.SolidShellComponent",
                "CADTopology.ValidatedBRepModel",
            ],
            testFixtures: [
                "BRepValidationLevelTests",
                "BRepSewerTests",
                "ExactFacePcurveBuilderTests",
                "ExactIGESExchangeTests.roundTripsClockwiseHarmonicPcurveAsExactRationalBSpline",
                "BooleanEvaluationPlanServiceTests",
                "GeneralCylinderBooleanClassificationTests",
                "PrimitiveBooleanIntegrationTests",
                "PrimitiveFaceContainmentTests",
                "PrimitiveSphereBooleanIntegrationTests",
                "PrimitiveSphereConeBooleanIntegrationTests",
                "PrimitiveOffsetSphereConeBooleanIntegrationTests",
                "PrimitiveTorusCylinderBooleanIntegrationTests",
                "PrimitiveOffsetTorusCylinderBooleanIntegrationTests",
                "PrimitiveNonParallelTorusCylinderBooleanIntegrationTests",
                "PrimitiveSphereTorusBooleanIntegrationTests",
                "PrimitiveGeneralSphereTorusBooleanIntegrationTests",
                "PrimitiveTorusBooleanIntegrationTests",
                "PrimitiveOffsetTorusTorusBooleanIntegrationTests",
                "PrimitiveGeneralTorusTorusBooleanIntegrationTests",
                "PrimitivePlaneTorusBooleanIntegrationTests",
                "OffsetDiskSectionVolumeIntegratorTests",
                "PrimitiveConeTorusBooleanIntegrationTests",
                "PrimitiveGeneralConeTorusBooleanIntegrationTests",
                "PrimitiveConeBooleanIntegrationTests",
                "PrimitiveGeneralConeConeBooleanIntegrationTests",
                "PrimitiveSphereCylinderBooleanIntegrationTests",
                "PrimitiveConeCylinderBooleanIntegrationTests",
                "PrimitiveGeneralConeCylinderBooleanIntegrationTests",
                "TrimmedParametricSurfaceVolumeTests.closedCurvedBSplineSolidUsesBoundaryIntegralWithoutMeshFallback",
                "TrimmedParametricSurfaceVolumeTests.nonuniformMultiSpanRationalPlanarFaceReturnsCertifiedBounds",
                "TrimmedParametricSurfaceVolumeTests.exhaustedCoefficientBudgetReturnsTypedResourceDiagnostic",
                "TrimmedParametricSurfaceVolumeTests.exhaustedRationalCellBudgetReturnsTypedResourceDiagnostic",
                "TrimmedParametricSurfaceVolumeTests.multiSpanSaddleFluxUsesCertifiedKnotExtraction",
                "TrimmedParametricSurfaceVolumeTests.exhaustedKnotExtractionBudgetReturnsTypedResourceDiagnostic",
                "TrimmedRationalBRepVolumeTests.multiSpanSaddlePrismCertifiesRationalKnotCrossingThroughPublicVolume",
                "TrimmedRationalBRepVolumeTests.reversedOnlySolidShellIsNotAcceptedAsPositiveMaterial",
                "StrictCurrentTopologySchemaTests",
                "SurfaceFeatureEvaluatorTests.bSplineSurfaceRejectsPcurveDifferentFromExactIsoparametricEdge",
                "CurveSurfaceCorrespondenceValidatorTests",
                "SurfaceParameterCurveAreaIntegratorTests",
                "PrimitiveFeatureTests",
                "BRepSewerTests.sewsOperandSwappedImplicitIntersectionEdges",
                "BRepSewerTests.sewsImplicitIntersectionFaceWithSelectedUAsGraphCoordinate",
                "SurfaceParameterCurveAreaIntegratorTests.implicitGraphOnOtherSurfaceBoundsSelectedPcurveArea",
                "SurfaceParameterCurveAreaIntegratorTests.analyticCylinderImplicitPcurveBoundsCertifiedGeneratorArea",
                "SurfaceParameterCurveAreaIntegratorTests.analyticConeImplicitPcurveBoundsCertifiedGeneratorArea",
                "SurfaceParameterCurveAreaIntegratorTests.analyticSphereImplicitPcurveBoundsCertifiedMeridianArea",
                "SurfaceParameterCurveAreaIntegratorTests.analyticTorusImplicitPcurveBoundsCertifiedMeridianArea",
                "SphericalGreatCirclePcurveAreaIntegratorTests.meridianBoundsContainExactForwardAndReversedArea",
                "SphericalGreatCirclePcurveAreaIntegratorTests.meridianCrossingPoleUsesExactHalfArcContributions",
                "SphericalGreatCirclePcurveAreaIntegratorTests.obliqueArcBoundsContainIndependentHighResolutionIntegral",
                "SphericalGreatCirclePcurveAreaIntegratorTests.obliqueArcCrossingLongitudeSeamIsSplitAnalytically",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.boundedPlaneTorusComponentBoundsPlaneRole",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.boundedPlaneTorusComponentBoundsTorusRoleAcrossSeam",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.trimmedFullBranchBoundsAndReversalContainIndependentIntegral",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.operandSwappedTrimPreservesBothRoleEnclosures",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.exhaustedProofBudgetReturnsTypedResourceDiagnostic",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.negativeInnerSupportNodalPlaneRoleHasCertifiedAreaBounds",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.negativeInnerSupportNodalTorusRoleHasCertifiedAreaBounds",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.positiveInnerSupportNodalPlaneRoleHasCertifiedAreaBounds",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.positiveInnerSupportNodalTorusRoleHasCertifiedAreaBounds",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.sphereCylinderBothRolesHaveCertifiedAreaAndFluxBounds",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.sphereCylinderGenericLongitudeSeamHasCertifiedAreaAndFluxBounds",
                "SurfaceParameterCurveChartLiftTests",
                "CertifiedGeneralConeTorusSpatialDifferentialBoundsTests.regularTorusPcurvesOwnTheirCertifiedContinuousChartLift",
                "CertifiedIntervalSummationTests",
                "RationalRevolutionProfileMomentBuilderTests.multiSpanProfileRetainsEveryExactMomentSpan",
                "RationalRevolutionProfileMomentBuilderTests.rationalMultiSpanMomentMatchesProfilePointwise",
                "CurvedRevolveFeatureTests.multiSpanRationalBSplineBoundaryIsSplitWithoutLosingExactness",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.sphericalRectangleBoundsContainClosedFormVolume",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.toroidalRectangleBoundsContainClosedFormVolume",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.cylindricalRectangleBoundsContainClosedFormSideContribution",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.planarHarmonicLoopBoundsContainGreenTheoremVolumeForEitherTraversal",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.planarInnerLoopNegatesCertifiedArea",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.planarDegenerateLoopFailsTypedInsteadOfReturningZeroVolume",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.concaveCoordinateLoopsMatchRectangularDecompositionOnCurvedSurfaces",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.torusCoordinateLoopCrossingAzimuthSeamMatchesUnwrappedRectangle",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.reversedCoordinateLoopPreservesCanonicalOuterContribution",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.affineDiagonalTrimReturnsCertifiedCylinderContribution",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.harmonicTrimReturnsCertifiedCylinderContribution",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.rationalBSplineTrimReturnsCertifiedCylinderContribution",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.nonClampedRationalBSplineTrimReturnsCertifiedCylinderContribution",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.sphericalGreatCircleMeridianMatchesRectangularSphereContribution",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.sphericalGreatCircleEquatorMatchesRectangularSphereContribution",
                "TrimmedAnalyticSurfaceVolumeEvaluatorTests.certifiedAnalyticImplicitTrimMatchesCylinderRectangle",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.torusRoleFluxBoundsContainIndependentBoundaryIntegral",
                "BRepSewerTests.sewsImplicitIntersectionFaceWhenOtherSurfaceOwnsGraphCoordinate",
                "ExactFacePcurveBuilderTests.reusesExactSurfaceLiftPcurveForTrimmedEdge",
                "ExactFacePcurveBuilderTests.reversesExactSurfaceLiftPcurveForReversedCoedge",
                "TrimmedParametricSurfaceVolumeTests.triangularRuledTrimReturnsCertifiedSaddleContribution",
                "ThickenFeatureTests.thickensRegularCurvedBSplineSheetWithExactOffsetCapsAndRuledWalls",
            ]
        ),
        KernelCapability(
            id: "TOPO-SEWING-001",
            operation: "exactBRepSewing",
            status: .supported,
            topology: .anyBRep,
            acceptedInputs: [
                "orderedFacePatches",
                "explicitStableShellComponentOwnership",
                "planeCylinderConeSphereTorusSurfaces",
                "lineCircleTrims",
                "faceLocalPcurves",
                "analyticCoordinatePcurves",
                "sphericalGreatCirclePcurves",
                "equivalentLinearCurveSpans",
                "structurallyIdenticalExactCurveSpans",
                "analyticConicAndExactRationalBSplineEquivalentSpans",
                "knotInsertedAffineReparameterizedBSplineSpans",
                "degreeElevatedRationalBSplineSpans",
                "certifiedNonAffineRationalBSplineSpans",
                "nestedRepartitionedOrOperandSwappedImplicitGraphCurveSpans",
                "differentlyParameterizedImplicitGraphCurveSpansWithSharedCertifiedComponentWitness",
            ],
            exactOutputs: [
                "deterministicCoedgeBRep",
                "manifoldValidation",
                "SubshapeID",
                "TopologyLineage",
                "sampleCollisionSafeCurveSpanIdentity",
                "periodicTurnCountPreservation",
                "homogeneousControlNetCoincidenceBound",
                "homogeneousBezierDegreeElevationCoincidenceBound",
                "adaptiveNonAffineRationalCoincidenceBound",
                "krawczykGraphCellContainmentCoincidenceProof",
                "operandOrderInvariantImplicitCurveIdentity",
                "freeCoordinateInvariantImplicitCurveIdentity",
                "canonicalImplicitPcurveCertificateTransfer",
                "validatedBRepResultType",
                "explicitSolidComponentAndVoidShellOwnership",
            ],
            failureCodes: [
                .invalidInput,
                .topologyFailure,
                .nonManifoldResult,
                .resourceLimitExceeded,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADModeling.BRepSewing",
                "CADModeling.BRepSewingRequest",
                "CADModeling.BRepSewingBodyTopology",
                "CADModeling.BRepSewingSolidComponent",
                "CADModeling.BRepSewingStableKey",
                "CADModeling.BRepSewingResult",
                "CADKernel.BRepFacePatchExtracting",
                "CADKernel.DefaultBRepSewer",
            ],
            testFixtures: [
                "BRepSewerTests.preservesReversedShellOrientationAcrossExtractionAndResewing",
                "BRepSewerTests.explicitSewingTopologyPreservesVoidOwnerAcrossStableSorting",
                "ClosedIntersectionSewingLoopBuilderTests",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCarriesRevolvedToolForTargetContainedUnion",
                "ExactFacePcurveBuilderTests",
                "CurveSpanCoincidenceMatcherTests",
                "BRepSewerTests.sewsEquivalentAnalyticAndRationalSharedEdges",
                "BRepSewerTests.sewsOperandSwappedImplicitIntersectionEdges",
                "CurveSpanCoincidenceMatcherTests.acceptsImplicitComponentRecertifiedWithDifferentFreeCoordinate",
                "BRepSewerTests.sewsImplicitIntersectionEdgesRecertifiedWithDifferentFreeCoordinate",
            ]
        ),
        KernelCapability(
            id: "TOPO-REPAIR-001",
            operation: "explicitBRepRepair",
            status: .supported,
            topology: .anyBRep,
            acceptedInputs: [
                "callerSelectedValidationScopes",
                "duplicateBodyShellFaceLoopOwnershipReferences",
                "uniquelyReorderableAndOrientableLoopCoedgeCycle",
                "topologyAndGeometryUnreachableFromBodies",
                "actionRequiredValidationScopes",
            ],
            exactOutputs: [
                "independentMultiDiagnosticValidationReport",
                "unmodifiedInputModel",
                "explicitlyRepairedBRepModel",
                "beforeAfterValidationReports",
                "deterministicRepairChangeLedger",
                "typedUnrepairableDiagnostic",
                "requestActionOrderIndependent",
                "strictCurrentRepairSchema",
            ],
            failureCodes: [.invalidInput, .missingReference, .topologyFailure],
            tolerance: .standard,
            publicAPIs: [
                "CADTopology.BRepTopologyValidating",
                "CADTopology.DefaultBRepTopologyValidator",
                "CADTopology.BRepValidationRequest",
                "CADTopology.BRepRepairing",
                "CADTopology.DefaultBRepRepairer",
                "CADTopology.BRepRepairRequest",
                "CADTopology.BRepRepairResult",
            ],
            testFixtures: [
                "BRepScopedValidationAndRepairTests",
                "StrictCurrentTopologySchemaTests",
            ]
        ),
    ]
}
