import CADCore

extension KernelCapabilities {
    static let exchangeCapabilities: [KernelCapability] = [
        KernelCapability(
            id: "EXCHANGE-STEP-001",
            operation: "STEP",
            status: .partial,
            topology: .sheetOrSolidBody,
            acceptedInputs: [
                "validatedLineBoundedPlanarBRep",
                "finiteTrimmedOpenNonPeriodicRationalBSplineEdgesInEitherSense",
                "finiteSubperiodCircleAndEllipseEdgesAcrossPeriodicSeamsInEitherSense",
                "piecewiseLinearPolylinePcurves",
                "analyticLineArcEllipseHyperbolaAndParabolaEdges",
                "projectedPlaneConeOpenConics",
                "sphericalGreatCircleEdges",
                "certifiedPlaneTorusIntersectionEdges",
                "certifiedBSplinePairAndAnalyticBSplineIntersectionEdges",
                "exactSurfaceLiftEdgesWithRationalBSplinePcurves",
                "singleForwardOuterShellWithReversedVoidShells",
                "SILengthUnitsAndConversionBasedInchFootUnits",
            ],
            exactOutputs: [
                "AP242AdvancedFaces",
                "SurfaceCurvesAndPcurves",
                "EdgeCurveSameSenseRoundTrip",
                "PeriodicConicTrimDirectionAndPcurveRoundTrip",
                "PolylinePcurveDegreeOneBSplineRoundTrip",
                "EdgeLoops",
                "OpenOrClosedShells",
                "BrepWithVoidsAndOrientedClosedShells",
                "ExactLengthUnitAndPhysicalUncertaintyRoundTrip",
                "ManifoldSolidOrSheetModel",
                "DeterministicExactImport",
                "NoMeshFallback",
                "CanonicalIntersectionTruthReconstructionFromExactSurfaceProvenance",
                "PcurveMasterSurfaceLiftReconstruction",
            ],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: ["CADExchange.STEPExchange"],
            testFixtures: [
                "ExactSTEPExchangeTests",
                "ExactSTEPExchangeTests.roundTripsExactPlanarTopologyInConversionBasedLengthUnits",
                "ExactSTEPExchangeTests.roundTripsReversedCompleteDomainRationalBSplineEdges",
                "ExactSTEPExchangeTests.roundTripsPartialDomainRationalBSplineEdgesInBothDirections",
                "ExactSTEPExchangeTests.roundTripsPolylinePcurvesExactlyThroughSTEPAndIGES",
                "ExactSTEPExchangeTests.roundTripsSeamCrossingCircleAndEllipseEdges",
                "ExactSTEPExchangeTests.roundTripsSolidVoidShellTopologyAndVolume",
                "ExactSTEPExchangeTests.roundTripsConeHyperbolaThroughExactSurfaceAssociation",
                "ExactSTEPExchangeTests.roundTripsSphericalGreatCircleThroughExactSurfaceAssociation",
                "ExactSTEPExchangeTests.roundTripsPlaneTorusIntersectionWithExactTwoSurfaceProvenance",
                "ExactSTEPExchangeTests.roundTripsCertifiedImplicitIntersectionWithExactSurfaceProvenance",
                "ExactSTEPExchangeTests.roundTripsCertifiedAnalyticBSplineIntersectionWithExactSurfaceProvenance",
                "ExactSTEPExchangeTests.roundTripsSurfaceLiftAsPcurveMasterWithoutChangingCanonicalTruth",
                "ExchangeProcessingBudgetTests",
                "CADExchangeTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-IGES-001",
            operation: "IGES",
            status: .partial,
            topology: .sheetOrSolidBody,
            acceptedInputs: [
                "validatedSheetBodyWithOneOrMoreOpenShells",
                "finiteTrimmedOpenNonPeriodicRationalBSplineEdgesInEitherSense",
                "finiteSubperiodCircleAndEllipseEdgesAcrossPeriodicSeamsInEitherSense",
                "finiteSubperiodArbitraryAxisAnalyticArcEdgesInEitherSense",
                "harmonicEllipticPcurvesInEitherOrientation",
                "piecewiseLinearPolylinePcurves",
                "analyticLineArcEllipseHyperbolaAndParabolaEdges",
                "projectedPlaneConeOpenConics",
                "sphericalGreatCircleEdges",
                "certifiedPlaneTorusIntersectionEdges",
                "certifiedBSplinePairAndAnalyticBSplineIntersectionEdges",
                "exactSurfaceLiftEdgesWithRationalBSplinePcurves",
                "singleForwardOuterShellWithReversedVoidShells",
                "IGESLengthUnits",
            ],
            exactOutputs: [
                "Type110ModelAndParameterCurves",
                "Type100AnalyticArcIdentityAndDirectionRoundTrip",
                "Type126CurveParameterDirectionRoundTrip",
                "PeriodicConicTrimDirectionAndPcurveRoundTrip",
                "ClockwiseHarmonicPcurveType126ExactRoundTrip",
                "PolylinePcurveDegreeOneBSplineRoundTrip",
                "Type190PlaneSurfaces",
                "Type502To514ManifoldTopology",
                "Type402Form7MultiShellSheetBodyGroups",
                "Type186OuterAndVoidShellUses",
                "DeterministicExactImport",
                "NoMeshFallback",
                "CanonicalIntersectionTruthReconstructionFromNestedType142SurfaceProvenance",
                "Type142SurfaceLiftReconstruction",
            ],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: ["CADExchange.IGESExchange"],
            testFixtures: [
                "ExactIGESExchangeTests",
                "ExactIGESExchangeTests.roundTripsArbitraryAxisAnalyticArcEdgesInBothDirections",
                "ExactIGESExchangeTests.roundTripsReversedCompleteDomainRationalBSplineEdges",
                "ExactIGESExchangeTests.roundTripsPartialDomainRationalBSplineEdgesInBothDirections",
                "ExactIGESExchangeTests.roundTripsSeamCrossingCircleAndEllipseEdges",
                "ExactIGESExchangeTests.roundTripsClockwiseHarmonicPcurveAsExactRationalBSpline",
                "ExactSTEPExchangeTests.roundTripsPolylinePcurvesExactlyThroughSTEPAndIGES",
                "ExactIGESExchangeTests.roundTripsMultiShellSheetBodyAsForm7Group",
                "ExactIGESExchangeTests.roundTripsSolidVoidShellTopologyAndVolume",
                "ExactIGESExchangeTests.roundTripsConeHyperbolaWithoutApproximatedPcurve",
                "ExactIGESExchangeTests.roundTripsSphericalGreatCircleWithoutApproximatedPcurve",
                "ExactIGESExchangeTests.roundTripsPlaneTorusIntersectionThroughNestedCurveOnSurfaceEntities",
                "ExactIGESExchangeTests.roundTripsCertifiedImplicitIntersectionThroughNestedCurveOnSurfaceEntities",
                "ExactIGESExchangeTests.roundTripsCertifiedAnalyticBSplineIntersectionThroughNestedCurveOnSurfaceEntities",
                "ExactIGESExchangeTests.roundTripsSurfaceLiftThroughExactCurveOnSurfaceEntity",
                "ExchangeProcessingBudgetTests",
                "CADExchangeTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-USD-001",
            operation: "USDMeshExchange",
            status: .partial,
            topology: .polygonMesh,
            acceptedInputs: [
                "USDA",
                "USDC",
                "USDZ",
                "StandaloneDirectMeshLayer",
                "USDZPackageLocalComposition",
                "ExplicitTimeCodeSnapshot",
                "DerivedTriangleMesh",
            ],
            exactOutputs: [
                "ZeroCopyRetainedInputSlice",
                "DerivedMeshPositionsAndTopology",
                "UnitsAndUpAxis",
                "StandardNormalsInterpolationWithDerivedMeshExpansion",
                "TextureCoordinatesAndDisplayColor",
                "TypedUSDAndCompositionDiagnostics",
                "StandaloneSdfLayerSemanticPreflight",
                "TypedSdfLayerAuthoring",
                "PureSwiftUSDAUSDCUSDZCodecs",
                "USDCUSDZVertexPrimvarRoundTrip",
                "USDZComposedSublayerReferenceAndPayloadMeshImport",
                "ExplicitTimeSampledSceneSnapshot",
                "TypedUSDAUnsupportedVertexPrimvarDiagnostic",
                "BoundedImportResources",
            ],
            failureCodes: [.invalidInput, .unsupportedCapability, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.USDExchange",
                "CADUSD.USDSceneImporting",
                "CADUSD.SceneImporter",
                "OpenUSD.USDSceneReader",
                "OpenUSD.USDAReader.readSdfLayer",
                "OpenUSD.USDAReader.read",
                "OpenUSDC.USDCReader.readSdfLayer",
                "OpenUSDC.USDCReader.read",
                "OpenUSDZ.USDZReader.read",
            ],
            testFixtures: [
                "CADUSDImportTests",
                "USDExchangePureSwiftImportTests",
                "USDExchangePureSwiftImportTests.pureSwiftUSDAImportEvaluatesRequestedTimeSample",
                "USDExchangePureSwiftImportTests.standaloneUSDAImportRejectsUnresolvedCompositionArc",
                "USDExchangePureSwiftImportTests.standaloneUSDCImportRejectsUnresolvedCompositionArc",
                "USDExchangePureSwiftImportTests.standaloneUSDAImportRejectsVariantOpinionBeforeMaterialization",
                "USDExchangePureSwiftImportTests.pureSwiftUSDZImportComposesPackagedSublayers",
                "USDExchangeTopologyTests.importPreservesFaceVaryingNormalsThroughMeshExpansion",
                "USDExchangeTopologyTests",
                "USDExporterCodecTests",
                "USDExchangeResourceLimitTests",
            ]
        ),
    ]
}
