import CADCore

extension KernelCapabilities {
    static let exchangeCapabilities: [KernelCapability] = [
        KernelCapability(
            id: "API-NATIVEPERSISTENCE-001",
            operation: "nativePersistence",
            status: .supported,
            topology: .document,
            acceptedInputs: [
                "strictCurrentSchemaValidatedCADDocument",
                "borrowedOrMappedSwiftCADNativePackage",
            ],
            exactOutputs: [
                "deterministicSourceOnlyZipPackage",
                "canonicalSortedDynamicDictionaries",
                "strictManifestAndDocumentSchemaValidation",
                "documentFeatureParameterAndSelectionIdentityRoundTrip",
                "atomicURLPersistence",
            ],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .resourceLimitExceeded,
                .topologyFailure,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.NativePackageStore",
                "SwiftCAD.CADPipeline.writePackage",
                "SwiftCAD.CADPipeline.loadDocument",
            ],
            testFixtures: [
                "CADExchangeTests",
                "NativeOperationSchemaTests",
                "NativeStableSelectionPackageTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-STEP-001",
            operation: "STEP",
            status: .partial,
            topology: .sheetOrSolidBody,
            acceptedInputs: [
                "validatedLineBoundedPlanarBRep",
                "finiteTrimmedOpenNonPeriodicRationalBSplineEdgesInEitherSense",
                "finiteSubperiodCircleAndEllipseEdgesAcrossPeriodicSeamsInEitherSense",
                "piecewiseLinearPolylinePcurves",
                "analyticLineArcEllipseHyperbolaAndParabolaEdges",
                "finiteRegularAffineImageCurvesWithExactRationalMaterialization",
                "projectedPlaneConeOpenConics",
                "sphericalGreatCircleEdges",
                "certifiedPlaneTorusIntersectionEdges",
                "certifiedBSplinePairAndAnalyticBSplineIntersectionEdges",
                "exactSurfaceLiftEdgesWithRationalBSplinePcurves",
                "generalSameParameterOffsetSurfacesWithFiniteRationalBSplineBasis",
                "oneOrMoreOrderedSolidComponentsWithOwnedReversedVoidShells",
                "SILengthUnitsAndConversionBasedInchFootUnits",
            ],
            exactOutputs: [
                "AP242AdvancedFaces",
                "SurfaceCurvesAndPcurves",
                "EdgeCurveSameSenseRoundTrip",
                "PeriodicConicTrimDirectionAndPcurveRoundTrip",
                "PolylinePcurveDegreeOneBSplineRoundTrip",
                "EdgeLoops",
                "OpenOrClosedShells",
                "BrepWithVoidsAndOrientedClosedShells",
                "ExactLengthUnitAndPhysicalUncertaintyRoundTrip",
                "ManifoldSolidOrSheetModel",
                "oneStandardSolidRepresentationItemPerMaterialComponent",
                "DeterministicExactImport",
                "NoMeshFallback",
                "CanonicalIntersectionTruthReconstructionFromExactSurfaceProvenance",
                "PcurveMasterSurfaceLiftReconstruction",
                "StandardOffsetSurfaceRoundTrip",
                "StandardLineOrRationalBSplineAffineImageMaterialization",
            ],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: ["CADExchange.STEPExchange"],
            testFixtures: [
                "ExactSTEPExchangeTests",
                "ExactSTEPExchangeTests.roundTripsExactPlanarTopologyInConversionBasedLengthUnits",
                "ExactSTEPExchangeTests.roundTripsReversedCompleteDomainRationalBSplineEdges",
                "ExactSTEPExchangeTests.roundTripsPartialDomainRationalBSplineEdgesInBothDirections",
                "ExactSTEPExchangeTests.roundTripsPolylinePcurvesExactlyThroughSTEPAndIGES",
                "ExactSTEPExchangeTests.roundTripsSeamCrossingCircleAndEllipseEdges",
                "ExactSTEPExchangeTests.roundTripsSolidVoidShellTopologyAndVolume",
                "ExactSTEPExchangeTests.exportsEachDisconnectedSolidComponentWithoutLosingVoidOwnership",
                "ExactSTEPExchangeTests.roundTripsConeHyperbolaThroughExactSurfaceAssociation",
                "ExactSTEPExchangeTests.roundTripsSphericalGreatCircleThroughExactSurfaceAssociation",
                "ExactSTEPExchangeTests.roundTripsPlaneTorusIntersectionWithExactTwoSurfaceProvenance",
                "ExactSTEPExchangeTests.roundTripsCertifiedImplicitIntersectionWithExactSurfaceProvenance",
                "ExactSTEPExchangeTests.roundTripsCertifiedAnalyticBSplineIntersectionWithExactSurfaceProvenance",
                "ExactSTEPExchangeTests.roundTripsSurfaceLiftAsPcurveMasterWithoutChangingCanonicalTruth",
                "ExactSTEPExchangeTests.roundTripsGeneralOffsetSurfaceWithSameParameterChart",
                "ExchangeProcessingBudgetTests",
                "ExactAffineImageExchangeTests",
                "ExactAffineImageExchangeTests.stepMaterializesAffineImagesAsExactStandardCurves",
                "CADExchangeTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-IGES-001",
            operation: "IGES",
            status: .partial,
            topology: .sheetOrSolidBody,
            acceptedInputs: [
                "validatedSheetBodyWithOneOrMoreOpenShells",
                "finiteTrimmedOpenNonPeriodicRationalBSplineEdgesInEitherSense",
                "finiteSubperiodCircleAndEllipseEdgesAcrossPeriodicSeamsInEitherSense",
                "finiteSubperiodArbitraryAxisAnalyticArcEdgesInEitherSense",
                "harmonicEllipticPcurvesInEitherOrientation",
                "piecewiseLinearPolylinePcurves",
                "analyticLineArcEllipseHyperbolaAndParabolaEdges",
                "finiteRegularAffineImageCurvesWithExactRationalMaterialization",
                "projectedPlaneConeOpenConics",
                "sphericalGreatCircleEdges",
                "certifiedPlaneTorusIntersectionEdges",
                "certifiedBSplinePairAndAnalyticBSplineIntersectionEdges",
                "exactSurfaceLiftEdgesWithRationalBSplinePcurves",
                "generalSameParameterOffsetSurfacesWithFiniteRationalBSplineBasis",
                "oneOrMoreOrderedSolidComponentsWithOwnedReversedVoidShells",
                "IGESLengthUnits",
            ],
            exactOutputs: [
                "Type110ModelAndParameterCurves",
                "Type100AnalyticArcIdentityAndDirectionRoundTrip",
                "Type126CurveParameterDirectionRoundTrip",
                "PeriodicConicTrimDirectionAndPcurveRoundTrip",
                "ClockwiseHarmonicPcurveType126ExactRoundTrip",
                "PolylinePcurveDegreeOneBSplineRoundTrip",
                "Type190PlaneSurfaces",
                "Type502To514ManifoldTopology",
                "Type402Form7MultiShellSheetBodyGroups",
                "Type186OuterAndVoidShellUses",
                "oneType186EntityPerMaterialComponent",
                "DeterministicExactImport",
                "NoMeshFallback",
                "CanonicalIntersectionTruthReconstructionFromNestedType142SurfaceProvenance",
                "Type142SurfaceLiftReconstruction",
                "Type140OffsetSurfaceRoundTrip",
                "StandardLineOrType126AffineImageMaterialization",
            ],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: ["CADExchange.IGESExchange"],
            testFixtures: [
                "ExactIGESExchangeTests",
                "ExactIGESExchangeTests.roundTripsArbitraryAxisAnalyticArcEdgesInBothDirections",
                "ExactIGESExchangeTests.roundTripsReversedCompleteDomainRationalBSplineEdges",
                "ExactIGESExchangeTests.roundTripsPartialDomainRationalBSplineEdgesInBothDirections",
                "ExactIGESExchangeTests.roundTripsSeamCrossingCircleAndEllipseEdges",
                "ExactIGESExchangeTests.roundTripsClockwiseHarmonicPcurveAsExactRationalBSpline",
                "ExactSTEPExchangeTests.roundTripsPolylinePcurvesExactlyThroughSTEPAndIGES",
                "ExactIGESExchangeTests.roundTripsMultiShellSheetBodyAsForm7Group",
                "ExactIGESExchangeTests.roundTripsSolidVoidShellTopologyAndVolume",
                "ExactIGESExchangeTests.exportsEachDisconnectedSolidComponentWithoutLosingVoidOwnership",
                "ExactIGESExchangeTests.roundTripsConeHyperbolaWithoutApproximatedPcurve",
                "ExactIGESExchangeTests.roundTripsSphericalGreatCircleWithoutApproximatedPcurve",
                "ExactIGESExchangeTests.roundTripsPlaneTorusIntersectionThroughNestedCurveOnSurfaceEntities",
                "ExactIGESExchangeTests.roundTripsCertifiedImplicitIntersectionThroughNestedCurveOnSurfaceEntities",
                "ExactIGESExchangeTests.roundTripsCertifiedAnalyticBSplineIntersectionThroughNestedCurveOnSurfaceEntities",
                "ExactIGESExchangeTests.roundTripsSurfaceLiftThroughExactCurveOnSurfaceEntity",
                "ExactIGESExchangeTests.roundTripsGeneralOffsetSurfaceWithType140Indicator",
                "ExchangeProcessingBudgetTests",
                "ExactAffineImageExchangeTests",
                "ExactAffineImageExchangeTests.igesMaterializesAffineImagesAsExactStandardCurves",
                "CADExchangeTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-USD-001",
            operation: "USDMeshExchange",
            status: .partial,
            topology: .polygonMesh,
            acceptedInputs: [
                "USDA",
                "USDC",
                "USDZ",
                "StandaloneDirectMeshLayer",
                "USDZPackageLocalComposition",
                "ExplicitTimeCodeSnapshot",
                "DerivedTriangleMesh",
            ],
            exactOutputs: [
                "ZeroCopyRetainedInputSlice",
                "DerivedMeshPositionsAndTopology",
                "UnitsAndUpAxis",
                "StandardNormalsInterpolationWithDerivedMeshExpansion",
                "TextureCoordinatesAndDisplayColor",
                "TypedUSDAndCompositionDiagnostics",
                "StandaloneSdfLayerSemanticPreflight",
                "TypedSdfLayerAuthoring",
                "PureSwiftUSDAUSDCUSDZCodecs",
                "USDCUSDZVertexPrimvarRoundTrip",
                "USDZComposedSublayerReferenceAndPayloadMeshImport",
                "ExplicitTimeSampledSceneSnapshot",
                "TypedUSDAUnsupportedVertexPrimvarDiagnostic",
                "BoundedImportResources",
            ],
            failureCodes: [.invalidInput, .unsupportedCapability, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.USDExchange",
                "CADUSD.USDSceneImporting",
                "CADUSD.SceneImporter",
                "OpenUSD.USDSceneReader",
                "OpenUSD.USDAReader.readSdfLayer",
                "OpenUSD.USDAReader.read",
                "OpenUSDC.USDCReader.readSdfLayer",
                "OpenUSDC.USDCReader.read",
                "OpenUSDZ.USDZReader.read",
            ],
            testFixtures: [
                "CADUSDImportTests",
                "USDExchangePureSwiftImportTests",
                "USDExchangePureSwiftImportTests.pureSwiftUSDAImportEvaluatesRequestedTimeSample",
                "USDExchangePureSwiftImportTests.standaloneUSDAImportRejectsUnresolvedCompositionArc",
                "USDExchangePureSwiftImportTests.standaloneUSDCImportRejectsUnresolvedCompositionArc",
                "USDExchangePureSwiftImportTests.standaloneUSDAImportRejectsVariantOpinionBeforeMaterialization",
                "USDExchangePureSwiftImportTests.pureSwiftUSDZImportComposesPackagedSublayers",
                "USDExchangeTopologyTests.importPreservesFaceVaryingNormalsThroughMeshExpansion",
                "USDExchangeTopologyTests",
                "USDExporterCodecTests",
                "USDExchangeResourceLimitTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-STL-001",
            operation: "STLMeshExchange",
            status: .supported,
            topology: .polygonMesh,
            acceptedInputs: [
                "validatedDerivedTriangleMeshes",
                "binarySTLWithFiniteTriangleRecords",
                "optionalSwiftCADLengthUnitMarker",
            ],
            exactOutputs: [
                "deterministicBinarySTL",
                "validatedTriangleMeshImport",
                "finiteNormalsAndCoordinates",
                "boundedImportResources",
            ],
            failureCodes: [.invalidInput, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.STLExporter",
                "CADExchange.OfficialFormatExchange",
            ],
            testFixtures: ["CADExchangeTests"]
        ),
        KernelCapability(
            id: "EXCHANGE-3MF-001",
            operation: "ThreeMFMeshExchange",
            status: .supported,
            topology: .polygonMesh,
            acceptedInputs: [
                "validatedDerivedTriangleMeshes",
                "core3MFMeshPackageWithStoredOrDeflatedDirectBuildItems",
                "finiteSupportedLengthUnit",
            ],
            exactOutputs: [
                "deterministicStoredZip3MFPackage",
                "storedAndDeflatedZIPImportWithCRCAndDescriptorValidation",
                "validatedTriangleMeshImport",
                "unitRoundTrip",
                "strictPackageRelationshipAndXMLStructureValidation",
                "boundedImportAndExportResources",
            ],
            failureCodes: [.invalidInput, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.ThreeMFExchange",
                "CADExchange.OfficialFormatExchange",
            ],
            testFixtures: ["CADExchangeTests"]
        ),
        KernelCapability(
            id: "EXCHANGE-OBJ-001",
            operation: "OBJMeshExchange",
            status: .supported,
            topology: .polygonMesh,
            acceptedInputs: [
                "validatedDerivedTriangleMeshes",
                "finiteOBJVertexTextureNormalAndSimplePlanarPolygonFaceRecordsWithPerFaceConsistentAttributes",
                "explicitFallbackLengthUnit",
            ],
            exactOutputs: [
                "deterministicOBJMesh",
                "validatedTriangulatedMeshImport",
                "negativeAndPositiveIndexResolution",
                "faceVaryingAttributePreservationAndLayoutPartitioning",
                "boundedImportResources",
            ],
            failureCodes: [.invalidInput, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.OBJExchange",
                "CADExchange.OfficialFormatExchange",
            ],
            testFixtures: ["CADExchangeTests"]
        ),
        KernelCapability(
            id: "EXCHANGE-DXF-001",
            operation: "DXFMeshExchange",
            status: .supported,
            topology: .polygonMesh,
            acceptedInputs: [
                "validatedDerivedTriangleMeshes",
                "ASCIIHeaderlessOrAC1027DXFWithTriangularOrQuadrilateral3DFACEEntities",
                "headerOrExplicitFallbackLengthUnit",
            ],
            exactOutputs: [
                "deterministicASCII3DFACEExchange",
                "validatedTriangleAndQuadrilateralMeshImport",
                "strictSectionAndGroupCodeValidation",
                "boundedImportResources",
            ],
            failureCodes: [.invalidInput, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.DXFExchange",
                "CADExchange.OfficialFormatExchange",
            ],
            testFixtures: ["CADExchangeTests"]
        ),
        KernelCapability(
            id: "EXCHANGE-SVG-001",
            operation: "SVGMeshExchange",
            status: .supported,
            topology: .polygonMesh,
            acceptedInputs: [
                "validatedDerivedTriangleMeshesProjectedToXY",
                "SVG11SimplePlanarPolygonElementsWithoutTransformsOrExternalContent",
                "explicitFallbackLengthUnit",
            ],
            exactOutputs: [
                "deterministicSVGPolygonExchange",
                "validatedConcavePlanarPolygonTriangulation",
                "strictNamespaceElementAndAttributeValidation",
                "boundedImportResources",
            ],
            failureCodes: [.invalidInput, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.SVGExchange",
                "CADExchange.OfficialFormatExchange",
            ],
            testFixtures: ["CADExchangeTests"]
        ),
        KernelCapability(
            id: "EXCHANGE-GLB-001",
            operation: "GLBMeshExport",
            status: .supported,
            topology: .polygonMesh,
            acceptedInputs: ["validatedDerivedTriangleMeshes"],
            exactOutputs: [
                "deterministicGLB2Mesh",
                "finitePositionAndNormalAccessors",
                "unsignedIndexComponentSelection",
                "fourByteAlignedJSONAndBinaryChunks",
            ],
            failureCodes: [.invalidInput, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.GLBExporter",
                "CADExchange.OfficialFormatExchange",
            ],
            testFixtures: ["CADExchangeTests"]
        ),
        KernelCapability(
            id: "EXCHANGE-PDF-001",
            operation: "PDFMeshExport",
            status: .supported,
            topology: .polygonMesh,
            acceptedInputs: [
                "validatedDerivedTriangleMeshes",
                "finiteDocumentTitle",
            ],
            exactOutputs: [
                "deterministicSinglePagePDF",
                "projectedVectorTrianglePaths",
                "validCrossReferenceTable",
            ],
            failureCodes: [.invalidInput, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.PDFExporter",
                "CADExchange.OfficialFormatExchange",
            ],
            testFixtures: ["CADExchangeTests"]
        ),
    ]
}
