import CADCore

extension KernelCapabilities {
    static let geometryCapabilities: [KernelCapability] = [
        KernelCapability(
            id: "GEO-CURVE-001",
            operation: "analyticCurve",
            status: .supported,
            topology: .notApplicable,
            acceptedInputs: ["line", "circle", "arc", "ellipse"],
            exactOutputs: [
                "position", "firstDerivative", "secondDerivative", "tangent", "curvature",
                "inverseParameterProjection", "verifiedResidual",
            ],
            failureCodes: [.invalidInput, .intersectionFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.Curve3D",
                "CADGeometry.CurveParameterProjection",
                "CADGeometry.CurveParameterProjectionOptions",
            ],
            testFixtures: [
                "GeometryKernelTests",
                "AnalyticGeometryIntegrationTests",
                "CurveParameterProjectionTests",
            ]
        ),
        KernelCapability(
            id: "GEO-CURVE-002",
            operation: "rationalBSplineCurve",
            status: .supported,
            topology: .notApplicable,
            acceptedInputs: [
                "boundedNonPeriodicControlPoints", "positiveWeights",
                "nondecreasingClampedOrNonClampedKnots", "degree",
                "finiteOpenOrClosedPiecewiseLinearSurfaceParameterCurves",
            ],
            exactOutputs: [
                "position", "firstDerivative", "secondDerivative", "curvature",
                "inverseParameterProjection", "verifiedResidual",
                "exactKnotInsertion", "exactParameterTrim",
                "normalizedPcurveDifferential",
                "directHomogeneousDerivativeToBernsteinSpanExtraction",
                "outwardRoundedBezierControlHullProjectionSearch",
                "leafLocalProjectionRefinementWithGlobalRootNormalization",
                "typedMultipleParameterAmbiguity",
                "strictCurrentSchemaDecoding",
                "exactArcLengthPolylineTrimIncludingPeriodicSeamCrossings",
            ],
            failureCodes: [
                .invalidInput, .intersectionFailure, .ambiguousSelection,
                .singularSystem, .resourceLimitExceeded,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.BSplineCurve3D",
                "CADGeometry.CurveParameterProjection",
                "CADGeometry.CurveParameterProjectionOptions",
                "CADGeometry.SurfaceParameterCurve",
            ],
            testFixtures: [
                "GeometryKernelTests",
                "CurveParameterProjectionTests",
                "BSplineCurveTrimmingTests",
                "SurfaceParameterCurveDifferentialTests",
                "SurfaceParameterCurveSubcurveTests",
            ]
        ),
        KernelCapability(
            id: "GEO-SURFACE-001",
            operation: "analyticSurface",
            status: .supported,
            topology: .notApplicable,
            acceptedInputs: ["plane", "cylinder", "cone", "sphere", "torus"],
            exactOutputs: [
                "position", "tangentU", "tangentV", "secondDerivatives", "normal",
                "curvature", "principalDirections", "UVNFrame",
                "typedSingularParameterFailure",
            ],
            failureCodes: [.invalidInput, .singularSystem],
            tolerance: .standard,
            publicAPIs: ["CADGeometry.Surface3D"],
            testFixtures: ["GeometryKernelTests", "AnalyticGeometryIntegrationTests"]
        ),
        KernelCapability(
            id: "GEO-SURFACE-002",
            operation: "rationalBSplineSurface",
            status: .supported,
            topology: .notApplicable,
            acceptedInputs: [
                "boundedNonPeriodicControlNet", "positiveWeights",
                "nondecreasingClampedOrNonClampedKnotsU",
                "nondecreasingClampedOrNonClampedKnotsV", "degreeU", "degreeV",
            ],
            exactOutputs: [
                "position", "tangentU", "tangentV", "secondDerivatives", "normal",
                "curvature", "principalDirections", "UVNFrame",
                "inverseParameterProjection", "verifiedResidual",
                "outwardRoundedBezierControlHullProjectionSearch",
                "leafLocalProjectionRefinementWithGlobalRootNormalization",
                "typedMultipleParameterAmbiguity",
                "exactBoundedParameterTrim",
                "typedSingularParameterFailure",
                "directHomogeneousDerivativeToBernsteinSpanExtraction",
                "nonClampedNaturalDomainSupport",
                "scaleInvariantMetricConditioning",
                "exactRationalIsoparametricCurves",
                "finiteDifferentialRangeValidation",
            ],
            failureCodes: [
                .invalidInput, .intersectionFailure, .ambiguousSelection,
                .singularSystem, .resourceLimitExceeded, .topologyFailure,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.BSplineSurface3D",
                "CADGeometry.SurfaceParameterProjection",
                "CADGeometry.SurfaceParameterProjectionOptions",
            ],
            testFixtures: [
                "GeometryKernelTests",
                "BSplineSurfaceParameterProjectionTests",
                "BSplineSurfaceTrimmingTests",
            ]
        ),
        KernelCapability(
            id: "GEO-INTERSECTION-001",
            operation: "curveSurfaceIntersection",
            status: .partial,
            topology: .notApplicable,
            acceptedInputs: [
                "lineAnalyticSurface",
                "circleArcEllipseAgainstPlaneSphereCylinderConeOrTorus",
                "boundedLineCircleArcEllipseAgainstRationalBSplineSurface",
                "boundedRationalBSplineCurveSurface",
                "boundedSurfaceLiftAgainstAnalyticSurfaceIncludingVerifiedTangency",
                "certifiedIntersectionCurveAgainstEitherSourceSurface",
                "certifiedIntersectionCurveAgainstToleranceEquivalentSourceSurfaceRepresentation",
                "certifiedIntersectionCurveAgainstSpatiallySeparatedExactSphereOrTorus",
                "certifiedConeBasedIntersectionCurveAgainstExactPlane",
                "certifiedParallelTorusTorusIntersectionCurveAgainstExactPlane",
                "certifiedSphereConeIntersectionCurveAgainstExactSphere",
                "certifiedSphereConeIntersectionCurveAgainstExactCoaxialCylinder",
                "certifiedSphereConeIntersectionCurveAgainstExactCylinder",
                "certifiedConeCylinderIntersectionCurveAgainstExactCoaxialSphere",
                "certifiedConeCylinderIntersectionCurveAgainstExactSphere",
                "certifiedConeCylinderIntersectionCurveAgainstNonDegenerateExactCone",
                "certifiedConeConeIntersectionCurveAgainstExactCylinderWithNonDegenerateConeCylinderConeReduction",
                "certifiedSphereConeIntersectionCurveAgainstNonDegenerateExactCone",
                "certifiedConeConeIntersectionCurveAgainstNonDegenerateExactSphere",
                "certifiedConeConeIntersectionCurveAgainstNonDegenerateExactCone",
                "certifiedConeCylinderIntersectionCurveAgainstExactParallelAxisCylinder",
                "certifiedConeCylinderIntersectionCurveAgainstExactFullBranchSkewCylinder",
                "certifiedConeCylinderIntersectionCurveAgainstExactBoundedSkewCylinder",
                "certifiedReducedSectionWithAlgebraicallyIdentifiedComponent",
                "certifiedBoundedPlaneConeSurfaceLiftAgainstExactAnalyticPlane",
                "certifiedRootFreeSphereCylinderSurfaceLiftAgainstExactAnalyticPlane",
                "certifiedRootFreeSphereConeSurfaceLiftAgainstExactAnalyticPlane",
                "certifiedRootFreeConeCylinderSurfaceLiftAgainstExactAnalyticPlane",
                "explicitFiniteParameterRanges",
            ],
            exactOutputs: [
                "closedFormAlgebraicPoint", "adaptivelyRefinedPoint",
                "curveParameter", "surfaceParameters", "intersectionKind",
                "verifiedResidual", "rationalBSplineAnalyticRepeatedRootPreservation",
                "periodicSurfaceRangeResolution", "typedSingularGeometry",
                "rankDeficientBSplineTangencyRefinement",
                "boundedSubdivisionCellAndCandidateBudgets",
                "typedUnresolvedControlHullCandidateFailure",
                "outwardRoundedHomogeneousBezierDifferenceSubdivision",
                "intervalKrawczykTransverseRootExistenceAndUniqueness",
                "exactAnalyticCurveToRationalBSplineLocusReduction",
                "shiftedPeriodicSourceParameterRecovery",
                "uncertifiedNonRationalPartialResultRejection",
                "verifiedStationarySurfaceLiftTangentContact",
                "typedContinuousCoincidenceForEveryCertifiedIntersectionCurveKind",
                "typedNonDiscreteSourceCoincidenceAcrossCanonicalAnalyticRepresentations",
                "outwardRoundedBoundingBoxCertifiedEmptyIntersection",
                "algebraicallyReducedCertifiedCurvePlaneIntersectionsWithRecoveredSourceParameter",
                "degreeEightParallelTorusPlaneEliminationWithVerifiedSourceParameter",
                "sphereSectionReducedCertifiedCurveSphereIntersectionsWithRecoveredSourceParameter",
                "coneSectionReducedCertifiedCurveCylinderIntersectionsWithRecoveredSourceParameter",
                "coneCylinderSectionReducedCertifiedSphereConeCurveCylinderIntersectionsWithCanonicalSourceParameterRecovery",
                "cylinderSectionReducedCertifiedCurveSphereIntersectionsWithRecoveredSourceParameterAndPoleSafeTargetNormal",
                "degreeEightConeCylinderSphereResultantWithVerifiedSourceParameter",
                "degreeSixteenConeCylinderConeResultantWithVerifiedSourceParameterAndTangency",
                "coneCylinderSectionReducedCertifiedConeConeCurveCylinderIntersections",
                "degreeSixteenConeHostedQuadricResultantWithVerifiedSourceParameterAndTangency",
                "parallelCylinderGeneratorReducedCertifiedCurveCylinderIntersectionsWithRecoveredSourceParameter",
                "fullBranchCylinderPairReducedCertifiedCurveCylinderIntersectionsWithStructuralDifferentialBounds",
                "boundedCylinderPairReducedCertifiedCurveCylinderIntersectionsWithEndpointRegularizedIntervalDifferentialBounds",
                "bezoutCertifiedReducedSectionComponentCoincidenceAndSharedNodePreservation",
                "boundedConicSpatialDifferentialCertifiedCurvePlaneIntersections",
                "rootFreeSphereCylinderSpatialDifferentialCertifiedCurvePlaneIntersections",
                "rootFreeSphereConeSpatialDifferentialCertifiedCurvePlaneIntersections",
                "rootFreeConeCylinderSpatialDifferentialCertifiedCurvePlaneIntersections",
            ],
            failureCodes: [
                .invalidInput, .intersectionFailure, .nonDiscreteIntersection,
                .singularGeometry, .resourceLimitExceeded,
                .unsupportedCapability,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.CurveSurfaceIntersecting",
                "CADGeometry.DefaultCurveSurfaceIntersector",
                "CADGeometry.CurveSurfaceIntersection",
            ],
            testFixtures: [
                "CurveSurfaceIntersectionTests",
                "CurveSurfaceIntersectionTests.generalSurfaceLiftTangencyReturnsVerifiedTangentIntersection",
                "BSplineCurveAnalyticSurfaceIntersectionTests",
                "BSplineCurveSurfaceTangencyTests",
                "RationalBezierCurveSurfaceDifferencePatchTests",
                "CertifiedIntersectionCurveSurfaceIntersectionTests",
                "AnalyticSurfaceEquivalenceResolverTests",
                "CertifiedConeCylinderFullBranchSkewCylinderTests",
                "CertifiedCylinderCylinderSpatialDifferentialBoundsTests",
                "CertifiedBoundedPlaneConeSpatialDifferentialBoundsTests",
                "CertifiedSphereCylinderSpatialDifferentialBoundsTests",
                "CertifiedSphereConeSpatialDifferentialBoundsTests",
                "CertifiedConeCylinderSpatialDifferentialBoundsTests",
                "ConeCylinderSpherePolynomialBuilderTests",
                "SurfaceSurfaceIntersectionTests.coaxialSphereCylinderGreatCircleRetainsPoleSafeSpherePcurve",
                "GeometryKernelTests",
            ]
        ),
        KernelCapability(
            id: "GEO-INTERSECTION-002",
            operation: "surfaceSurfaceIntersection",
            status: .partial,
            topology: .notApplicable,
            acceptedInputs: [
                "planePlane",
                "planeSphere",
                "planeCylinder",
                "planeConeEllipticOrApexGenerator",
                "boundedPlaneConeHyperbolicOrParabolicSectionWithCompleteFaceBoundaryContacts",
                "planeTorusAxialMeridionalSupportTangentOrRegularQuarticSection",
                "planeTorusInnerSupportNodalSectionWithCompleteMixedBranchGraph",
                "planeClampedBSplineBoundaryIsocurve",
                "planeBoundedRationalBSplineCertifiedImplicitSection",
                "planeBoundedRationalBSplineSecondOrderAffineTangency",
                "transverseCylinderConeSphereOrTorusAgainstBoundedRationalBSpline",
                "transverseBoundedRationalBSplinePair",
                "isolatedSecondOrderDefiniteBoundedRationalBSplineTangency",
                "secondOrderRankOneBoundedRationalBSplineContactCurve",
                "secondOrderIndefiniteBoundedRationalBSplineBranchingIntersection",
                "isolatedQuarticEvenPowerBoundedRationalBSplineTangency",
                "sphereSphere",
                "parallelCylinderCylinder",
                "intersectingEqualRadiusCylinderCylinder",
                "generalNonParallelCylinderCylinder",
                "generalNonCoaxialSphereCylinderIncludingRegularSphereParameterPoleCrossings",
                "generalNonCoaxialSphereConeIncludingRegularSphereParameterPoleCrossingsAwayFromConeApex",
                "coaxialSphereCylinder",
                "coaxialConeCylinder",
                "generalConeCylinderAwayFromConeApexAndRulingParallelGenerators",
                "coaxialSphereCone",
                "coaxialTorusCylinder",
                "parallelOffsetTorusCylinderIncludingInternalDoubleTangency",
                "generalNonParallelTorusCylinderWithCertifiedConstantSimpleGeneratorRoots",
                "coaxialSphereTorus",
                "generalNonCoaxialSphereTorusIncludingRegularSphereParameterPoleCrossings",
                "coaxialTorusTorus",
                "parallelOffsetTorusTorusWithFourFullDomainSimpleTransverseBranches",
                "equalMajorRadiusCoplanarParallelOffsetTorusTorusAtMinorRadiusSumWithCompleteNodalGraph",
                "congruentCenteredNonParallelTorusTorusWithExactBisectorPlaneFactorization",
                "generalNonParallelTorusTorusWithCertifiedConstantSimpleMeridianRoots",
                "coaxialConeTorus",
                "generalNonCoaxialConeTorusWithCertifiedConstantSimpleRulingRootsAwayFromApex",
                "coaxialConeCone",
                "generalConeConeWithTwoFullDomainSimpleTransverseBranchesAwayFromApexAndRulingAsymptote",
            ],
            exactOutputs: [
                "line", "circle", "ellipse", "tangentPoint", "coincidence",
                "boundedRationalBSplineCurve", "mixedContactCurve",
                "pseudoArclengthMarchedBSplineCurve", "dualSurfacePcurves",
                "residualCertifiedCompositeCubicIntersectionCurve",
                "outwardRoundedAdaptiveTaylorResidualCertificate",
                "outwardRoundedPolynomialBezierResidualCertificate",
                "outwardRoundedFourParameterHomogeneousBezierDifferenceSearch",
                "intervalCoefficientConvexHullZeroExclusion",
                "intervalJacobianRankThreeCertificate",
                "certifiedMinorGaugeSeedRefinement",
                "intervalKrawczykMidpointGaugeRootExistenceAndUniqueness",
                "intervalKrawczykParameterizedRegularGraphExistenceAndUniqueness",
                "intervalKrawczykRegularCellExclusion",
                "intervalKrawczykBoundaryFaceRootIsolation",
                "adaptiveBoundaryFaceBezierSubdivision",
                "derivativeWidthGuidedBoundarySubdivision",
                "regularCellBoundaryParityCertificate",
                "earlyCertifiedRegularGraphSubdivisionTermination",
                "threeProbeRegularGraphComponentCoverage",
                "fourParameterBoundaryRootComponentCoverage",
                "boundarySubdivisionBudgetAccounting",
                "uncertifiedRegularCellPartialResultRejection",
                "numericalRootAttemptBudgetAccounting",
                "distinctSeedBudgetAccounting",
                "fourParameterCellComponentCoverage",
                "boundedSurfaceSubdivisionCellBudget",
                "exactAnalyticNURBSReduction",
                "certifiedImplicitPlaneBSplineIntersection",
                "certifiedAnalyticBSplineQuadraticTangencyTruth",
                "exactAffinePlaneMappingQuadraticTangencyCertificate",
                "exactAffinePlaneMappingQuarticPowerSumTangencyCertificate",
                "exactBernsteinToPowerCoefficientIdentity",
                "subdivisionIndependentHigherOrderTangencyPoint",
                "decodeRevalidatedAnalyticTangencyPcurve",
                "seamUnwrappedAnalyticPcurve",
                "deterministicPeriodicPatchBoundaryAvoidance",
                "toleranceBoundedIntersectionComponentConsolidation",
                "normalDerivativeRefinedTangencyPoint",
                "relativeCurvatureHessianContactClassification",
                "gaugeCorrectedContactCurveContinuation",
                "residualCertifiedTangentCurveWithDualPcurves",
                "hessianConeBranchContinuation",
                "residualCertifiedMixedCurvesWithDualPcurves",
                "surfaceDifferentialConsistentIntersectionSpline",
                "parameterDomainBoundedHermiteControls",
                "directVerifiedIntersectionSampleAnchors",
                "analyticGeneratorIntervalClassification", "adaptiveCubicBSplineCurve",
                "analyticRadialDistanceIntervalClassification",
                "sphericalPoleIntersectionGraphDecomposition",
                "oneSidedSphericalPoleParameterLimits",
                "exactParameterDrivenAdaptiveSplineCache",
                "analyticSphereConeQuadraticIntervalClassification",
                "sphereConePoleIntersectionGraphDecomposition",
                "oneSidedSphereConePoleParameterLimits",
                "analyticSphereTorusTubeAngleClassification",
                "sphereTorusPoleIntersectionGraphDecomposition",
                "oneSidedSphereTorusPoleParameterLimits",
                "analyticConeCylinderGeneratorQuadraticClassification",
                "analyticConeConeRulingQuadraticClassification",
                "exactConeConeDiscriminantExtrema",
                "tangentHalfAngleQuarticRootIsolation",
                "derivativePartitionedCertifiedSimpleRootIsolation",
                "intervalClassifiedPlaneTorusQuarticSections",
                "exactPlaneTorusAlgebraicCurveWithAnalyticDerivatives",
                "decodeRevalidatedQuarticComponentCompleteness",
                "innerSupportPlaneTorusNodalBranchDecomposition",
                "oneSidedDoubleRootPlaneTorusDifferentials",
                "decodeRevalidatedPlaneTorusNodalCompleteness",
                "principalFrameBoundedHyperbolaClassification",
                "principalFrameBoundedParabolaClassification",
                "openAdaptiveCubicBSplineCurve",
                "analyticTorusCylinderRadialBandIntervalClassification",
                "internalDoubleTangencyBranchDecomposition",
                "regularOpenTangencyIntervalBranches",
                "decodeRevalidatedTangencyMultiplicity",
                "intervalCertifiedTorusCylinderQuarticGeneratorRoots",
                "intervalCertifiedTorusTorusCircleBranches",
                "parallelTorusTorusNodalSelfLoopDecomposition",
                "oneSidedDoubleRootParallelTorusTorusDifferentials",
                "decodeRevalidatedParallelTorusTorusNodalCompleteness",
                "exactCongruentTorusTorusBisectorPlaneFactorization",
                "completeSecondOrderTorusTorusBranchContactGraph",
                "decodeRevalidatedTorusTorusBranchCompleteness",
                "intervalCertifiedTorusTorusQuarticMeridianRoots",
                "intervalCertifiedConeTorusQuarticRulingRoots",
                "operandOrderStableCurveGeometry",
                "canonicalOpenAndClosedCurveOrientation",
                "surfaceParameters", "verifiedResidual",
            ],
            failureCodes: [
                .invalidInput, .intersectionFailure, .nonDiscreteIntersection,
                .unsupportedCapability, .resourceLimitExceeded, .singularSystem,
                .singularGeometry,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.SurfaceSurfaceIntersecting",
                "CADGeometry.DefaultSurfaceSurfaceIntersector",
                "CADGeometry.BoundedSurfaceSurfaceIntersecting",
                "CADGeometry.DefaultBoundedSurfaceSurfaceIntersector",
                "CADGeometry.SurfaceSurfaceIntersection",
                "CADGeometry.CertifiedAnalyticBSplineTangencyIntersectionCurve",
                "CADGeometry.CertifiedParallelTorusTorusIntersectionCurve",
                "CADGeometry.CertifiedCongruentTorusTorusIntersectionCurve",
            ],
            testFixtures: [
                "SurfaceSurfaceIntersectionTests",
                "SurfaceSurfaceIntersectionTests.planeTorusInternalTangencyProducesCompleteMixedGraph",
                "SurfaceSurfaceIntersectionTests.obliquePlaneTorusInternalTangencyRetainsNodalBranches",
                "SurfaceSurfaceIntersectionTests.nearbyPlaneTorusSectionsDoNotClaimNodalTangency",
                "CertifiedAnalyticPairPcurveAreaIntegratorTests.innerSupportNodalBranchesReturnTypedUnsupportedAreaDiagnostic",
                "ParallelOffsetTorusTorusSurfaceIntersectionTests.generatorTangencyProducesCompleteNodalGraph",
                "ParallelOffsetTorusTorusSurfaceIntersectionTests.nodalGraphIsOperandOrderAndRotationInvariant",
                "ParallelOffsetTorusTorusSurfaceIntersectionTests.nodalCertificateRoundTripsAndRejectsTampering",
                "ParallelOffsetTorusTorusSurfaceIntersectionTests.nearbyOffsetsDoNotClaimNodalTopology",
                "CertifiedSimplePolynomialRootSolverTests",
                "BoundedBSplineSurfaceIntersectionTests",
                "BoundedBSplineSurfaceIntersectionTests.higherOrderTangencyProducesCompleteIsolatedPointIndependentOfSubdivisionBudget",
                "BoundedBSplineSurfaceIntersectionTests.higherOrderTangencyIsRotationAndTranslationInvariant",
                "BoundedBSplineSurfaceIntersectionTests.offCenterAnisotropicQuarticTangencyProducesUniquePoint",
                "BoundedBSplineSurfaceIntersectionTests.boundaryQuarticTangencyProducesUniquePoint",
                "BoundedBSplineSurfaceIntersectionTests.quarticTangencyCompletenessRequiresExactEligibility",
                "RationalBezierSurfaceSurfaceDifferencePatchTests",
                "AnalyticBSplineSurfaceIntersectionTests",
                "GeneralCylinderCylinderSurfaceIntersectionTests",
                "GeneralSphereCylinderSurfaceIntersectionTests",
                "GeneralSphereConeSurfaceIntersectionTests",
                "GeneralSphereTorusSurfaceIntersectionTests",
                "GeneralConeCylinderSurfaceIntersectionTests",
                "GeneralConeConeSurfaceIntersectionTests",
                "BoundedPlaneConeSurfaceIntersectionTests",
                "ParallelOffsetTorusCylinderSurfaceIntersectionTests",
                "ParallelOffsetTorusTorusSurfaceIntersectionTests",
                "GeneralTorusTorusSurfaceIntersectionTests",
                "GeneralTorusTorusSurfaceIntersectionTests.congruentCenteredOrthogonalToriProduceCompleteMixedGraph",
                "GeneralTorusTorusSurfaceIntersectionTests.tiltedCongruentCenteredToriUseExactBisectorFactorization",
                "GeneralTorusCylinderSurfaceIntersectionTests",
                "GeneralConeTorusSurfaceIntersectionTests",
                "GeneralCylinderBooleanIntersectionGraphTests",
                "GeneralCylinderBooleanClassificationTests",
                "IntersectingEqualRadiusCylinderSurfaceIntersectionTests",
                "PlaneBSplineBoundarySurfaceIntersectionTests",
                "RevolvedSurfaceIntersectionTests",
            ]
        ),
        KernelCapability(
            id: "GEO-PREDICATE-001",
            operation: "adaptivePlanarPredicates",
            status: .supported,
            topology: .notApplicable,
            acceptedInputs: [
                "finitePoint2D",
                "finiteSegmentPair",
                "finiteSimplePolygon",
                "explicitModelingTolerance",
            ],
            exactOutputs: [
                "expansionResolvedOrientation",
                "expansionResolvedPolygonOrientation",
                "certifiedSignedPolygonArea",
                "toleranceAwareCollinearity",
                "insideBoundaryOutsideClassification",
                "segmentIntersectionOrTouch",
                "typedIndeterminateClassification",
            ],
            failureCodes: [.invalidInput, .classificationFailure],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.PlanarPredicateEvaluating",
                "CADGeometry.AdaptivePlanarPredicateEvaluator",
                "CADGeometry.PlanarPointClassification",
                "CADGeometry.RobustPredicates",
            ],
            testFixtures: [
                "AdaptivePlanarPredicateEvaluatorTests",
                "CADKernelTests.profileExtractionRejectsNestedClosedLoops",
                "CADKernelTests.profileExtractionRejectsAdjacentOverlappingLoopSegments",
                "CADKernelTests.profileExtractionRejectsIntersectingClosedLoops",
                "CADKernelTests.profileExtractionUsesLocalAreaForFarOriginLoops",
                "CADKernelTests.standaloneBooleanCanReusePreviousCellUnionResultAsTarget",
                "BooleanOpenFaceArrangementTests",
                "ClosedIntersectionExteriorMaterializerTests.nestedClosedPcurvesProduceDeterministicContainmentParent",
                "FaceKnifeFeatureTests",
                "PrimitiveFaceContainmentTests",
                "ProfileRegionAnalyzerRobustnessTests",
                "StrictlyConvexPlanarLoopTests",
            ]
        ),
    ]
}
