import CADCore

extension KernelCapabilities {
    static let modelingFoundationCapabilities: [KernelCapability] = [
        KernelCapability(
            id: "MODEL-SKETCH-001",
            operation: "sketch",
            status: .partial,
            topology: .sketch,
            acceptedInputs: [
                "pointLineCircleArcAndCubicBezierChainSplineEntities",
                "coincidentHorizontalVerticalParallelPerpendicularEqualConcentricFixedConstraints",
                "explicitBranchLineCircularAndCircularCircularTangencyConstraints",
                "alignedOrOpposedSplineLineAndSplineEndpointTangencyConstraints",
                "alignedSmoothSplineControlPointAndEndpointContinuityConstraints",
                "distanceAngleRadiusDiameterDimensions",
                "finiteNondegenerateLineAndArcSourceGeometry",
                "dimensionTargetsWithinToleranceAwareDomains",
                "oneCircleProfileOrIndependentNonNestedClosedLineArcSplineLoops",
            ],
            exactOutputs: [
                "forwardModeJacobian",
                "levenbergMarquardtSolution",
                "typedConstraintStatus",
                "persistedTangencySolutionBranch",
                "persistedSplineTangentOrientationBranch",
                "nonModuloFullTurnArcSpanResidual",
                "positiveRadiusSolverInvariant",
                "candidateEntityInvariantPreservation",
                "preiterationTypedInputRejection",
                "validatedExactProfileBoundaries",
                "validatedExactLineCircleArcAndRationalBSplineCurves",
            ],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .classificationFailure,
                .underConstrained,
                .overConstrained,
                .conflictingConstraints,
                .singularSystem,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADIR.CADCommand.appendFeature",
                "CADKernel.SketchConstraintSolving",
                "CADKernel.LevenbergMarquardtSketchConstraintSolver",
                "CADKernel.SketchConstraintSolveResult",
            ],
            testFixtures: [
                "CADIRTests",
                "CADKernelTests",
                "SketchConstraintSolverTests",
                "SketchTangencyConstraintTests",
                "SketchSplineTangencyConstraintTests",
                "SketchSplineConstraintSolverTests",
                "SketchSplineProfileExtractionTests",
                "NativeOperationSchemaTests.roundTripsTypedSplineTangencyBranches",
            ]
        ),
        feature(
            id: "MODEL-PRIMITIVE-001",
            operation: "primitive",
            topology: .solidBody,
            inputs: [
                "placedBox",
                "placedCylinder",
                "placedCone",
                "placedSphere",
                "placedRingTorus",
                "positiveLengthExpressions",
            ],
            outputs: [
                "validatedExactBRep",
                "analyticPlaneCylinderConeSphereTorusFaces",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
                "exactAnalyticVolume",
            ],
            fixtures: ["PrimitiveFeatureTests", "PrimitiveCommandParityTests"],
            status: .supported,
            failureCodes: [.invalidInput, .missingReference, .topologyFailure],
            additionalPublicAPIs: ["CADModeling.PrimitiveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-EXTRUDE-001",
            operation: "extrude",
            topology: .solidBody,
            inputs: [
                "planarClosedLineProfile",
                "planarClosedCircularArcProfile",
                "planarClosedRationalBSplineProfile",
                "positiveLengthExpression",
                "normalSymmetricOrNonTangentialVectorDirection",
            ],
            outputs: [
                "validatedExactBRep",
                "analyticPlanarAndCylindricalFaces",
                "rationalBSplineRuledSurfaces",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
                "certifiedExactVolume",
            ],
            fixtures: [
                "CADKernelTests.rectangleExtrudeCreatesClosedBoxBRepAndDeterministicMesh",
                "CADKernelTests.circleProfileExtrudeCreatesExactCylindricalBRepAndDeterministicMesh",
                "CADKernelTests.closedSplineProfileExtrudeCreatesExactRuledBRep",
                "CADKernelTests.obliqueVectorExtrudeKeepsCapFacesParallelToSketchPlane",
                "ExactSplineExtrudeFeatureTests",
                "ExactSplineExtrudeCommandParityTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .topologyFailure,
                .nonManifoldResult,
                .resourceLimitExceeded,
            ],
            additionalPublicAPIs: ["CADModeling.PlanarExtrudeFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-REVOLVE-001",
            operation: "revolve",
            topology: .solidBody,
            inputs: [
                "planarClosedLineProfile",
                "planarClosedCircularArcProfile",
                "planarClosedRationalBSplineProfile",
                "coplanarAxis",
                "partialOrFullAngleUpToOneTurn",
                "profileBoundaryInClosedRadialHalfSpace",
                "radialAxialConicalSegments",
            ],
            outputs: [
                "validatedExactBRep",
                "analyticPlaneCylinderConeFaces",
                "rationalBSplineSurfacesOfRevolution",
                "exactAffineBilinearBSplineCaps",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
                "certifiedExactVolume",
            ],
            fixtures: [
                "CADKernelTests.revolveBuildsValidatedConicalFrustum",
                "CurvedRevolveFeatureTests",
                "SketchSplineProfileExtractionTests",
                "CurvedRevolveCommandParityTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .classificationFailure,
                .singularGeometry,
                .topologyFailure,
                .nonManifoldResult,
                .resourceLimitExceeded,
            ],
            additionalPublicAPIs: ["CADModeling.PlanarRevolveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SWEEP-001",
            operation: "sweep",
            topology: .sheetOrSolidBody,
            inputs: [
                "oneClosedPlanarLineCircularArcOrExactRationalBSplineProfileForSolid",
                "oneBoundedPlanarExactCurveSectionForSheet",
                "oneConnectedOpenExactLineCircularEllipseOrRationalBSplinePath",
                "identityOrStraightPathLinearScaleSectionTransform",
                "zeroGuidesOrOneStraightPointGuideWithVerifiedSectionBoundaryContactAndPositiveSimilarityTransform",
                "straightNormalOrNonTangentialParallelPath",
                "curvedParallelPathWithCertifiedMonotoneProfileNormalAdvance",
                "circularPathNormalSolidReducibleToExactRevolve",
                "optionalExactPathPrefixDistanceFraction",
            ],
            outputs: [
                "validatedExactSolidOrSheetBRep",
                "exactAnalyticOrTensorProductRationalBSplineFaces",
                "exactStraightPointGuideSimilaritySectionLaw",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
                "derivedMeshOnly",
            ],
            fixtures: [
                "ExactTranslationalSweepFeatureTests",
                "ExactLinearScaleSweepFeatureTests",
                "CADKernelTests.curvedParallelPathSweepCreatesExactTranslationalBRep",
                "CADKernelTests.circularPathNormalSweepProducesExactRevolvedBRep",
                "CADKernelTests.pointGuidedStraightPathSweepProducesExactLinearSectionBRep",
                "CADKernelTests.pointGuidedStraightPathSweepProducesExactRotatingSimilarityBRep",
                "SweepEvaluationPlanServiceTests",
                "UnsupportedGeneralPathNormalSweepIntegrationTests",
                "ExactTranslationalSweepCommandParityTests",
                "ExactLinearScaleSweepCommandParityTests",
                "ExactPointGuideSweepCommandParityTests",
                "ExactCircularPathNormalSweepCommandParityTests",
            ],
            status: .partial,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .sweepSimplifyUnavailable,
                .sweepProfilePlaneDegenerate,
                .sweepMixedNormalAdvance,
                .sweepMonotonicityCertificateUnavailable,
                .sweepBooleanRequiresSolid,
                .sweepInvalidGuideConstraintCount,
                .sweepRoundCornerUnavailable,
                .sweepPathNormalUnavailable,
                .sweepScaleCollapse,
                .sweepScalePathUnavailable,
                .sweepTwistUnavailable,
                .sweepGuideContactUnavailable,
                .sweepGuideTransformCollapse,
                .sweepGuideConstraintUnavailable,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: [
                "CADModeling.PlanarSweepFeatureEvaluator",
                "CADKernel.SweepEvaluationPlanService",
            ]
        ),
        feature(
            id: "MODEL-LOFT-001",
            operation: "loft",
            topology: .sheetOrSolidBody,
            inputs: [
                "twoOrMoreClosedExactLineArcOrRationalBSplineProfileSections",
                "oneOuterAndAnyFiniteNumberOfNonintersectingHoleBoundariesPerSection",
                "optionalOpenRationalGuideCurvesWithOneOrderedExactBoundaryContactPerSection",
                "ruledOrSmoothSectionInterpolation",
                "openSolidOrSheetSectionChainOrClosedSheetSectionLoop",
            ],
            outputs: [
                "validatedExactSolidOrSheetBRep",
                "minimalDegreeRuledPolynomialTransfiniteOrRationalCoonsSideSurfaces",
                "exactGuideAndProfileBoundaryPartition",
                "singleMaterialShellWithHoleWallsOrOneSheetShellPerBoundaryLoop",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
            ],
            fixtures: [
                "LoftFeatureTests",
                "LoftFeatureTests.loftGuideContactInsideExactBoundarySegmentCreatesPartitionVertex",
                "LoftFeatureTests.loftGuideResolvesExactInteriorContactOnEveryIntermediateSection",
                "LoftFeatureTests.loftMultipleInteriorGuideContactsShareExactSectionIndexes",
                "LoftFeatureTests.loftPreservesRectangularHoleAsOneWatertightSolid",
                "LoftFeatureTests.loftPreservesCircularHoleAsExactRationalBoundary",
                "LoftFeatureTests.loftHoleAwareSheetKeepsEachBoundaryAsAnOpenShell",
                "LoftFeatureTests.loftSmoothSurfaceModePreservesHoleWallsAndVolume",
                "LoftFeatureTests.loftGuideCanConstrainAnInteriorHoleBoundary",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .singularGeometry,
                .topologyFailure,
                .nonManifoldResult,
                .resourceLimitExceeded,
            ],
            additionalPublicAPIs: ["CADModeling.LoftFeatureEvaluator"]
        ),
    ]
}
