import CADCore

public enum KernelCapabilities {
    public static let current = KernelCapabilityCatalog(capabilities: [
        KernelCapability(
            id: "GEO-CURVE-001",
            operation: "analyticCurve",
            status: .supported,
            acceptedInputs: ["line", "circle", "arc", "ellipse"],
            exactOutputs: [
                "position", "firstDerivative", "secondDerivative", "tangent", "curvature",
                "inverseParameterProjection", "verifiedResidual",
            ],
            failureCodes: [.invalidInput, .intersectionFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.Curve3D",
                "CADGeometry.CurveParameterProjection",
                "CADGeometry.CurveParameterProjectionOptions",
            ],
            testFixtures: ["GeometryKernelTests", "CurveParameterProjectionTests"]
        ),
        KernelCapability(
            id: "GEO-CURVE-002",
            operation: "rationalBSplineCurve",
            status: .supported,
            acceptedInputs: ["controlPoints", "weights", "knots", "degree"],
            exactOutputs: [
                "position", "firstDerivative", "secondDerivative", "curvature",
                "inverseParameterProjection", "verifiedResidual",
                "exactKnotInsertion", "exactParameterTrim",
                "normalizedPcurveDifferential",
            ],
            failureCodes: [.invalidInput, .intersectionFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.BSplineCurve3D",
                "CADGeometry.RationalBSplineCurve3D",
                "CADGeometry.CurveParameterProjection",
                "CADGeometry.CurveParameterProjectionOptions",
                "CADGeometry.SurfaceParameterCurve",
            ],
            testFixtures: [
                "GeometryKernelTests",
                "CurveParameterProjectionTests",
                "BSplineCurveTrimmingTests",
                "SurfaceParameterCurveDifferentialTests",
            ]
        ),
        KernelCapability(
            id: "GEO-SURFACE-001",
            operation: "analyticSurface",
            status: .supported,
            acceptedInputs: ["plane", "cylinder", "cone", "sphere", "torus"],
            exactOutputs: [
                "position", "tangentU", "tangentV", "secondDerivatives", "normal",
                "curvature", "principalDirections", "UVNFrame",
            ],
            failureCodes: [.invalidInput],
            tolerance: .standard,
            publicAPIs: ["CADGeometry.Surface3D"],
            testFixtures: ["GeometryKernelTests"]
        ),
        KernelCapability(
            id: "GEO-SURFACE-002",
            operation: "rationalBSplineSurface",
            status: .partial,
            acceptedInputs: ["controlNet", "weights", "knotsU", "knotsV", "degreeU", "degreeV"],
            exactOutputs: [
                "position", "tangentU", "tangentV", "secondDerivatives", "normal",
                "curvature", "principalDirections", "UVNFrame",
                "inverseParameterProjection", "verifiedResidual",
            ],
            failureCodes: [
                .invalidInput, .intersectionFailure, .resourceLimitExceeded, .topologyFailure,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.BSplineSurface3D",
                "CADGeometry.RationalBSplineSurface3D",
                "CADGeometry.SurfaceParameterProjection",
                "CADGeometry.SurfaceParameterProjectionOptions",
            ],
            testFixtures: ["GeometryKernelTests", "BSplineSurfaceParameterProjectionTests"]
        ),
        KernelCapability(
            id: "GEO-INTERSECTION-001",
            operation: "curveSurfaceIntersection",
            status: .partial,
            acceptedInputs: [
                "lineAnalyticSurface",
                "circleArcEllipseAgainstPlaneSphereCylinderConeOrTorus",
                "boundedRationalBSplineCurveSurface",
                "explicitFiniteParameterRanges",
            ],
            exactOutputs: [
                "closedFormAlgebraicPoint", "adaptivelyRefinedPoint",
                "curveParameter", "surfaceParameters", "intersectionKind",
                "verifiedResidual",
            ],
            failureCodes: [.invalidInput, .intersectionFailure, .nonDiscreteIntersection, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.CurveSurfaceIntersecting",
                "CADGeometry.DefaultCurveSurfaceIntersector",
                "CADGeometry.CurveSurfaceIntersection",
            ],
            testFixtures: [
                "CurveSurfaceIntersectionTests",
                "GeometryKernelTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "GEO-INTERSECTION-002",
            operation: "surfaceSurfaceIntersection",
            status: .partial,
            acceptedInputs: [
                "planePlane",
                "planeSphere",
                "planeCylinder",
                "planeConeEllipticOrApexGenerator",
                "boundedPlaneConeHyperbolicOrParabolicSectionWithCompleteFaceBoundaryContacts",
                "planeTorusAxialMeridionalSupportTangentOrRegularQuarticSection",
                "planeClampedBSplineBoundaryIsocurve",
                "planeBoundedRationalBSplineAdaptiveSection",
                "transverseCylinderConeSphereOrTorusAgainstBoundedRationalBSpline",
                "transverseBoundedRationalBSplinePair",
                "sphereSphere",
                "parallelCylinderCylinder",
                "intersectingEqualRadiusCylinderCylinder",
                "generalNonParallelCylinderCylinder",
                "generalNonCoaxialSphereCylinderAwayFromSphereParameterPoles",
                "generalNonCoaxialSphereConeAwayFromConeApexAndSphereParameterPoles",
                "coaxialSphereCylinder",
                "coaxialConeCylinder",
                "generalConeCylinderAwayFromConeApexAndRulingParallelGenerators",
                "coaxialSphereCone",
                "coaxialTorusCylinder",
                "parallelOffsetTorusCylinderWithoutInternalTangency",
                "generalNonParallelTorusCylinderWithCertifiedConstantSimpleGeneratorRoots",
                "coaxialSphereTorus",
                "generalNonCoaxialSphereTorusAwayFromSphereParameterPoles",
                "coaxialTorusTorus",
                "parallelOffsetTorusTorusWithFourFullDomainSimpleTransverseBranches",
                "generalNonParallelTorusTorusWithCertifiedConstantSimpleMeridianRoots",
                "coaxialConeTorus",
                "generalNonCoaxialConeTorusWithCertifiedConstantSimpleRulingRootsAwayFromApex",
                "coaxialConeCone",
                "generalConeConeWithTwoFullDomainSimpleTransverseBranchesAwayFromApexAndRulingAsymptote",
            ],
            exactOutputs: [
                "line", "circle", "ellipse", "tangentPoint", "coincidence",
                "boundedRationalBSplineCurve", "mixedContactCurve",
                "pseudoArclengthMarchedBSplineCurve", "dualSurfacePcurves",
                "exactAnalyticNURBSReduction", "seamUnwrappedAnalyticPcurve",
                "deterministicPeriodicPatchBoundaryAvoidance",
                "toleranceBoundedIntersectionComponentConsolidation",
                "analyticGeneratorIntervalClassification", "adaptiveCubicBSplineCurve",
                "analyticRadialDistanceIntervalClassification",
                "analyticSphereConeQuadraticIntervalClassification",
                "analyticSphereTorusTubeAngleClassification",
                "analyticConeCylinderGeneratorQuadraticClassification",
                "analyticConeConeRulingQuadraticClassification",
                "exactConeConeDiscriminantExtrema",
                "tangentHalfAngleQuarticRootIsolation",
                "intervalClassifiedPlaneTorusQuarticSections",
                "principalFrameBoundedHyperbolaClassification",
                "principalFrameBoundedParabolaClassification",
                "openAdaptiveCubicBSplineCurve",
                "analyticTorusCylinderRadialBandIntervalClassification",
                "intervalCertifiedTorusCylinderQuarticGeneratorRoots",
                "intervalCertifiedTorusTorusCircleBranches",
                "intervalCertifiedTorusTorusQuarticMeridianRoots",
                "intervalCertifiedConeTorusQuarticRulingRoots",
                "operandOrderStableCurveGeometry",
                "surfaceParameters", "verifiedResidual",
            ],
            failureCodes: [
                .invalidInput, .intersectionFailure, .nonDiscreteIntersection,
                .unsupportedCapability, .resourceLimitExceeded, .singularSystem,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADGeometry.SurfaceSurfaceIntersecting",
                "CADGeometry.DefaultSurfaceSurfaceIntersector",
                "CADGeometry.BoundedSurfaceSurfaceIntersecting",
                "CADGeometry.DefaultBoundedSurfaceSurfaceIntersector",
                "CADGeometry.SurfaceSurfaceIntersection",
            ],
            testFixtures: [
                "SurfaceSurfaceIntersectionTests",
                "BoundedBSplineSurfaceIntersectionTests",
                "AnalyticBSplineSurfaceIntersectionTests",
                "GeneralCylinderCylinderSurfaceIntersectionTests",
                "GeneralSphereCylinderSurfaceIntersectionTests",
                "GeneralSphereConeSurfaceIntersectionTests",
                "GeneralSphereTorusSurfaceIntersectionTests",
                "GeneralConeCylinderSurfaceIntersectionTests",
                "GeneralConeConeSurfaceIntersectionTests",
                "BoundedPlaneConeSurfaceIntersectionTests",
                "ParallelOffsetTorusCylinderSurfaceIntersectionTests",
                "ParallelOffsetTorusTorusSurfaceIntersectionTests",
                "GeneralTorusTorusSurfaceIntersectionTests",
                "GeneralTorusCylinderSurfaceIntersectionTests",
                "GeneralConeTorusSurfaceIntersectionTests",
                "GeneralCylinderBooleanIntersectionGraphTests",
                "GeneralCylinderBooleanClassificationTests",
                "IntersectingEqualRadiusCylinderSurfaceIntersectionTests",
                "PlaneBSplineBoundarySurfaceIntersectionTests",
                "RevolvedSurfaceIntersectionTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "TOPO-LINEAGE-001",
            operation: "topologyLineage",
            status: .partial,
            acceptedInputs: [
                "generatedFeatureOutput",
                "evaluatorOwnedCompleteLineage",
                "exactRelationParentCardinality",
                "mixedSplitMergeParentUse",
                "StableSubshapeReference",
                "edgeAndFaceSubobjectQuery",
            ],
            exactOutputs: [
                "SubshapeID",
                "SubshapeIndex",
                "TopologyLineage",
                "uniqueLiveDescendantResolution",
                "uniqueGeometrySignatureFallback",
                "typedSplitAmbiguity",
                "typedGeometryAmbiguity",
                "topologyKindCompatibleResolution",
                "multiGenerationLiveDescendantAmbiguity",
                "typedLineageCycleFailure",
                "oneToOneFeatureOutputCoverage",
                "evaluatingFeatureOutputOwnership",
                "noEngineInferredLineage",
            ],
            failureCodes: [.missingReference, .ambiguousSelection, .topologyFailure],
            tolerance: .standard,
            publicAPIs: [
                "CADCore.SubshapeID",
                "CADCore.TopologyLineage",
                "CADIR.StableSubshapeReference",
                "CADIR.SubshapeGeometrySignature",
                "CADIR.SubshapeIndex",
                "CADModeling.StableSubshapeResolving",
                "CADModeling.StableSubshapeResolver",
                "CADKernel.EvaluatedDocument",
                "CADKernel.EdgeQueryEvaluator",
                "CADKernel.SurfaceQueryEvaluator",
            ],
            testFixtures: [
                "TopologyLineageValidationTests",
                "FeatureTopologyLineageValidatorTests",
                "DocumentEvaluatorIncrementalTests",
                "StableSelectionResolverTests",
                "BooleanEvaluationPlanServiceTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "TOPO-BREP-001",
            operation: "validatedBRep",
            status: .partial,
            acceptedInputs: [
                "vertex",
                "edge",
                "coedge",
                "loop",
                "face",
                "shell",
                "body",
                "analyticCoordinatePcurves",
                "sphericalGreatCirclePcurves",
                "boundedTwoSphereBooleanShells",
                "boundedOffsetSphereConeBooleanShellsWithTwoClosedTransverseComponentsAndExternalConeCap",
                "boundedCoaxialSphereConeBooleanShells",
                "boundedCoaxialTorusCylinderBooleanShellsWithStrictInteriorIntersectionCircles",
                "boundedParallelOffsetTorusCylinderBooleanShellsWithTwoClosedTransverseComponentsAndExternalCylinderCaps",
                "boundedCenteredNonParallelTorusCylinderBooleanShellsWithTwoClosedTransverseComponentsAndExternalCylinderCaps",
                "boundedCoaxialSphereTorusBooleanShellsWithStrictInteriorIntersectionCircles",
                "boundedNonCoaxialSphereTorusBooleanShellsWithTwoClosedTransverseComponents",
                "boundedCoaxialTorusTorusBooleanShellsWithStrictInteriorIntersectionCircles",
                "boundedParallelOffsetTorusTorusBooleanShellsWithFourClosedTransverseComponents",
                "boundedNonParallelTorusTorusBooleanShellsWithTwoClosedTransverseComponents",
                "boundedPlanarCutterRingTorusBooleanShellsWithOneRegularQuarticLoop",
                "boundedCoaxialConeTorusBooleanShellsWithStrictInteriorIntersectionCirclesAndExternalConeCap",
                "boundedNonCoaxialConeTorusBooleanShellsWithTwoClosedTransverseComponentsAndExternalConeCap",
                "boundedCoaxialConeConeBooleanShellsWithOneStrictInteriorIntersectionCircle",
                "boundedTransverseConeConeBooleanShellsWithOneClosedTransverseComponentAndExternalCaps",
                "boundedCoaxialSphereCylinderBooleanShellsWithTwoStrictInteriorIntersectionCirclesAndExternalCylinderCaps",
                "boundedCoaxialConeCylinderBooleanShellsWithStrictInteriorSideAndCapIntersectionCircles",
                "boundedTransverseConeCylinderBooleanShellsWithTwoClosedSideComponentsAndExternalOrHyperbolicallyIntersectingCylinderCaps",
            ],
            exactOutputs: [
                "manifold",
                "watertight",
                "faceLocalPcurves",
                "monotoneGeometricPcurveCorrespondenceIndependentOfParameterization",
                "validatedExactTopology",
                "analyticCylinderVolume",
                "analyticRevolvedThroughHoleVolume",
                "adaptiveExactBoundaryAnalyticSurfaceVolume",
                "closedFormTwoSphereBooleanVolume",
                "closedFormSphereConeBooleanVolume",
                "adaptiveDiskSectionSphereConeBooleanVolume",
                "closedFormSphereTorusBooleanVolume",
                "adaptiveDiskSectionSphereTorusBooleanVolume",
                "closedFormSphereCylinderBooleanVolume",
                "adaptiveDiskSectionSphereCylinderBooleanVolume",
                "adaptiveAnnulusDiskSectionTorusCylinderBooleanVolume",
                "adaptiveAnnulusSectionTorusTorusBooleanVolume",
                "toleranceBoundedCenteredNonParallelTorusCylinderBooleanVolume",
            ],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            tolerance: .standard,
            publicAPIs: ["CADTopology.BRepModel", "CADTopology.ValidatedBRepModel"],
            testFixtures: [
                "BRepSewerTests",
                "ExactFacePcurveBuilderTests",
                "ExactIGESExchangeTests.roundTripsClockwiseHarmonicPcurveAsExactRationalBSpline",
                "BooleanEvaluationPlanServiceTests",
                "GeneralCylinderBooleanClassificationTests",
                "PrimitiveBooleanIntegrationTests",
                "PrimitiveFaceContainmentTests",
                "PrimitiveSphereBooleanIntegrationTests",
                "PrimitiveSphereConeBooleanIntegrationTests",
                "PrimitiveOffsetSphereConeBooleanIntegrationTests",
                "PrimitiveTorusCylinderBooleanIntegrationTests",
                "PrimitiveOffsetTorusCylinderBooleanIntegrationTests",
                "PrimitiveNonParallelTorusCylinderBooleanIntegrationTests",
                "PrimitiveSphereTorusBooleanIntegrationTests",
                "PrimitiveGeneralSphereTorusBooleanIntegrationTests",
                "PrimitiveTorusBooleanIntegrationTests",
                "PrimitiveOffsetTorusTorusBooleanIntegrationTests",
                "PrimitiveGeneralTorusTorusBooleanIntegrationTests",
                "PrimitivePlaneTorusBooleanIntegrationTests",
                "OffsetDiskSectionVolumeIntegratorTests",
                "PrimitiveConeTorusBooleanIntegrationTests",
                "PrimitiveGeneralConeTorusBooleanIntegrationTests",
                "PrimitiveConeBooleanIntegrationTests",
                "PrimitiveGeneralConeConeBooleanIntegrationTests",
                "PrimitiveSphereCylinderBooleanIntegrationTests",
                "PrimitiveConeCylinderBooleanIntegrationTests",
                "PrimitiveGeneralConeCylinderBooleanIntegrationTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "TOPO-SEWING-001",
            operation: "exactBRepSewing",
            status: .partial,
            acceptedInputs: [
                "orderedFacePatches",
                "planeCylinderConeSphereTorusSurfaces",
                "lineCircleTrims",
                "faceLocalPcurves",
                "analyticCoordinatePcurves",
                "sphericalGreatCirclePcurves",
            ],
            exactOutputs: [
                "deterministicCoedgeBRep",
                "manifoldValidation",
                "SubshapeID",
                "TopologyLineage",
            ],
            failureCodes: [.invalidInput, .topologyFailure, .nonManifoldResult],
            tolerance: .standard,
            publicAPIs: [
                "CADModeling.BRepSewing",
                "CADModeling.BRepSewingRequest",
                "CADModeling.BRepSewingStableKey",
                "CADKernel.BRepFacePatchExtracting",
                "CADModeling.DefaultBRepSewer",
            ],
            testFixtures: [
                "BRepSewerTests",
                "ExactFacePcurveBuilderTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "TOPO-REPAIR-001",
            operation: "explicitBRepRepair",
            status: .partial,
            acceptedInputs: [
                "callerSelectedValidationScopes",
                "duplicateBodyShellFaceLoopOwnershipReferences",
                "uniquelyReorderableAndOrientableLoopCoedgeCycle",
                "topologyAndGeometryUnreachableFromBodies",
            ],
            exactOutputs: [
                "independentMultiDiagnosticValidationReport",
                "unmodifiedInputModel",
                "explicitlyRepairedBRepModel",
                "beforeAfterValidationReports",
                "deterministicRepairChangeLedger",
                "typedUnrepairableDiagnostic",
            ],
            failureCodes: [.invalidInput, .missingReference, .topologyFailure],
            tolerance: .standard,
            publicAPIs: [
                "CADTopology.BRepTopologyValidating",
                "CADTopology.DefaultBRepTopologyValidator",
                "CADTopology.BRepValidationRequest",
                "CADTopology.BRepRepairing",
                "CADTopology.DefaultBRepRepairer",
                "CADTopology.BRepRepairRequest",
                "CADTopology.BRepRepairResult",
            ],
            testFixtures: [
                "BRepScopedValidationAndRepairTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "MODEL-SKETCH-001",
            operation: "sketch",
            status: .partial,
            acceptedInputs: [
                "pointLineCircleArcSplineEntities",
                "coincidentHorizontalVerticalParallelPerpendicularTangentEqualConcentricFixedConstraints",
                "distanceAngleRadiusDiameterDimensions",
            ],
            exactOutputs: [
                "forwardModeJacobian",
                "levenbergMarquardtSolution",
                "typedConstraintStatus",
                "validatedProfile",
                "validatedCurve",
            ],
            failureCodes: [
                .invalidInput,
                .underConstrained,
                .overConstrained,
                .conflictingConstraints,
                .singularSystem,
            ],
            tolerance: .standard,
            publicAPIs: [
                "CADIR.CADCommand.appendFeature",
                "CADKernel.SketchConstraintSolving",
                "CADKernel.LevenbergMarquardtSketchConstraintSolver",
                "CADKernel.SketchConstraintSolveResult",
            ],
            testFixtures: ["CADIRTests", "CADKernelTests", "SketchConstraintSolverTests"]
        ),
        feature(
            id: "MODEL-PRIMITIVE-001",
            operation: "primitive",
            inputs: [
                "placedBox",
                "placedCylinder",
                "placedCone",
                "placedSphere",
                "placedRingTorus",
                "positiveLengthExpressions",
            ],
            outputs: [
                "validatedExactBRep",
                "analyticPlaneCylinderConeSphereTorusFaces",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
                "exactAnalyticVolume",
            ],
            fixtures: ["PrimitiveFeatureTests", "PrimitiveCommandParityTests"],
            additionalPublicAPIs: ["CADModeling.PrimitiveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-EXTRUDE-001",
            operation: "extrude",
            inputs: [
                "planarClosedLineProfile",
                "planarClosedCircularArcProfile",
                "planarClosedRationalBSplineProfile",
                "positiveLengthExpression",
                "normalSymmetricOrNonTangentialVectorDirection",
            ],
            outputs: [
                "validatedExactBRep",
                "analyticPlanarAndCylindricalFaces",
                "rationalBSplineRuledSurfaces",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
            ],
            fixtures: [
                "CADKernelTests.rectangleExtrudeCreatesClosedBoxBRepAndDeterministicMesh",
                "CADKernelTests.circleProfileExtrudeCreatesExactCylindricalBRepAndDeterministicMesh",
                "CADKernelTests.closedSplineProfileExtrudeCreatesExactRuledBRep",
                "CADKernelTests.obliqueVectorExtrudeKeepsCapFacesParallelToSketchPlane",
                "ExactSplineExtrudeFeatureTests",
                "ExactSplineExtrudeCommandParityTests",
            ],
            additionalPublicAPIs: ["CADModeling.PlanarExtrudeFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-REVOLVE-001",
            operation: "revolve",
            inputs: [
                "planarClosedLineProfile",
                "planarClosedCircularArcProfile",
                "planarClosedCubicSplineProfile",
                "axis",
                "partialOrFullAngle",
                "radialAxialConicalSegments",
            ],
            outputs: [
                "validatedExactBRep",
                "analyticPlaneCylinderConeFaces",
                "rationalBSplineSurfacesOfRevolution",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
                "exactConicalFrustumVolume",
            ],
            fixtures: [
                "CADKernelTests.revolveBuildsValidatedConicalFrustum",
                "CurvedRevolveFeatureTests",
                "SketchSplineProfileExtractionTests",
                "CurvedRevolveCommandParityTests",
            ],
            additionalPublicAPIs: ["CADModeling.PlanarRevolveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SWEEP-001",
            operation: "sweep",
            inputs: [
                "oneClosedPlanarLineCircularArcOrExactRationalBSplineProfileForSolid",
                "oneBoundedPlanarExactCurveSectionForSheet",
                "oneConnectedOpenExactLineCircularEllipseOrRationalBSplinePath",
                "identityOrStraightPathLinearScaleSectionTransform",
                "straightNormalOrNonTangentialParallelPath",
                "curvedParallelPathWithCertifiedMonotoneProfileNormalAdvance",
                "circularPathNormalSolidReducibleToExactRevolve",
                "optionalExactPathPrefixDistanceFraction",
            ],
            outputs: [
                "validatedExactSolidOrSheetBRep",
                "exactAnalyticOrTensorProductRationalBSplineFaces",
                "mandatoryFaceLocalPcurves",
                "deterministicGeneratedLineage",
                "derivedMeshOnly",
            ],
            fixtures: [
                "ExactTranslationalSweepFeatureTests",
                "ExactLinearScaleSweepFeatureTests",
                "CADKernelTests.curvedParallelPathSweepCreatesExactTranslationalBRep",
                "CADKernelTests.circularPathNormalSweepProducesExactRevolvedBRep",
                "SweepEvaluationPlanServiceTests",
                "ExactTranslationalSweepCommandParityTests",
                "ExactLinearScaleSweepCommandParityTests",
                "ExactCircularPathNormalSweepCommandParityTests",
            ],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .sweepSimplifyUnavailable,
                .sweepProfilePlaneDegenerate,
                .sweepMixedNormalAdvance,
                .sweepMonotonicityCertificateUnavailable,
                .sweepBooleanRequiresSolid,
                .sweepInvalidGuideConstraintCount,
                .sweepRoundCornerUnavailable,
                .sweepPathNormalUnavailable,
                .sweepScaleCollapse,
                .sweepScalePathUnavailable,
                .sweepTwistUnavailable,
                .sweepGuideConstraintUnavailable,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: [
                "CADModeling.PlanarSweepFeatureEvaluator",
                "CADKernel.SweepEvaluationPlanService",
            ]
        ),
        feature(
            id: "MODEL-LOFT-001",
            operation: "loft",
            inputs: ["profileSections"],
            outputs: ["validatedBRep", "validatedSheet"],
            fixtures: ["LoftFeatureTests"],
            additionalPublicAPIs: ["CADModeling.LoftFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-BOOLEAN-001",
            operation: "boolean",
            inputs: [
                "orthogonalPlanarSolid",
                "singleShellConvexPlanarLineEdgeSolids",
                "coincidentPlanarBoundary",
                "arbitraryAxisCylinderOrConeThroughBlindOrContainedDifferenceAndPositiveAxialOverlapIntersection",
                "arbitraryAxisCylinderOrConeContainedOrProtrudingBeyondOneOrBothTargetCapsUnion",
                "convexPlanarTargetContainedByArbitraryAxisCylinderOrCone",
                "axisParallelCylinderWithCoincidentCapBoundsAndStrictTransverseIntersectionsAgainstConvexTargetBoundary",
                "multiComponentPartialCylinderDifference",
                "singleClosedRationalBSplineTransverseIntersectionWithBothBoundedInteriorRegionsSelected",
                "boundedNonParallelSolidCylinderBooleansWithSimplyConnectedFacePartitions",
                "boundedOffsetSphereCylinderBooleansWithTwoClosedTransverseComponentsAndNoCapContact",
                "boundedOffsetSphereSphereBooleansWithOneTransverseCircle",
                "boundedOffsetSphereConeBooleansWithTwoClosedTransverseComponentsAndExternalConeCap",
                "boundedCoaxialSphereConeBooleansWithTwoTransverseCirclesAndExternalConeCap",
                "boundedCoaxialTorusCylinderBooleansWithTwoStrictFaceInteriorTransverseCirclesAndExternalCylinderCaps",
                "boundedParallelOffsetTorusCylinderBooleansWithTwoClosedTransverseComponentsAndExternalCylinderCaps",
                "boundedCenteredNonParallelTorusCylinderBooleansWithTwoClosedTransverseComponentsAndExternalCylinderCaps",
                "boundedCoaxialSphereTorusBooleansWithTwoStrictFaceInteriorTransverseCircles",
                "boundedNonCoaxialSphereTorusBooleansWithTwoClosedTransverseComponents",
                "boundedCoaxialTorusTorusBooleansWithTwoStrictFaceInteriorTransverseCircles",
                "boundedParallelOffsetTorusTorusBooleansWithFourClosedTransverseComponents",
                "boundedNonParallelTorusTorusBooleansWithTwoClosedTransverseComponents",
                "boundedPlanarCutterRingTorusBooleansWithOneRegularQuarticLoopAndExternalRemainingCutterFaces",
                "boundedCoaxialConeTorusBooleansWithTwoStrictFaceInteriorTransverseCirclesAndExternalConeCap",
                "boundedNonCoaxialConeTorusBooleansWithTwoClosedTransverseComponentsAndExternalConeCap",
                "boundedCoaxialConeConeBooleansWithOneStrictFaceInteriorTransverseCircle",
                "boundedTransverseConeConeBooleansWithOneClosedTransverseComponentAndExternalCaps",
                "boundedCoaxialSphereCylinderBooleansWithTwoStrictFaceInteriorTransverseCirclesAndExternalCylinderCaps",
                "boundedCoaxialConeCylinderBooleansWithStrictFaceInteriorSideAndCapIntersectionCircles",
                "boundedTransverseConeCylinderBooleansWithTwoClosedSideComponentsAndExternalOrHyperbolicallyIntersectingCylinderCaps",
            ],
            outputs: [
                "intersectionGraph",
                "faceSurfaceIntersections",
                "uvSplitGraph",
                "classificationGraph",
                "adaptiveNonBoundaryClassification",
                "regionSelectionGraph",
                "exactRegionSelectionGraph",
                "deterministicSewingRequest",
                "convexPlanarUnion",
                "convexPlanarDifference",
                "convexPlanarIntersection",
                "revolvedThroughHole",
                "revolvedBlindHole",
                "revolvedCavity",
                "revolvedIntersection",
                "revolvedUnion",
                "partialCylinderDifference",
                "partialCylinderIntersection",
                "partialCylinderUnion",
                "generalCylinderDifference",
                "generalCylinderIntersection",
                "generalCylinderUnion",
                "generalSphereCylinderUnionDifferenceIntersection",
                "coaxialSphereCylinderUnionDifferenceIntersection",
                "generalSphereSphereUnionDifferenceIntersection",
                "generalSphereConeUnionDifferenceIntersection",
                "coaxialSphereConeUnionDifferenceIntersection",
                "coaxialTorusCylinderUnionDifferenceIntersection",
                "parallelOffsetTorusCylinderUnionDifferenceIntersection",
                "centeredNonParallelTorusCylinderUnionDifferenceIntersection",
                "coaxialSphereTorusUnionDifferenceIntersection",
                "generalSphereTorusUnionDifferenceIntersection",
                "coaxialTorusTorusUnionDifferenceIntersection",
                "parallelOffsetTorusTorusUnionDifferenceIntersection",
                "generalTorusTorusUnionDifferenceIntersection",
                "generalPlaneTorusUnionDifferenceIntersection",
                "coaxialConeTorusUnionDifferenceIntersection",
                "generalConeTorusUnionDifferenceIntersection",
                "coaxialConeConeUnionDifferenceIntersection",
                "generalConeConeUnionDifferenceIntersection",
                "coaxialConeCylinderUnionDifferenceIntersection",
                "generalConeCylinderUnionDifferenceIntersection",
                "boundedPlaneConeHyperbolicCapSections",
                "dualPcurveClosedIntersectionShell",
                "multiClosedPcurveContainmentTree",
                "bSplineBoundedPlaneCylinderShell",
                "bSplineBoundedAnalyticSurfaceShell",
                "adaptiveExactBoundaryAnalyticSurfaceVolume",
                "closedFormTwoSphereBooleanVolume",
                "closedFormSphereConeBooleanVolume",
                "adaptiveDiskSectionSphereConeBooleanVolume",
                "closedFormSphereTorusBooleanVolume",
                "adaptiveDiskSectionSphereTorusBooleanVolume",
                "closedFormSphereCylinderBooleanVolume",
                "adaptiveDiskSectionSphereCylinderBooleanVolume",
                "adaptiveAnnulusDiskSectionTorusCylinderBooleanVolume",
                "adaptiveAnnulusSectionTorusTorusBooleanVolume",
                "toleranceBoundedCenteredNonParallelTorusCylinderBooleanVolume",
                "carriedOperand",
                "TopologyLineage",
                "validatedExactBRep",
            ],
            fixtures: [
                "BooleanIntersectionGraphTests",
                "ClosedIntersectionSewingLoopBuilderTests",
                "GeneralCylinderBooleanClassificationTests",
                "PrimitiveBooleanIntegrationTests",
                "PrimitiveFaceContainmentTests",
                "PrimitiveSphereBooleanIntegrationTests",
                "PrimitiveSphereConeBooleanIntegrationTests",
                "PrimitiveOffsetSphereConeBooleanIntegrationTests",
                "PrimitiveTorusCylinderBooleanIntegrationTests",
                "PrimitiveOffsetTorusCylinderBooleanIntegrationTests",
                "PrimitiveNonParallelTorusCylinderBooleanIntegrationTests",
                "PrimitiveSphereTorusBooleanIntegrationTests",
                "PrimitiveGeneralSphereTorusBooleanIntegrationTests",
                "PrimitiveTorusBooleanIntegrationTests",
                "PrimitiveOffsetTorusTorusBooleanIntegrationTests",
                "PrimitiveGeneralTorusTorusBooleanIntegrationTests",
                "PrimitivePlaneTorusBooleanIntegrationTests",
                "PrimitiveConeTorusBooleanIntegrationTests",
                "PrimitiveGeneralConeTorusBooleanIntegrationTests",
                "PrimitiveConeBooleanIntegrationTests",
                "PrimitiveGeneralConeConeBooleanIntegrationTests",
                "PrimitiveSphereCylinderBooleanIntegrationTests",
                "PrimitiveConeCylinderBooleanIntegrationTests",
                "PrimitiveGeneralConeCylinderBooleanIntegrationTests",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactConicalThroughHole",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactContainedCylindricalCavity",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactContainedConicalCavity",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactLowerCylindricalBlindHole",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactUpperConicalBlindHole",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactConicalIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationPreservesContainedCylinderForIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactPartialConicalIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactConicalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactUpperCylindricalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactLowerConicalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationPreservesTargetForContainedCylindricalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCarriesRevolvedToolForTargetContainedUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCarriesPlanarTargetForTargetContainedIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationReportsEmptyDifferenceForTargetContainedByRevolvedTool",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCarriesPlanarTargetForAxiallySeparatedDifference",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationReportsTypedEmptyIntersectionForAxiallySeparatedTool",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesAxiallySeparatedConicalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCarriesPlanarTargetForRadiallySeparatedDifference",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationReportsTypedEmptyIntersectionForRadiallySeparatedTool",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCarriesTargetForTangentialCylindricalDifference",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationReportsTypedEmptyIntersectionForTangentialCylindricalTool",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationRejectsTangentialCylindricalUnionAsNonManifold",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactSideCrossingCylindricalDifference",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactSideCrossingCylindricalIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactSideCrossingCylindricalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactOutsideAxisCylindricalDifference",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactOutsideAxisCylindricalIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactOutsideAxisCylindricalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactCornerCylindricalDifference",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactCornerCylindricalIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactCornerCylindricalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactInsideCornerCylindricalDifference",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactInsideCornerCylindricalIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesExactInsideCornerCylindricalUnion",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesTwoShellOppositeSideCylindricalDifference",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesOppositeSideCylindricalIntersection",
                "BooleanEvaluationPlanServiceTests.booleanEvaluationCreatesOppositeSideCylindricalUnion",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalConicalIntersection",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalPartialConicalIntersection",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalConicalUnion",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalContainedConicalUnion",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalTargetContainedConicalUnion",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalContainedConicalDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalUpperBlindConicalDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalAxiallySeparatedConicalDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalRadiallySeparatedConicalDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalTangentialRevolvedDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalSideCrossingCylindricalDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalOutsideAxisCylindricalDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalCornerCylindricalDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalInsideCornerCylindricalDifference",
                "CADCommandPipelineTests.builderAndCodableCommandProduceIdenticalTwoShellCylindricalDifference",
                "CADKernelTests",
            ],
            failureCodes: [
                .invalidInput,
                .unsupportedCapability,
                .classificationFailure,
                .emptyResult,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: [
                "CADModeling.BooleanFeatureEvaluator",
                "CADModeling.BooleanOperationApplying",
            ]
        ),
        feature(
            id: "MODEL-POLYSPLINE-001",
            operation: "polySpline",
            inputs: ["supportedQuadMesh"],
            outputs: ["validatedSheet"],
            fixtures: ["CADKernelTests"],
            additionalPublicAPIs: [
                "CADModeling.PolySplineFeatureEvaluator",
                "CADModeling.PolySplineMeshAnalyzer",
            ]
        ),
        feature(
            id: "MODEL-BSPLINESURFACE-001",
            operation: "bSplineSurface",
            inputs: ["rationalBSplineSurface", "trimLoops"],
            outputs: ["validatedSheet"],
            fixtures: ["SurfaceFeatureEvaluatorTests", "CADKernelTests"],
            additionalPublicAPIs: ["CADModeling.BSplineSurfaceFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACELOOPOFFSET-001",
            operation: "faceLoopOffset",
            inputs: ["planarRectangularFace", "offsetDistance"],
            outputs: ["validatedBRep"],
            fixtures: ["CADKernelTests"],
            additionalPublicAPIs: ["CADModeling.FaceLoopOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-EDGEOFFSET-001",
            operation: "edgeOffset",
            inputs: ["edgeSelection", "supportFace", "offsetDistance"],
            outputs: ["validatedCurve"],
            fixtures: ["CADKernelTests"],
            additionalPublicAPIs: ["CADModeling.EdgeOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEKNIFE-001",
            operation: "faceKnife",
            inputs: ["planarFace", "knifeLoop"],
            outputs: ["validatedBRep", "TopologyLineage"],
            fixtures: ["CADKernelTests"],
            additionalPublicAPIs: ["CADModeling.FaceKnifeFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEDELETE-001",
            operation: "faceDelete",
            inputs: ["faceSelections"],
            outputs: ["validatedBRep", "TopologyLineage"],
            fixtures: ["CADKernelTests"],
            additionalPublicAPIs: ["CADModeling.FaceDeleteFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEDRAFT-001",
            operation: "faceDraft",
            inputs: ["faceSelections", "neutralFace", "angle"],
            outputs: ["validatedBRep", "TopologyLineage"],
            fixtures: ["CADKernelTests"],
            additionalPublicAPIs: ["CADModeling.FaceDraftFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CHAMFER-001",
            operation: "chamfer",
            inputs: [
                "singleStraightEdge",
                "singleShellSolid",
                "twoPerpendicularPlanarIncidentFaces",
                "positiveEqualDistance",
            ],
            outputs: ["validatedExactBRep", "faceLocalPcurves", "strictRequestDecoding", "TopologyLineage", "preservedUnrelatedBodiesAndSelections"],
            fixtures: ["ChamferFeatureTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.ChamferFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FILLET-001",
            operation: "fillet",
            inputs: [
                "singleStraightConvexEdge",
                "singleShellOrthogonalSolid",
                "twoPerpendicularPlanarIncidentFaces",
                "positiveConstantRadius",
            ],
            outputs: ["validatedExactBRep", "quarterCylinder", "verifiedG1Tangency", "faceLocalPcurves", "strictRequestDecoding", "TopologyLineage", "preservedUnrelatedBodiesAndSelections"],
            fixtures: ["FilletFeatureTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.FilletFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-G2BLEND-001",
            operation: "g2Blend",
            inputs: [
                "singleStraightConvexEdge",
                "singleShellOrthogonalSolid",
                "twoPerpendicularPlanarIncidentFaces",
                "positiveSymmetricSetbackDistance",
            ],
            outputs: [
                "validatedExactBRep",
                "quinticBSplineSurface",
                "verifiedG2Tangency",
                "faceLocalPcurves",
                "strictRequestDecoding",
                "TopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["G2BlendFeatureTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.G2BlendFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SETBACKCORNER-001",
            operation: "setbackCorner",
            inputs: [
                "oneTrihedralConvexVertex",
                "oneOrthogonalHexahedralSolid",
                "threeMutuallyPerpendicularStraightEdges",
                "positiveEqualRollingBallRadius",
            ],
            outputs: [
                "validatedExactBRep",
                "threeQuarterCylinders",
                "sphericalOctant",
                "verifiedG1Tangency",
                "sphericalGreatCirclePcurves",
                "strictRequestDecoding",
                "TopologyLineage",
                "deterministicRightHandedEdgeOrdering",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["SetbackCornerFeatureTests", "SphericalGreatCirclePcurveTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.SetbackCornerFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SHELL-001",
            operation: "shell",
            inputs: [
                "oneOrthogonalHexahedralSolid",
                "oneRemovedPlanarFace",
                "positiveUniformInwardThickness",
            ],
            outputs: [
                "validatedExactBRep",
                "fiveOuterFaces",
                "fiveInnerOffsetFaces",
                "fourOpeningRimFaces",
                "analyticVolume",
                "strictRequestDecoding",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["ShellFeatureTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.ShellFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-EDGEMOVE-001",
            operation: "edgeMove",
            inputs: [
                "oneLineOnlyPlanarSolid",
                "oneStraightEdge",
                "finiteDirection",
                "finiteSignedDistancePreservingPlanarityAndVolume",
            ],
            outputs: [
                "validatedExactBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["EdgeMoveFeatureTests", "EdgeMoveBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.EdgeMoveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-VERTEXMOVE-001",
            operation: "vertexMove",
            inputs: [
                "oneSingleShellLineOnlyPlanarSolid",
                "oneVertex",
                "finiteDirection",
                "finiteSignedDistancePreservingPositiveVolume",
            ],
            outputs: [
                "validatedExactBRep",
                "nonPlanarIncidentFaceTriangulation",
                "faceLocalPcurves",
                "analyticVolume",
                "splitAndPreservedTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["VertexMoveFeatureTests", "VertexMoveBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.VertexMoveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEOFFSET-001",
            operation: "faceOffset",
            inputs: [
                "oneConvexLineOnlyPlanarSolid",
                "onePlanarFace",
                "finiteSignedNormalDistancePreservingConvexPositiveVolume",
            ],
            outputs: [
                "validatedExactBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["FaceOffsetFeatureTests", "FaceOffsetBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.FaceOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEMOVE-001",
            operation: "faceMove",
            inputs: [
                "oneConvexLineOnlyPlanarSolid",
                "onePlanarFace",
                "finiteDirection",
                "finiteSignedDistancePreservingConvexPositiveVolume",
            ],
            outputs: [
                "validatedExactBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["FaceMoveFeatureTests", "FaceMoveBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.FaceMoveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-LINEARPATTERN-001",
            operation: "linearPattern",
            inputs: [
                "oneLineOnlyPlanarSolid",
                "finiteDirection",
                "positiveSpacing",
                "twoToOneThousandSeparatedInstances",
            ],
            outputs: [
                "validatedExactMultiShellBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "splitTopologyLineage",
                "typedAmbiguousSourceSelection",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["LinearPatternFeatureTests", "LinearPatternBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .resourceLimitExceeded,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.LinearPatternFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-RADIALPATTERN-001",
            operation: "radialPattern",
            inputs: [
                "oneLineOnlyPlanarSolid",
                "finiteAxis",
                "finiteNonzeroAngularSpacing",
                "twoToOneThousandSeparatedInstances",
            ],
            outputs: [
                "validatedExactMultiShellBRep",
                "rigidlyRotatedAnalyticGeometry",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "splitTopologyLineage",
                "typedAmbiguousSourceSelection",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["RadialPatternFeatureTests", "PatternBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .resourceLimitExceeded,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.RadialPatternFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-GRIDPATTERN-001",
            operation: "gridPattern",
            inputs: [
                "oneLineOnlyPlanarSolid",
                "twoFiniteNonparallelDirections",
                "twoPositiveSpacings",
                "fourToOneThousandSeparatedInstances",
            ],
            outputs: [
                "validatedExactMultiShellBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "splitTopologyLineage",
                "typedAmbiguousSourceSelection",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["GridPatternFeatureTests", "PatternBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .resourceLimitExceeded,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.GridPatternFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEDRIVENPATTERN-001",
            operation: "curveDrivenPattern",
            inputs: [
                "oneLineOnlyPlanarSolid",
                "oneConnectedOpenEvaluatedCurveChain",
                "finiteAnchorAndReferenceDirection",
                "twoToOneThousandSeparatedInstances",
            ],
            outputs: [
                "validatedExactMultiShellBRep",
                "equalArcLengthPlacement",
                "minimumRotationTangentAlignment",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "splitTopologyLineage",
                "typedAmbiguousSourceSelection",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["CurveDrivenPatternFeatureTests", "CurveDrivenPatternBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .resourceLimitExceeded,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.CurveDrivenPatternFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-THICKEN-001",
            operation: "thicken",
            inputs: [
                "onePlanarSheetFace",
                "oneStraightOuterBoundaryLoop",
                "positiveUniformThickness",
                "positiveNegativeOrSymmetricSide",
            ],
            outputs: [
                "validatedExactBRep",
                "planarPrismaticSolid",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["ThickenFeatureTests", "ThickenBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.ThickenFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-BRIDGECURVE-001",
            operation: "bridgeCurve",
            inputs: [
                "twoFiniteExactCurveEndpoints",
                "explicitG0G1OrG2Continuity",
                "optionalPositiveEndpointDerivativeMagnitudes",
            ],
            outputs: [
                "exactPolynomialBezierBSplineCurve",
                "verifiedEndpointContinuity",
                "kernelDerivedDisplaySamples",
                "strictRequestDecoding",
            ],
            fixtures: [
                "CADKernelTests.bridgeCurveFeatureEvaluatorProducesGeneratedCurve",
                "DerivedCurveSamplingTests",
                "CurveDerivedSamplingSchemaTests",
            ],
            additionalPublicAPIs: [
                "CADModeling.BridgeCurveFeatureEvaluator",
                "CADModeling.CurveBridgeSolver",
            ]
        ),
        feature(
            id: "MODEL-BRIDGESURFACE-001",
            operation: "bridgeSurface",
            inputs: [
                "twoFinitePositiveWeightRationalBSplineBoundaries",
                "matchingDegreeControlPointCountAndNormalizedKnotDistribution",
                "forwardOrReversedEndOrientation",
                "sampledRegularRuledSpan",
            ],
            outputs: [
                "validatedExactSheetBRep",
                "rationalRuledBSplineSurface",
                "exactBoundaryInterpolation",
                "faceLocalPcurves",
                "strictRequestDecoding",
                "deterministicGeneratedTopologyLineage",
            ],
            fixtures: ["SurfaceFeatureEvaluatorTests", "BridgeSurfaceBuilderTests", "NativeOperationSchemaTests"],
            additionalPublicAPIs: ["CADModeling.BridgeSurfaceFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-PATCHSURFACE-001",
            operation: "patchSurface",
            inputs: [
                "fourFinitePolynomialSingleSpanBezierBoundaries",
                "matchingDegreesOnOppositeBoundaries",
                "explicitIndependentBoundaryOrientations",
                "cornerCoincidenceWithinTolerance",
                "sampledRegularCoonsSpan",
            ],
            outputs: [
                "validatedExactSheetBRep",
                "polynomialCoonsBSplineSurface",
                "fourBoundaryInterpolationWithinTolerance",
                "faceLocalPcurves",
                "strictRequestDecoding",
                "deterministicGeneratedTopologyLineage",
            ],
            fixtures: ["SurfaceFeatureEvaluatorTests", "PatchSurfaceBuilderTests", "NativeOperationSchemaTests"],
            failureCodes: [
                .invalidInput,
                .unsupportedCapability,
                .singularSystem,
                .topologyFailure,
            ],
            additionalPublicAPIs: ["CADModeling.PatchSurfaceFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEEDIT-001",
            operation: "curveEdit",
            inputs: ["exactBSplineCurveSelection", "controlPointKnotOrWeightEdits"],
            outputs: [
                "validatedExactBSplineCurve",
                "kernelDerivedDisplaySamples",
                "strictRequestDecoding",
            ],
            fixtures: ["CADKernelTests", "CurveDerivedSamplingSchemaTests"],
            additionalPublicAPIs: ["CADModeling.CurveEditFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEOFFSET-001",
            operation: "curveOffset",
            inputs: ["exactLineCircleOrArc", "positiveDistance", "orientedPlaneNormal", "leftOrRightSide"],
            outputs: ["exactAnalyticCurve", "preservedParameterDomain", "derivedDisplaySamples"],
            fixtures: ["CurveOffsetTrimFeatureTests", "CurveOffsetTrimBuilderTests"],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability],
            additionalPublicAPIs: ["CADModeling.CurveOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVETRIM-001",
            operation: "curveTrim",
            inputs: ["exactCurve", "containedFiniteParameterDomain"],
            outputs: ["unchangedExactCurve", "finiteTrimDomain", "derivedDisplaySamples"],
            fixtures: ["CurveTrimFeatureEvaluatorTests", "CurveOffsetTrimBuilderTests"],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability],
            additionalPublicAPIs: ["CADModeling.CurveTrimFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEEXTEND-001",
            operation: "curveExtend",
            inputs: ["finiteExactLineOrCircularArc", "startEndOrBoth", "positiveExtensionLength"],
            outputs: ["exactExtendedCurve", "expandedFiniteParameterDomain", "derivedDisplaySamples"],
            fixtures: ["CurveExtendFeatureTests", "CurveExtendBuilderTests"],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure],
            additionalPublicAPIs: ["CADModeling.CurveExtendFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEMATCH-001",
            operation: "curveMatch",
            inputs: ["oneNonRationalClampedCubicBezierSource", "oneFiniteExactTargetEndpoint", "G0G1OrG2Request"],
            outputs: ["exactMatchedCubicBezier", "verifiedPositionTangentAndCurvatureResiduals", "derivedDisplaySamples"],
            fixtures: ["CurveMatchFeatureTests", "CurveMatchBuilderTests"],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .singularSystem, .conflictingConstraints, .topologyFailure],
            additionalPublicAPIs: ["CADModeling.CurveMatchFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SURFACEOFFSET-001",
            operation: "surfaceOffset",
            inputs: ["oneSingleFaceLineBoundedPlanarSheet", "finiteSignedNormalDistance"],
            outputs: ["validatedExactSheetBRep", "translatedPlaneAndBoundaryCurves", "faceLocalPcurves", "preservedTopologyLineage", "preservedUnrelatedBodiesAndSelections"],
            fixtures: ["SurfaceOffsetFeatureTests", "SurfaceOffsetBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure],
            additionalPublicAPIs: ["CADModeling.SurfaceOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SURFACETRIM-001",
            operation: "surfaceTrim",
            inputs: ["oneRectangularLineBoundedPlanarSheet", "containedFiniteUVDomains"],
            outputs: ["validatedExactTrimmedSheetBRep", "rebuiltBoundaryCurvesAndPcurves", "preservedTopologyLineage", "preservedUnrelatedBodiesAndSelections"],
            fixtures: ["SurfaceTrimExtendFeatureTests", "SurfaceTrimExtendBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure],
            additionalPublicAPIs: ["CADModeling.SurfaceTrimFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SURFACEEXTEND-001",
            operation: "surfaceExtend",
            inputs: ["oneRectangularLineBoundedPlanarSheet", "fourNonnegativePhysicalExtensionDistances"],
            outputs: ["validatedExactExtendedSheetBRep", "rebuiltBoundaryCurvesAndPcurves", "preservedTopologyLineage", "preservedUnrelatedBodiesAndSelections"],
            fixtures: ["SurfaceTrimExtendFeatureTests", "SurfaceTrimExtendBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure],
            additionalPublicAPIs: ["CADModeling.SurfaceExtendFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SURFACEMATCH-001",
            operation: "surfaceMatch",
            inputs: ["twoRectangularLineBoundedPlanarSheets", "twoContainedUVAnchors", "alignedOrOpposedNormals", "G0G1OrG2Request"],
            outputs: ["validatedExactMatchedSheetBRep", "verifiedPositionNormalAndCurvatureResiduals", "mergedTargetFaceLineage", "preservedUnrelatedBodiesAndSelections"],
            fixtures: ["SurfaceMatchFeatureTests", "SurfaceMatchBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .conflictingConstraints, .topologyFailure],
            additionalPublicAPIs: ["CADModeling.SurfaceMatchFeatureEvaluator"]
        ),
        KernelCapability(
            id: "API-PARITY-001",
            operation: "CADCommand",
            status: .partial,
            acceptedInputs: ["UI", "Builder", "Agent"],
            exactOutputs: [
                "CADDocument",
                "KernelQueryResult",
                "snapMeasurementAndSelectionResults",
                "curveEdgeAndSurfaceProjectionResults",
                "diagnostics",
            ],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability],
            tolerance: .standard,
            publicAPIs: [
                "CADIR.CADCommand",
                "SwiftCAD.DocumentEditing",
                "SwiftCAD.DocumentEditor",
                "SwiftCAD.CADPipeline",
                "CADKernel.KernelQuery",
                "CADKernel.KernelQueryResult",
                "CADKernel.ProjectionQuery",
                "CADKernel.ProjectionQueryResult",
            ],
            testFixtures: [
                "CADCommandPipelineTests",
                "KernelQueryPipelineTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-STEP-001",
            operation: "STEP",
            status: .partial,
            acceptedInputs: [
                "validatedLineBoundedPlanarBRep",
                "finiteTrimmedOpenNonPeriodicRationalBSplineEdgesInEitherSense",
                "finiteSubperiodCircleAndEllipseEdgesAcrossPeriodicSeamsInEitherSense",
                "piecewiseLinearPolylinePcurves",
                "singleForwardOuterShellWithReversedVoidShells",
                "SILengthUnitsAndConversionBasedInchFootUnits",
            ],
            exactOutputs: [
                "AP242AdvancedFaces",
                "SurfaceCurvesAndPcurves",
                "EdgeCurveSameSenseRoundTrip",
                "PeriodicConicTrimDirectionAndPcurveRoundTrip",
                "PolylinePcurveDegreeOneBSplineRoundTrip",
                "EdgeLoops",
                "OpenOrClosedShells",
                "BrepWithVoidsAndOrientedClosedShells",
                "ExactLengthUnitAndPhysicalUncertaintyRoundTrip",
                "ManifoldSolidOrSheetModel",
                "DeterministicExactImport",
                "NoMeshFallback",
            ],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: ["CADExchange.STEPExchange"],
            testFixtures: [
                "ExactSTEPExchangeTests",
                "ExactSTEPExchangeTests.roundTripsExactPlanarTopologyInConversionBasedLengthUnits",
                "ExactSTEPExchangeTests.roundTripsPolylinePcurvesExactlyThroughSTEPAndIGES",
                "ExactSTEPExchangeTests.roundTripsSeamCrossingCircleAndEllipseEdges",
                "ExactSTEPExchangeTests.roundTripsSolidVoidShellTopologyAndVolume",
                "CADExchangeTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-IGES-001",
            operation: "IGES",
            status: .partial,
            acceptedInputs: [
                "validatedSheetBodyWithOneOrMoreOpenShells",
                "finiteTrimmedOpenNonPeriodicRationalBSplineEdgesInEitherSense",
                "finiteSubperiodCircleAndEllipseEdgesAcrossPeriodicSeamsInEitherSense",
                "finiteSubperiodArbitraryAxisAnalyticArcEdgesInEitherSense",
                "harmonicEllipticPcurvesInEitherOrientation",
                "piecewiseLinearPolylinePcurves",
                "singleForwardOuterShellWithReversedVoidShells",
                "IGESLengthUnits",
            ],
            exactOutputs: [
                "Type110ModelAndParameterCurves",
                "Type100AnalyticArcIdentityAndDirectionRoundTrip",
                "Type126CurveParameterDirectionRoundTrip",
                "PeriodicConicTrimDirectionAndPcurveRoundTrip",
                "ClockwiseHarmonicPcurveType126ExactRoundTrip",
                "PolylinePcurveDegreeOneBSplineRoundTrip",
                "Type190PlaneSurfaces",
                "Type502To514ManifoldTopology",
                "Type402Form7MultiShellSheetBodyGroups",
                "Type186OuterAndVoidShellUses",
                "DeterministicExactImport",
                "NoMeshFallback",
            ],
            failureCodes: [.invalidInput, .missingReference, .unsupportedCapability, .topologyFailure, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: ["CADExchange.IGESExchange"],
            testFixtures: [
                "ExactIGESExchangeTests",
                "ExactIGESExchangeTests.roundTripsArbitraryAxisAnalyticArcEdgesInBothDirections",
                "ExactIGESExchangeTests.roundTripsSeamCrossingCircleAndEllipseEdges",
                "ExactIGESExchangeTests.roundTripsClockwiseHarmonicPcurveAsExactRationalBSpline",
                "ExactSTEPExchangeTests.roundTripsPolylinePcurvesExactlyThroughSTEPAndIGES",
                "ExactIGESExchangeTests.roundTripsMultiShellSheetBodyAsForm7Group",
                "ExactIGESExchangeTests.roundTripsSolidVoidShellTopologyAndVolume",
                "CADExchangeTests",
                "KernelCapabilityContractTests",
            ]
        ),
        KernelCapability(
            id: "EXCHANGE-USD-001",
            operation: "USDMeshExchange",
            status: .partial,
            acceptedInputs: [
                "USDA",
                "USDC",
                "USDZ",
                "StandaloneDirectMeshLayer",
                "USDZPackageLocalComposition",
                "ExplicitTimeCodeSnapshot",
                "DerivedTriangleMesh",
            ],
            exactOutputs: [
                "ZeroCopyRetainedInputSlice",
                "DerivedMeshPositionsAndTopology",
                "UnitsAndUpAxis",
                "StandardNormalsInterpolationWithDerivedMeshExpansion",
                "TextureCoordinatesAndDisplayColor",
                "TypedUSDAndCompositionDiagnostics",
                "StandaloneSdfLayerSemanticPreflight",
                "TypedSdfLayerAuthoring",
                "PureSwiftUSDAUSDCUSDZCodecs",
                "USDCUSDZVertexPrimvarRoundTrip",
                "USDZComposedSublayerReferenceAndPayloadMeshImport",
                "ExplicitTimeSampledSceneSnapshot",
                "TypedUSDAUnsupportedVertexPrimvarDiagnostic",
                "BoundedImportResources",
            ],
            failureCodes: [.invalidInput, .unsupportedCapability, .resourceLimitExceeded],
            tolerance: .standard,
            publicAPIs: [
                "CADExchange.USDExchange",
                "CADUSD.USDSceneImporting",
                "CADUSD.SceneImporter",
                "OpenUSD.USDSceneReader",
                "OpenUSD.USDAReader.readSdfLayer",
                "OpenUSD.USDAReader.read",
                "OpenUSDC.USDCReader.readSdfLayer",
                "OpenUSDC.USDCReader.read",
                "OpenUSDZ.USDZReader.read",
            ],
            testFixtures: [
                "CADUSDImportTests",
                "USDExchangePureSwiftImportTests",
                "USDExchangePureSwiftImportTests.pureSwiftUSDAImportEvaluatesRequestedTimeSample",
                "USDExchangePureSwiftImportTests.standaloneUSDAImportRejectsUnresolvedCompositionArc",
                "USDExchangePureSwiftImportTests.standaloneUSDCImportRejectsUnresolvedCompositionArc",
                "USDExchangePureSwiftImportTests.standaloneUSDAImportRejectsVariantOpinionBeforeMaterialization",
                "USDExchangePureSwiftImportTests.pureSwiftUSDZImportComposesPackagedSublayers",
                "USDExchangeTopologyTests.importPreservesFaceVaryingNormalsThroughMeshExpansion",
                "USDExporterCodecTests",
                "USDExchangeResourceLimitTests",
                "KernelCapabilityContractTests",
            ]
        ),
    ])

    private static func feature(
        id: String,
        operation: String,
        inputs: [String],
        outputs: [String],
        fixtures: [String],
        failureCodes: [KernelErrorCode] = [
            .invalidInput, .missingReference, .unsupportedCapability, .topologyFailure,
        ],
        additionalPublicAPIs: [String] = []
    ) -> KernelCapability {
        KernelCapability(
            id: id,
            operation: operation,
            status: .partial,
            acceptedInputs: inputs,
            exactOutputs: outputs,
            failureCodes: failureCodes,
            tolerance: .standard,
            publicAPIs: [
                "CADIR.FeatureRequest",
                "CADIR.CADCommand.appendFeature",
                "SwiftCAD.DocumentBuilder.\(operation)",
            ] + additionalPublicAPIs,
            testFixtures: fixtures
        )
    }
}
