import CADCore

extension KernelCapabilities {
    static let modelingEditCapabilities: [KernelCapability] = [
        feature(
            id: "MODEL-FACELOOPOFFSET-001",
            operation: "faceLoopOffset",
            topology: .solidBody,
            inputs: [
                "oneValidatedSolidBody",
                "oneStableSelectedStrictlyConvexLineOnlyPlanarFace",
                "positiveInwardDistancePreservingEveryOffsetHalfspace",
            ],
            outputs: [
                "validatedExactSplitBRep",
                "coplanarRingAndCenterFaces",
                "affineFaceLocalPcurves",
                "deterministicNEdgeTopology",
                "preservedAnalyticVolume",
                "strictCurrentSchemaPersistence",
                "generatedAndPreservedTopologyLineage",
            ],
            fixtures: [
                "FaceLoopOffsetFeatureTests",
                "CADIRTests",
                "SwiftCADTests.facadeBuildsPlanarEditFeaturesThroughSharedOperations",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .classificationFailure,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.FaceLoopOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-EDGEOFFSET-001",
            operation: "edgeOffset",
            topology: .solidBody,
            inputs: [
                "oneValidatedSolidBody",
                "oneStableSelectedEdgeOnStrictlyConvexLineOnlyPlanarSupportFace",
                "positiveInwardDistanceKeepingBothIntersectionsInsideAdjacentEdges",
                "optionalSymmetricSplitAcrossUniqueOppositeSupportFace",
            ],
            outputs: [
                "validatedExactSplitBRep",
                "stripAndRemainderFaces",
                "affineFaceLocalPcurves",
                "splitAdjacentEdgesAndVertices",
                "preservedAnalyticVolume",
                "strictCurrentSchemaNativePersistence",
                "deterministicGeneratedPreservedAndSplitTopologyLineage",
            ],
            fixtures: ["EdgeOffsetFeatureTests", "EdgeOffsetBuilderTests"],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .classificationFailure,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.EdgeOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEKNIFE-001",
            operation: "faceKnife",
            topology: .solidBody,
            inputs: [
                "oneValidatedSolidBody",
                "oneStableSelectedLineOnlyPlanarFaceWithOneOuterLoop",
                "oneCoplanarStrictlyInteriorSimpleLineKnifeLoopIncludingConcaveLoops",
            ],
            outputs: [
                "validatedExactSplitBRep",
                "coplanarRingAndCenterFaces",
                "affineFaceLocalPcurves",
                "preservedAnalyticVolume",
                "strictCurrentSchemaNativePersistence",
                "deterministicPreservedSplitAndGeneratedTopologyLineage",
                "typedAmbiguousSourceFaceSelectionAfterSplit",
                "noCarriedTopologyAliases",
            ],
            fixtures: ["FaceKnifeFeatureTests", "FaceKnifeBuilderTests"],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .classificationFailure,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.FaceKnifeFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEDELETE-001",
            operation: "faceDelete",
            topology: .sheetBody,
            inputs: [
                "oneValidatedSolidBody",
                "oneOrMoreUniqueStableSelectedFacesOwnedByTheTargetBody",
                "atLeastOneRemainingFaceInEverySourceShell",
            ],
            outputs: [
                "validatedExactSheetBRep",
                "deterministicEdgeConnectedShellPartition",
                "orphanFreeTopologyAndGeometry",
                "mandatoryFaceLocalPcurves",
                "strictCurrentSchemaNativePersistence",
                "targetBodyScopedIdentityReplacement",
                "preservedUnrelatedBodiesAndSelections",
                "preservedBodyFaceEdgeAndVertexLineage",
            ],
            fixtures: [
                "FaceDeleteFeatureTests",
                "FaceDeleteSchemaTests",
                "FaceDeleteBuilderTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.FaceDeleteFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEDRAFT-001",
            operation: "faceDraft",
            topology: .solidBody,
            inputs: [
                "oneValidatedLineOnlyPlanarSolid",
                "oneOrMoreUniquePlanarSideFacesOwnedByTargetBody",
                "eachTargetSharingExactlyOneEdgeWithOnePlanarNeutralFace",
                "finiteNonzeroSignedIncrementalAngleBelowNinetyDegrees",
            ],
            outputs: [
                "constraintSolvedExactPlanarBRep",
                "verifiedConstraintResiduals",
                "deterministicGeometryIDs",
                "mandatoryFaceLocalPcurves",
                "analyticVolume",
                "strictCurrentSchemaNativePersistence",
                "targetBodyScopedIdentityReplacement",
                "preservedUnrelatedBodiesAndSelections",
                "preservedBodyFaceEdgeAndVertexLineage",
            ],
            fixtures: [
                "FaceDraftFeatureTests",
                "FaceDraftSchemaTests",
                "FaceDraftBuilderTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
                .singularSystem,
                .conflictingConstraints,
            ],
            additionalPublicAPIs: ["CADModeling.FaceDraftFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CHAMFER-001",
            operation: "chamfer",
            topology: .solidBody,
            inputs: [
                "singleStraightEdgeOwnedByTargetBody",
                "singleShellSolid",
                "twoPerpendicularPlanarIncidentFaces",
                "positiveEqualDistance",
            ],
            outputs: [
                "validatedExactBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "strictCurrentSchemaNativePersistence",
                "targetBodyScopedIdentityReplacement",
                "targetBodyScopedLineageParents",
                "typedAmbiguousSourceEdgeSelectionAfterSplit",
                "TopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["ChamferFeatureTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
                .ambiguousSelection,
            ],
            additionalPublicAPIs: ["CADModeling.ChamferFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FILLET-001",
            operation: "fillet",
            topology: .solidBody,
            inputs: [
                "singleStraightConvexEdgeOwnedByTargetBody",
                "singleShellOrthogonalSolid",
                "twoPerpendicularPlanarIncidentFaces",
                "positiveConstantRadius",
            ],
            outputs: [
                "validatedExactBRep",
                "quarterCylinder",
                "verifiedG1Tangency",
                "faceLocalPcurves",
                "analyticVolume",
                "deterministicEvaluation",
                "strictRequestDecoding",
                "strictCurrentSchemaNativePersistence",
                "targetBodyScopedIdentityReplacement",
                "targetBodyScopedLineageParents",
                "typedAmbiguousSourceEdgeSelectionAfterSplit",
                "TopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: [
                "FilletFeatureTests",
                "EdgeBlendOwnershipTests",
                "CrossBodyReplacementFeatureTests",
                "ModelingFeatureSchemaTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
                .ambiguousSelection,
            ],
            additionalPublicAPIs: ["CADModeling.FilletFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-G2BLEND-001",
            operation: "g2Blend",
            topology: .solidBody,
            inputs: [
                "singleStraightConvexEdgeOwnedByTargetBody",
                "singleShellOrthogonalSolid",
                "twoPerpendicularPlanarIncidentFaces",
                "positiveSymmetricSetbackDistance",
            ],
            outputs: [
                "validatedExactBRep",
                "quinticBSplineSurface",
                "verifiedG2Tangency",
                "faceLocalPcurves",
                "analyticVolume",
                "deterministicEvaluation",
                "strictRequestDecoding",
                "strictCurrentSchemaNativePersistence",
                "targetBodyScopedIdentityReplacement",
                "targetBodyScopedLineageParents",
                "typedAmbiguousSourceEdgeSelectionAfterSplit",
                "TopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: [
                "G2BlendFeatureTests",
                "EdgeBlendOwnershipTests",
                "CrossBodyReplacementFeatureTests",
                "ModelingFeatureSchemaTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
                .ambiguousSelection,
            ],
            additionalPublicAPIs: ["CADModeling.G2BlendFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SETBACKCORNER-001",
            operation: "setbackCorner",
            topology: .solidBody,
            inputs: [
                "oneTargetBodyOwnedTrihedralConvexVertex",
                "oneOrthogonalHexahedralSolid",
                "threeMutuallyPerpendicularStraightEdges",
                "positiveEqualRollingBallRadius",
            ],
            outputs: [
                "validatedExactBRep",
                "threeQuarterCylinders",
                "sphericalOctant",
                "verifiedG1Tangency",
                "sphericalGreatCirclePcurves",
                "analyticVolume",
                "deterministicEvaluation",
                "strictRequestDecoding",
                "strictCurrentSchemaNativePersistence",
                "targetBodyScopedIdentityReplacement",
                "targetBodyScopedLineageParents",
                "typedAmbiguousSourceVertexSelectionAfterSplit",
                "TopologyLineage",
                "deterministicRightHandedEdgeOrdering",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: [
                "SetbackCornerFeatureTests",
                "SetbackCornerOwnershipTests",
                "SphericalGreatCirclePcurveTests",
                "CrossBodyReplacementFeatureTests",
                "ModelingFeatureSchemaTests",
            ],
            status: .supported,
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
                .ambiguousSelection,
            ],
            additionalPublicAPIs: ["CADModeling.SetbackCornerFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-SHELL-001",
            operation: "shell",
            topology: .solidBody,
            inputs: [
                "oneOrthogonalHexahedralSolid",
                "oneRemovedPlanarFace",
                "positiveUniformInwardThickness",
            ],
            outputs: [
                "validatedExactBRep",
                "fiveOuterFaces",
                "fiveInnerOffsetFaces",
                "fourOpeningRimFaces",
                "analyticVolume",
                "strictRequestDecoding",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["ShellFeatureTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.ShellFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-EDGEMOVE-001",
            operation: "edgeMove",
            topology: .solidBody,
            inputs: [
                "oneLineOnlyPlanarSolid",
                "oneStraightEdge",
                "finiteDirection",
                "finiteSignedDistancePreservingPlanarityAndVolume",
            ],
            outputs: [
                "validatedExactBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["EdgeMoveFeatureTests", "EdgeMoveBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.EdgeMoveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-VERTEXMOVE-001",
            operation: "vertexMove",
            topology: .solidBody,
            inputs: [
                "oneSingleShellLineOnlyPlanarSolid",
                "oneVertex",
                "finiteDirection",
                "finiteSignedDistancePreservingPositiveVolume",
            ],
            outputs: [
                "validatedExactBRep",
                "nonPlanarIncidentFaceTriangulation",
                "faceLocalPcurves",
                "analyticVolume",
                "splitAndPreservedTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["VertexMoveFeatureTests", "VertexMoveBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.VertexMoveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEOFFSET-001",
            operation: "faceOffset",
            topology: .solidBody,
            inputs: [
                "oneConvexLineOnlyPlanarSolid",
                "onePlanarFace",
                "finiteSignedNormalDistancePreservingConvexPositiveVolume",
            ],
            outputs: [
                "validatedExactBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["FaceOffsetFeatureTests", "FaceOffsetBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.FaceOffsetFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-FACEMOVE-001",
            operation: "faceMove",
            topology: .solidBody,
            inputs: [
                "oneConvexLineOnlyPlanarSolid",
                "onePlanarFace",
                "finiteDirection",
                "finiteSignedDistancePreservingConvexPositiveVolume",
            ],
            outputs: [
                "validatedExactBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["FaceMoveFeatureTests", "FaceMoveBuilderTests", "DirectEditSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.FaceMoveFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-LINEARPATTERN-001",
            operation: "linearPattern",
            topology: .solidBody,
            inputs: [
                "oneLineOnlyPlanarSolid",
                "finiteDirection",
                "positiveSpacing",
                "twoToOneThousandSeparatedInstances",
            ],
            outputs: [
                "validatedExactMultiShellBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "splitTopologyLineage",
                "typedAmbiguousSourceSelection",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["LinearPatternFeatureTests", "LinearPatternBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .resourceLimitExceeded,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.LinearPatternFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-RADIALPATTERN-001",
            operation: "radialPattern",
            topology: .solidBody,
            inputs: [
                "oneLineOnlyPlanarSolid",
                "finiteAxis",
                "finiteNonzeroAngularSpacing",
                "twoToOneThousandSeparatedInstances",
            ],
            outputs: [
                "validatedExactMultiShellBRep",
                "rigidlyRotatedAnalyticGeometry",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "splitTopologyLineage",
                "typedAmbiguousSourceSelection",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["RadialPatternFeatureTests", "PatternBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .resourceLimitExceeded,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.RadialPatternFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-GRIDPATTERN-001",
            operation: "gridPattern",
            topology: .solidBody,
            inputs: [
                "oneLineOnlyPlanarSolid",
                "twoFiniteNonparallelDirections",
                "twoPositiveSpacings",
                "fourToOneThousandSeparatedInstances",
            ],
            outputs: [
                "validatedExactMultiShellBRep",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "splitTopologyLineage",
                "typedAmbiguousSourceSelection",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["GridPatternFeatureTests", "PatternBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .resourceLimitExceeded,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.GridPatternFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-CURVEDRIVENPATTERN-001",
            operation: "curveDrivenPattern",
            topology: .solidBody,
            inputs: [
                "oneLineOnlyPlanarSolid",
                "oneConnectedOpenEvaluatedCurveChain",
                "finiteAnchorAndReferenceDirection",
                "twoToOneThousandSeparatedInstances",
            ],
            outputs: [
                "validatedExactMultiShellBRep",
                "equalArcLengthPlacement",
                "minimumRotationTangentAlignment",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "splitTopologyLineage",
                "typedAmbiguousSourceSelection",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["CurveDrivenPatternFeatureTests", "CurveDrivenPatternBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .ambiguousSelection,
                .unsupportedCapability,
                .resourceLimitExceeded,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.CurveDrivenPatternFeatureEvaluator"]
        ),
        feature(
            id: "MODEL-THICKEN-001",
            operation: "thicken",
            topology: .sheetToSolidBody,
            inputs: [
                "onePlanarSheetFace",
                "oneStraightOuterBoundaryLoop",
                "positiveUniformThickness",
                "positiveNegativeOrSymmetricSide",
            ],
            outputs: [
                "validatedExactBRep",
                "planarPrismaticSolid",
                "faceLocalPcurves",
                "analyticVolume",
                "strictRequestDecoding",
                "dimensionPreservingTopologyLineage",
                "preservedUnrelatedBodiesAndSelections",
            ],
            fixtures: ["ThickenFeatureTests", "ThickenBuilderTests", "CrossBodyReplacementFeatureTests", "ModelingFeatureSchemaTests"],
            failureCodes: [
                .invalidInput,
                .missingReference,
                .unsupportedCapability,
                .topologyFailure,
                .nonManifoldResult,
            ],
            additionalPublicAPIs: ["CADModeling.ThickenFeatureEvaluator"]
        ),
    ]
}
